"""phase4 soft delete columns

Revision ID: c7c1300e5936
Revises: b1d0b04b9825
Create Date: 2026-05-27 22:20:19.730889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c1300e5936'
down_revision: Union[str, Sequence[str], None] = 'b1d0b04b9825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_matches_deleted_at'), 'matches', ['deleted_at'], unique=False)
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sessions_deleted_at'), 'sessions', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_deleted_at'), table_name='sessions')
    op.drop_column('sessions', 'deleted_at')
    op.drop_index(op.f('ix_matches_deleted_at'), table_name='matches')
    op.drop_column('matches', 'deleted_at')
    # ### end Alembic commands ###
