// src/LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';
import { setDisplayLanguage } from './gameData';

const LanguageContext = createContext();

export const translations = {
  ko: {
    back: "뒤로", loading: "데이터 로딩 중...", noData: "데이터가 없습니다.", add: "추가",
    dashboard: "대시보드", sessions: "스크림 세션", overall: "전체 통계", teamManage: "팀 관리 (준비중)",
    navGroupStats: "통계", navGroupAnalysis: "분석", navBanpick: "밴픽",
    ssCalendar: "달력", ssList: "리스트",
    title: "스크림 데이터 센터", desc: "오버워치 스크림 로그를 업로드하여 팀의 퍼포먼스를 분석하세요.", desc2: "데이터는 서버에 안전하게 저장됩니다.",
    createScrim: "스크림 생성하기", viewHistory: "기록 보기", uploading: "업로드 중...",
    modalTitle: "스크림 기록 생성", step1Title: "기본 정보 입력", step1Desc: "스크림 날짜와 시간을 입력해주세요.",
    scrimName: "스크림 이름", scrimNamePlace: "예: 2024-05-20 vs 상대팀 스크림", videoUrl: "유튜브 전체 영상 링크",
    date: "날짜", time: "시간", next: "다음: 경기 입력하기", prev: "이전", save: "저장 및 완료", success: "스크림 저장 완료!",
    backToList: "목록으로 돌아가기", totalDuration: "총 경기 시간", roundScore: "라운드 스코어",
    finalBlows: "최종 타격", fightWins: "전투 승리", ultEconomy: "궁극기 효율", lowerBetter: "낮을수록 좋음",
    lead: "우세", draw: "무승부", win: "승리", tabStats: "스텟", tabKillLog: "킬 로그", tabChart: "차트",
    tabEvent: "이벤트", tabPlayer: "플레이어 통계", totalCumulative: "전체 (누적)", round: "라운드",
    fightSurvivors: "한타별 생존 인원", survivors: "명 생존", duration: "지속", avgSurvivors: "평균 생존",
    firstBloodAnalysis: "선취점 분석 승률", standard: "기준", situation: "상황", fightCount: "전투 횟수",
    winRate: "승률", fbSecured: "선취점 획득 시", fbSuffered: "선취점 허용 시", ultsPerFight: "한타 당 궁극기 사용",
    fbByRole: "역할별 결정타", cumulativeDmg: "라운드별 누적 영웅 피해", dmgEfficiency: "딜링 효율성 분석",
    heroDmgDealt: "가한 영웅 피해", battery: "딜만 넣는 배터리 (비효율)", carry: "캐리 (딜+킬)", role: "역할",
    player: "플레이어", team: "팀", playTime: "시간", elims: "처치", deaths: "죽음", assists: "지원",
    heroDmg: "영웅 딜", barrierDmg: "방벽 딜", healRcvd: "받은 힐", dhRatio: "딜:힐 비", healing: "준 힐",
    dmgTaken: "받은 딜", ults: "궁극기", fight: "전투", noEvents: "이벤트 없음", noUlts: "궁극기 사용 기록 없음",
    events: "이벤트", ultimatesUsed: "사용된 궁극기", pickRate: "점유율", soloKills: "단독 처치", ultUsage: "궁극기 사용",
    per10: "/ 10분", tank: "탱크", dps: "딜러", support: "지원",
    filterPlaceholder: "필터 입력 (예: 리장 타워, 우양, 루시우, 승리 ...)", filterTip: "선수 이름, 맵, 영웅 등을 입력하여 상세 분석을 해보세요.",
    searchedGames: "검색된 경기", avgWinRate: "평균 승률", avgKills: "평균 처치", avgDeaths: "평균 데스", avgDmg: "평균 딜량",
    tabHighlights: "하이라이트 & 요약", tabHeroes: "영웅별 통계", tabMaps: "맵별 통계", highlights: "하이라이트",
    noMoments: "조건에 맞는 장면이 없습니다.", heroStatsTitle: "영웅별 성적 (필터 기준)", mapStatsTitle: "맵별 통계",
    hero: "영웅", gamesPlayed: "게임 수", kda: "KDA",
    dateFilter: "기간 설정", startDate: "시작일", endDate: "종료일", allDates: "전체 기간",
    ultStatsTitle: "궁극기 가치 및 한타 분석", ultCountVsWin: "팀 궁극기 투자 개수 대비 한타 승률", ultEfficiency: "영웅별 궁극기 가치 (한타 승률 순)",
    ultUses: "사용 횟수",
    baseTeam: "기준 팀", allTeams: "전체 팀",
    matchStart: "경기 시작 시점", matchEnd: "경기 종료 시점",
    objectiveCaptured: "거점 점령", flNoDataInPeriod: "선택한 기간에 스크림 데이터가 없습니다 (마지막 스크림: {date})", flShowAllPeriod: "전체 기간 보기",
    matchStartTip: "영상에서 전투 시작(카운트다운 끝) 시점",
    navUltimateStats: "궁극기 통계", navFirstKill: "퍼킬 통계", navFirstDeath: "퍼뎃 통계", navFirstFight: "첫한타", navPersonal: "개인 통계",
    ffTitle: "첫 한타 모아보기", ffDesc: "각 맵·라운드의 첫 교전 시점을 모아 영상으로 바로 점프합니다. (쟁탈/화물/혼합은 라운드별, 플래시포인트/밀기는 매치당 1개)",
    ffAllOpponents: "전체 상대", ffAllMaps: "전체 맵", ffColDate: "날짜", ffColMap: "맵", ffColRound: "라운드", ffColMatchup: "매치업", ffColTime: "교전 시각", ffColLink: "영상",
    ffWatch: "보기", ffNoVideo: "영상 없음", ffLoading: "불러오는 중…", ffError: "데이터를 불러오지 못했습니다.",
    // FirstKillStats
    fkTitle: "퍼킬 분석", fkDesc: "한타를 터뜨리는 캐리력과 주력 희생양, 사용 스킬을 상세히 분석합니다.",
    allPositions: "전체 포지션", matchup: "특정 매치업:", myTeamAll: "우리 팀 (전체)", enemyTeamAll: "상대 팀 (전체)",
    position: "포지션", fkColFights: "한타 횟수", fkColCount: "퍼킬 횟수", fkColRate: "퍼킬 비율 (%)",
    timesUnit: "회", fkTopVictims: "주요 희생양 (Player)", fkTopHeroes: "집중 공략 영웅 (Hero)", fkKillSkill: "결정타 스킬 (누구에게 적중?)",
    noFilteredData: "조건에 맞는 데이터가 없습니다.",
    // FirstDeathStats
    fdTitle: "퍼뎃 분석", fdDesc: "선수들의 생존 능력과, 주로 누구에게/어떤 스킬에 먼저 죽었는지를 상세히 분석합니다.",
    fdColCount: "퍼뎃 횟수", fdColRate: "퍼뎃 비율 (%)",
    fdNemesis: "천적 (Player)", fdWatchHeroes: "경계 대상 영웅 (Hero)", fdDeadlySkill: "치명적 스킬 (누구의 스킬을 맞았는가)",
    // PlayerProfileView
    all: "전체", ppNoPlayers: "집계된 선수 데이터가 없습니다.", ppRosterTitle: "선수단 목록", ppSearchPlaceholder: "선수 검색...",
    ppOverallKd: "종합 K/D", ppDmgPer10: "10분당 딜량", ppHealPer10: "10분당 힐량", ppUltPerMatch: "경기당 궁극기",
    ppHeroPool: "모스트 영웅 풀", ppNoHeroes: "영웅 플레이 기록이 없습니다.", ppRecentForm: "최근 K/D 폼 (Form)",
    ppSelectPrompt: "왼쪽 목록에서 선수를 선택해주세요.",
    // PlayerCompareView
    navCompare: "선수 비교",
    pcRosterTitle: "선수 선택", pcSelectHint: "2명 이상 선택하세요", pcSelectedCount: "명 선택됨",
    pcSelectPrompt: "비교할 선수를 2명 이상 선택해주세요.",
    pcMetricCompare: "지표 비교", pcScopeLabel: "범위", pcScopeAll: "전체 (종합)",
    pcRadarTitle: "종합 능력치 (상대 비교)", pcRadarHint: "선택된 선수 중 최고값 기준 100% 환산",
    pcHeroCompare: "영웅별 비교", pcSelectHeroLabel: "영웅 선택:", pcNoHeroRecord: "기록 없음",
    pcHeroPlayTime: "플레이 시간", pcBest: "최고", pcMetricKd: "K/D", pcMetricWinRate: "승률",
    pcHeroUltEff: "궁당 킬", pcHeroUltWin: "궁 한타 승률", pcHeroUltGames: "한타", pcHeroUltUses: "궁", pcHeroUltCharge: "평균 궁 충전", pcSecUnit: "초", pcHeroImpact: "영향력 (처치/10)",
    pcMetricDmg: "10분당 딜", pcMetricHeal: "10분당 힐", pcMetricUlt: "경기당 궁극기", pcMin: "분",
    pcMetricMitig: "10분당 경감", pcMetricFb: "10분당 결정타", pcMetricSecondaryMixed: "10분당 보조 지표",
    pcTagHeal: "힐", pcTagMitig: "경감", pcTagFb: "결정타",
    // MatchStats
    msNoFights: "기록된 전투(킬)가 없습니다.", msUltEffWin: "효율적 승리 (덜 씀)", msUltSaveLoss: "궁 아끼다 패배", msUltOverInvest: "과투자 (2개 이상 초과)",
    msLostFightTitle: "패배 한타 저항력 (Kill Exchange in Lost Fights)", msAvgKillRateOnLoss: "패배 시 평균 적 처치율",
    msAvgWord: "평균 ", msKillsUnit: "명 처치", msLossUnit: "회 패배", msResistKills: "저항 킬 수",
    msMomentumTitle: "한타 모멘텀 (연속 승률 및 턴 뒤집기)", msWinRateAfterWin: "자리 먹었을 때 승률", msWinToWin: "(승리 ➔ 승리)", msSnowball: "유리함을 굳히는 능력",
    msWinRateAfterLoss: "자리 못 먹었을 때 승률", msLossToWin: "(패배 ➔ 승리)", msComeback: "턴을 뒤집는 능력",
    msFirstDeathAnalysis: "선취점 획득 및 개인별 데스 분석 (First Deaths)", msFirstKillCountTeam: "선취점 획득 횟수 (팀)", msFirstDeathRank: "퍼스트 데스 순위",
    msPlayerHero: "선수 (Hero)", msFirstBloodDeaths: "퍼블 데스", msDeathCause: "주요 데스 원인 (누구의 스킬을 맞았는가)", msNoDataShort: "데이터 없음",
    msUltSummary: "궁극기 종합 (Ultimates)", msTotalUlts: "총 궁극기 사용 횟수 (Total Ultimates Used)", msFirstUltInFight: "한타 첫 궁극기 사용 (Used Ult First in Fight)", msUltTiming: "궁극기 사용 타이밍 (Timing)",
    msPhaseEarly: "초반 (진입)", msPhaseMid: "중반", msPhaseLate: "후반", msUltExchange: "궁극기 교환비 및 과투자 (Ult Exchange)",
    msAvgConsumed: "평균 소모", msWonFight: "승리한 한타:", msLostFightLabel: "패배한 한타:", msCountUnit: "개",
    msNoVideo: "해당 경기는 영상 기록이 없습니다", msTabStats: "스탯표", msTabKill: "킬 로그", msTabChart: "상세 분석 차트", msTabTimeline: "타임라인", msTabCompare: "선수 비교",
    // 궁극기 타임라인 서브탭
    msTabUltTl: "궁극기 타임라인",
    msUltTlNote: "한타별 궁 흐름입니다. 궁 옆의 +X.Xs는 그 한타의 첫 궁 기준 상대 시간이며, 영상 링크는 한타 시작 약 12초 전부터 재생됩니다.",
    msUltTlFight: "한타", msUltTlWinner: "승자", msUltTlDraw: "판정 불가", msUltTlNoUlt: "궁 사용 없음",
    // 매치 상세 요약 카드·라운드 탭·이벤트 라벨 (i18n)
    msBackToOverview: "요약으로", msTotalTime: "총 경기 시간", msScoreLabel: "스코어", msWinnerLabel: "승자",
    msFinalBlows: "결정타", msFightWins: "한타 승리", msUltEconomy: "궁 효율",
    msOverview: "종합", msRoundLabel: "{n}라운드",
    msMultiKill: "멀티킬", msTeamKill: "팀킬", msKillsUnit: "킬",
    // 세션 리스트·스크림 상세 (i18n)
    matchCount: "매치 {n}개", sdMatchList: "매치 목록", sdResult: "결과", sdAnalyze: "분석", sdUnknown: "알 수 없음",
    sdEdit: "편집", sdEditSession: "세션 정보 수정", sdSave: "저장", sdCancel: "취소",
    sdOppRename: "상대팀명 변경", sdOppRenameHint: "기준 팀({team})은 변경할 수 없습니다. 등록 시 오타 교정 용도.",
    sdMatchEdit: "수정", sdOrder: "순서", sdVodOffset: "영상 오프셋 (MM:SS)",
    sdAddLog: "로그 추가", sdReplaceLog: "로그 교체",
    sdReplaceWarn: "이 매치의 기존 로그 데이터(라운드·이벤트·선수 통계)가 삭제되고 새 로그로 재파싱됩니다. 복구는 git 이전 커밋 또는 일일 백업으로만 가능합니다. 계속할까요?",
    sdDiffTitle: "수기 입력값과 파싱 결과가 다릅니다:",
    sdDiffAdopt: "[확인] = 파싱 결과 채택 · [취소] = 수기값 유지(승자는 승패 보정으로 이동)",
    sdManualBadge: "수기", sdEditFail: "수정 실패: ", sdUploadDone: "로그가 반영되었습니다.",
    // Common (buttons / delete dialogs)
    delete: "삭제", reset: "초기화", cancelSelection: "선택 취소", selectAll: "전체 선택", deselectAll: "전체 해제",
    selectedCount: "선택됨", deleting: "삭제 중...", deleteSelected: "선택 삭제", deleteConfirmPre: "선택한 ",
    sdIrreversible: "이 작업은 되돌릴 수 없습니다.", sdDeleteDone: "삭제 완료", sdWarnings: "경고:",
    sdPartialFail: "일부 삭제 실패: ", sdDeleteFail: "삭제 실패: ", sdDeleteMatchPost: "개 매치를 삭제하시겠습니까?",
    ssDeleteSessionMid: "개 세션을 삭제하시겠습니까?\n이 세션에 포함된 총 ", ssDeleteSessionPost: "개의 매치도 함께 삭제됩니다.",
    ssRebuildConfirm: "DB를 복구하시겠습니까? (Rebuild DB?)",
    // ScrimModal
    smCloseConfirm: "입력 중인 내용이 사라집니다. 정말 닫으시겠습니까?", smEnterName: "스크림 이름을 입력해주세요.", smMinOneMatch: "최소 1개의 경기를 기록해주세요.",
    smMatchPre: "", smMatchPost: "번 경기: ", smPauseSelectedWarn: "'퍼즈 있음'을 선택하셨습니다. 퍼즈 구간을 추가하거나 '아니오'를 선택해주세요.",
    smPauseTimeWarn: "퍼즈 시작/종료 시간을 모두 입력해주세요. (예: 10:00)", smYoutubeLink: "유튜브 영상 링크", smOptional: "(선택)",
    smTeam1Label: "1팀 이름 (왼쪽)", smTeam2Label: "2팀 이름 (오른쪽)", smStartPlaceholder: "예: 03:30 (전투 시작)",
    smSourceLabel: "매치 유형", smSourceLog: "로그 매치", smSourceManual: "수기 매치 (로그 없음)",
    smManualHint: "로그 없이 맵·승패·스코어만 기록합니다. 로그 표본 지표(한타·궁·선수 통계)에는 포함되지 않으며, 나중에 로그를 추가할 수 있습니다.",
    smWinnerLabel: "승리 팀", smScoreLabel: "스코어 (1팀 : 2팀)", smVodStart: "영상 시작 (MM:SS)", smVodEnd: "영상 끝 (MM:SS, 선택)",
    // UltimateStats
    ultFivePlus: "5개 이상", ultTotal: "총합", ultValue: "가치", ultLowSampleNote: "표본 부족 (5회 미만) · 참고용",
    // OverallStats
    osAnalysis: "분석", osTabFights: "한타 통계", osWinBadge: "승", osLossBadge: "패", osAllAvg: "전체 평균",
    osTabSummary: "요약", osMapWinCard: "맵 승률", osSummaryBasisTpl: "{team} 기준", osTrendCard: "추세 (vs 이전 기간)",
    osTrendHint: "시작일을 설정하면 이전 기간 대비 추세가 표시됩니다", osTrendPrevTpl: "이전 {p} · {n}한타", osFightSampleTpl: "{w}/{n}한타",
    osSummaryEntryHeroes: "영웅별 통계 보기", osSummaryEntryMaps: "맵별 통계 보기", osSummaryEntryHint: "자세히 →",
    osTopHeroTpl: "많이 쓴 영웅: {hero}", osTopMapTpl: "많이 한 맵: {map}", osSecondaryMetrics: "선수 평균 지표 (기간·필터 기준)",
    osShowMore: "더보기", osShowingCountTpl: "{shown} / {total}", osSummaryNoData: "우리 팀 경기 데이터가 없습니다.",
    osNoMatchDataPre: "", osNoMatchDataPost: "의 경기 데이터가 없습니다", osNoFightData: "분석할 한타 데이터가 없습니다",
    osLostFightsSuffix: "회 패배 한타", osResistDescPre: "패배한 한타에서 상대를 ", osResistDescMid: "명 처치 → ", osResistDescPost: "% 처치율. 값이 높을수록 지면서도 교환을 잘 함.",
    osFirstDeathTop3: "퍼스트 데스 TOP 3", osFirstDeathLabel: "퍼스트 데스", osLostFightCarryTop3: "패배 한타 캐리 TOP 3", osNoMin10: "최소 10회 이상 참여 선수 없음",
    osKillsPerFight: "킬/한타", osTotalWord: "총 ", osKillUnit: "킬", osMin10Note: "* 최소 10회 이상 패배 한타 참여 기준",
    osMomentumNotePre: "* 매치 경계를 넘지 않음 · Draw 한타 제외 · 대상 매치: ", osMomentumNotePost: "경기", osEliminated: "사망", osKill: "킬",
    // 탭 재편: 궁극기 분석 / 킬데스 통계
    navUltAnalysis: "궁극기 분석",
    navKillDeath: "킬데스 통계",
    kdToggleFk: "퍼스트킬", kdToggleFd: "퍼스트데스",
    flUaTitle: "궁극기 분석",
    flUaDesc: "궁극기 상황별 승률과 콤보·시퀀스·응수를 분석합니다. 기준 팀 관점.",
    flUaTabSituation: "상황", flUaTabComboSeq: "콤보·시퀀스",
    // [교환 패턴]
    flPatTab: "교환 패턴",
    flPatUs: "아", flPatOpp: "적", flPatNone: "무궁",
    flPatChipUs: "아군", flPatChipOpp: "적군",
    flPatChipUsTip: "아군 궁", flPatChipOppTip: "적군 궁",
    flPatSumFights: "총 한타(판정 가능)", flPatSumKinds: "패턴 종류", flPatSumTop: "최빈 패턴",
    flPatColPattern: "패턴",
    flPatSecUs: "우리 선궁 패턴", flPatSecOpp: "상대 선궁 패턴",
    flPatSecSub: "소계: 표본 {n} · 승률 {w}",
    flPatHotTitle: "주목 패턴",
    flPatBarToggle: "승률 바",
    flPatTableNote: "패턴 = 궁 교환의 순서. 행을 클릭하면 실제 영웅 구성과 VOD가 표시됩니다.",
    flPatOppOther: "기타 {n}",
    flPatInsFirst: "선궁 시(첫 궁이 아군) 승률 {a} ({an}한타) vs 후궁 시 {b} ({bn}한타)",
    flPatInsLast: "마지막 궁이 우리일 때 승률 {a} ({an}한타) vs 상대일 때 {b} ({bn}한타)",
    flExpPat1: "패턴 표기(낱개): 한타의 전체 궁을 시간순으로 궁 하나 = 칩 하나로 나열합니다 — 파랑 배지 = 아군 궁, 빨강 배지 = 적군 궁(타임라인 뷰어와 동일한 팀 색), 궁 0개 한타는 '무궁'. 칩이 6개를 넘으면 앞 6칩 + '…'로 절단해 같은 패턴으로 묶습니다. 이 표의 역할은 궁 '교환의 순서'입니다 — 시간 묶음(콤보) 분석은 [콤보·시퀀스] 서브탭을 참조하세요.",
    flExpPat2: "정렬 규칙: 양팀이 정확히 같은 시각에 궁을 쓰면 우리 궁을 앞으로 정렬합니다(콤보/이니시 분석과 동일 규칙). 발생률·승률·표본은 모두 승패 판정 가능 한타 기준입니다. 표는 첫 칩 기준 [우리 선궁]/[상대 선궁] 섹션으로 나뉘며, 섹션 헤더의 소계 승률은 그 섹션 한타 전체의 가중 평균입니다.",
    flExpPat3: "Δ(vs 상대) = 이 패턴의 우리 승률 − 미러 패턴(아군↔적군 반전)의 상대 승률(= 1 − 그 패턴의 우리 승률). 예: [아군]→[적군]의 비교 대상은 [적군]→[아군]에서의 상대 승률입니다. 미러가 자기 자신인 대칭 패턴(무궁 포함)은 '—'로 표시합니다.",
    flExpPat4: "주의: 패턴 승률은 상관관계일 뿐 인과가 아닙니다 — 궁 개수 자체(투자량)의 효과와 순서의 효과가 섞여 있으니 표본과 함께 해석하세요.",
    flPatOnlyUlt: "궁 사용 한타만 보기",
    flExpPat5: "'궁 사용 한타만 보기'(기본 켬)는 무궁 한타를 표본에서 제외하며, 발생률·요약 숫자·추세도 그 모집단 기준으로 계산됩니다. 끄면 무궁 패턴이 표와 발생률 분모에 포함됩니다(인사이트 줄은 원래 궁 사용 한타만 대상이라 영향 없음).",
    flPatCompTitle: "구성 상위",
    flPatCompNotice: "표본이 작습니다 — 경향 참고용.",
    flPatCompCol: "구성",
    // [이니시]
    flInitTab: "이니시",
    flInitSumRate: "우리 선궁률 ({m}/{n}한타)",
    flInitSumUsWin: "선궁 시 승률 ({n}한타)",
    flInitSumThemWin: "후궁 시 승률 ({n}한타)",
    flInitOurTitle: "우리 이니시 궁",
    flInitOurDesc: "우리가 선궁한 한타를 첫 궁 영웅별로 집계합니다 — 어떤 궁으로 열 때 이기는가. 행 클릭 → 선수별 분해 + VOD.",
    flInitOppTitle: "상대 이니시 궁",
    flInitOppDesc: "상대가 선궁한 한타입니다. 승률은 우리 기준 — 낮을수록 그 이니시에 우리가 힘들었다는 뜻. 행 클릭 → 우리 3초 응수 상위 3 + VOD.",
    flInitColUlt: "이니시 궁", flInitColShare: "이니시 점유율", flInitColDelta: "Δ(vs 선궁 전체)",
    flInitColPlayer: "선수", flInitPlayersTitle: "누가 열었나 (선수별)",
    flInitRespTitle: "이 이니시에 대한 우리 3초 응수 상위 3",
    flInitRespNone: "3초 내 우리 응수가 있었던 한타가 없습니다.",
    flExpInit1: "선궁(이니시) = 한타에서 시간상 첫 번째 궁입니다. 판정은 교환 패턴의 첫 수 정의를 그대로 재사용합니다 — 양팀이 정확히 같은 시각에 궁을 쓰면 우리 궁을 앞으로 정렬(우리 선궁으로 집계). 모집단은 승패 판정 가능 + 궁 사용 한타이며, 무궁 한타는 요약·표 어디에도 포함되지 않습니다(교환 패턴 인사이트 줄과 동일 계산·동일 수치).",
    flExpInit2: "이니시 점유율 = 그 표(우리 선궁/상대 선궁) 안에서 해당 영웅이 첫 궁이었던 비율 — 표별 합 100%. Δ = 그 이니시 궁의 승률 − 그 표 전체(우리 선궁 전체 또는 상대 선궁 전체)의 우리 승률.",
    flExpInit3: "상대 이니시 표의 승률도 항상 우리 기준입니다(낮을수록 그 이니시가 우리에게 위협적). 행을 펼치면 나오는 응수 미니 표는 응수(카운터) 분석과 동일 계산(첫 사용 이후 3초 내 우리 궁, 동시각 제외, 한타당 가장 빠른 응수 1개)이며, 모집단만 '그 궁이 이니시였던 한타'로 좁힌 것입니다.",
    flExpInit4: "주의: 이니시 승률은 상관관계일 뿐 인과가 아닙니다 — 특정 궁으로 열었다는 것은 조합·전황이 이미 유리했다는 신호일 수 있으니 표본과 함께 해석하세요.",
    flExpPatComp: "구성(패턴 행 펼침의 미니 표): 그룹 기준은 '우리 궁 영웅(낱개 순서)'만입니다 — 상대 궁은 그룹 키에 넣지 않아 표본이 쪼개지지 않습니다(시점 전환 시 상대 구성 분석이 됨). 표시는 전체 시퀀스로: 우리 자리는 영웅명(파랑), 상대 자리는 그 그룹 한타들의 실제 상대 궁 빈도를 병기(빨강, 상위 2 + 기타 N)합니다. 예: '키리코 → 적(아나 2/라마트라 1) → 시그마'. 우리 궁이 없는 패턴(적군만)은 구성 표가 없습니다. 구성 행을 클릭하면 VOD 목록이 그 구성의 한타로 좁혀지고, 각 VOD 항목에 그 한타의 완전한 궁 시퀀스(아/적 + 영웅)가 한 줄로 표시됩니다.",
    // FightLabStats (한타 분석 베타)
    navFightLab: "한타 분석",
    flTitle: "한타 분석",
    flDesc: "한타 단위 상황별 승률을 기간별로 비교합니다. 기준 팀 관점.",
    flTabFights: "교전", flTabUlts: "궁극기", flTabUltSeq: "궁 콤보·시퀀스",
    flPresetAll: "전체", flPreset1w: "최근 1주", flPreset2w: "최근 2주", flPreset1m: "최근 1달", flPresetCustom: "직접 선택",
    flPresetAllBefore: "이전 전체", flPresetPrevSame: "직전 동일 기간",
    flMinSample: "최소 표본",
    flSideDate: "기간", flSideTrend: "추세 기간", flSideView: "시점", flSideOpp: "상대팀", flSideMap: "맵", flSideMin: "최소 표본", flSideFilter: "필터",
    flApply: "적용",
    flScopePeriod: "기간", flScopeTrend: "추세", flScopeView: "시점", flScopeOpp: "상대", flScopeMap: "맵", flScopeNone: "없음",
    flOverlapWarn: "최근 기간과 과거 기간이 겹칩니다. 표본이 중복 집계되므로 해석에 주의하세요.",
    flColSituation: "상황", flColOccur: "발생률", flColDOcc: "Δ발생률 (vs 상대)",
    flColWin: "승률", flColDWin: "Δ승률 (vs 상대)", flColSampleOne: "표본",
    flColTrend: "추세 (vs 과거)", flColStability: "안정성", flColStatus: "상태",
    flStabStable: "안정", flStabVolatile: "변동", flStatusOk: "제공",
    flUnitPp: "%p", flTipUs: "우리", flTipOpp: "상대",
    flLowSample: "표본 부족",
    flRecentShort: "최근", flPastShort: "과거",
    flCmpPastAll: "과거 전체", flCmpPrevPrefix: "직전 ",
    flVerdictImproved: "개선", flVerdictWorse: "악화", flVerdictSame: "유지",
    flPerspUs: "우리 시점", flPerspThem: "상대 시점",
    flPerspNotice: "상대 시점 — 표시된 승률·발생률·총평은 모두 상대팀 기준입니다. 상대 데이터는 우리 팀과의 스크림에서만 수집된 표본입니다.",
    // [선수] 서브탭
    flTabPlayers: "선수",
    flPbGroupPlayer: "선수별", flPbGroupPlayerHero: "선수+영웅별",
    flPbColPlayer: "선수", flPbGroupFight: "한타 지표", flPbGroupRound: "라운드 지표",
    flPbFights: "한타 수", flPbKp: "킬 관여율", flPbFk: "첫 킬/한타", flPbFd: "첫데스/한타",
    flPbUpf: "궁/한타", flPbUwin: "궁 사용 한타 승률", flPbKd: "K/D", flPbDmg10: "딜량/10분",
    flPbHeal10: "힐량/10분", flPbUlt10: "궁 수/10분",
    flPbPoolAvg: "풀평균", flPbPoolShortPre: "풀 부족(", flPbPoolShortPost: "명)",
    flPbTipSample: "표본",
    flPbRankTpl: "{n}명 중 {k}위",
    flPbRankShortTpl: "{k}위", flPbNoPool: "풀 부족",
    flPbRankRoleTpl: "{role} {k}위",
    flPbRoleTank: "탱커", flPbRoleDps: "딜러", flPbRoleSup: "지원",
    flPbTipVsPast: "과거 대비",
    flPbColSignals: "시그널",
    flPbSigTopSuffix: " 상위", flPbSigLowSuffix: " 주의",
    flPbGroupLabel: "그룹 기준", flPbSortLabel: "정렬 기준", flPbSortName: "선수명",
    flPbUnitFight: "한타", flPbUnitRound: "라운드",
    flPbPDashSample: "순위 없음: 본인 표본이 풀 최소 기준(한타 20 / 라운드 10) 미달",
    flPbFootnote: "각 셀은 값, 추세 화살표(과거 대비), (괄호 = 같은 역할 풀(우리+상대) 내 순위)입니다. 셀에 마우스를 올리면 풀 인원 등 상세가 표시됩니다. 순위가 무의미하면 (—) 또는 (풀 부족)으로 표기합니다.",
    flPbPoolTpl: "{role} 풀: 우리 {us}명 + 상대 {them}명",
    flPbPoolWarn: "※ 순위는 우리 팀과의 스크림에서 수집된 데이터 기준입니다. 상대 선수 수치는 우리 팀전 한정 표본이며, 풀이 작을 경우 순위가 크게 요동칠 수 있습니다.",
    flPbExpSrc: "지표는 두 출처를 씁니다 — [한타 지표]는 킬·궁 이벤트 기반(교전/궁극기 탭과 동일 데이터), [라운드 지표]는 라운드 요약표(개인 통계 탭과 동일 데이터) 기반이라 서로 기준이 다를 수 있습니다.",
    flPbExpFights: "한타 수: 본인이 출전한 라운드에서 발생한 우리 팀의 한타 수.",
    flPbExpKp: "킬 관여율: 팀 킬이 1개 이상 나온 한타에서 (본인 킬 ÷ 팀 킬)의 평균.",
    flPbExpFkFd: "첫 킬/한타·첫데스/한타: 한타의 첫 킬을 본인이 낸 / 본인이 당한 비율. 첫데스는 낮을수록 좋으며 화살표·팀평균 색·순위 방향이 모두 반전됩니다.",
    flPbExpAxes: "셀 읽는 법: '값 ↑ (5위)' 한 줄 — 값은 현재 기간, 화살표는 자기 과거(추세 기간) 대비(첫데스 등 반전 지표는 색 반전, 변화 없음은 →), 괄호 = 같은 역할 풀(우리+상대) 내 공동 순위(동점은 순위 공유, 반전 지표는 좋은 방향 기준 1위). 마우스를 올리면 풀 인원(예: 13명 중 5위)·과거 대비 변화·표본·풀평균 대비·풀 구성이 표시됩니다. 시그널의 상·하위 20% 판정도 이 등수÷인원 기준입니다.",
    flExpSidebar: "왼쪽 사이드바에서 기간·추세 기간·시점·상대팀/맵·최소 표본을 설정한 뒤 '적용'을 눌러야 반영됩니다. 기간을 '전체'로 선택하면 비교(Δ·화살표)가 표시되지 않습니다.",
    flPbExpSignals: "시그널: 풀 인원이 충족된 지표에서 상위 20% 이내면 초록(강점), 하위 20% 이내면 빨강(주의). 반전 지표는 반전 방향 기준입니다. 선수당 최대 2개(주의 우선)이며 표시 전용 — 총평에는 집계되지 않습니다.",
    flPbExpPool: "순위 풀은 상대팀/맵 필터와 무관하게 '최근 기간 전체 데이터' 기준입니다(필터로 풀이 줄어 순위가 무의미해지는 것 방지). 최소 표본: 한타 지표 20한타 / 라운드 지표 10라운드. 풀이 8명 미만이면 '풀 부족'으로 표시합니다.",
    flPbExpHeal: "힐량/10분은 힐러(지원)만 표시합니다. 10분당 환산은 출전 라운드의 duration 합 기준이며, duration이 없는 라운드는 표본에서 제외합니다.",
    // 순위표(리더보드)
    flLbTitle: "순위표",
    flLbMetric: "지표", flLbRole: "역할",
    flLbColRank: "순위", flLbColTeam: "소속", flLbColValue: "값",
    flLbUnranked: "순위 외 (표본 부족)",
    flLbSupportOnly: "이 지표는 지원 역할만 집계됩니다 — 역할을 '지원'으로 선택하세요.",
    flLbPoolWarnTpl: "풀이 {n}명으로 최소 기준({min}명) 미만입니다 — 순위는 참고용입니다.",
    flPbExpLb: "순위표: 셀 괄호의 '(지원 3위)'와 동일한 풀(최근 기간 전체 데이터 · 우리+상대 · 같은 역할 · 최소 표본 충족)과 동일한 공동 순위 규칙을 표로 펼친 것입니다. 상대팀/맵 필터와 무관하게 기간 전체 기준이며(기존 풀 규칙), 반전 지표(첫데스 등)는 좋은 값이 1위입니다. 표본 미달 선수는 하단에 '순위 외'로 값만 표시됩니다.",
    flRowFirstPick: "퍼스트 킬", flRowFirstDeath: "퍼스트 데스",
    flRowFdTank: "탱커 퍼스트 데스", flRowFdDamage: "딜러 퍼스트 데스", flRowFdSupport: "힐러 퍼스트 데스", flRowFdOther: "기타 퍼스트 데스",
    flRowFkTraded: "퍼킬 내고 트레이드 당함", flRowFdTraded: "퍼뎃 트레이드 성공",
    flRowUltUsed: "궁 사용 한타", flRowFirstUlt: "선궁 (우리가 먼저)", flRowEnemyFirstUlt: "상대 선궁",
    flRowUltAdv: "궁 우위", flRowUltDis: "궁 열세", flRowUltEven: "궁 동수 (양쪽 1개 이상)",
    flRowUlt1: "궁 1개 투자", flRowUlt2: "궁 2개 투자", flRowUlt3: "궁 3개 이상 투자",
    flSumAvgUlt: "한타당 평균 궁 투자 (우리)", flSumUltConv: "궁 전환율 (궁 사용 한타 승률)",
    flUnknownNotePre: "승자 판정 불가 한타(양팀 생존자 동수 = 무승부 처리): ",
    flUnknownNotePost: " — 발생률 분모에는 포함되지만 승률 표본에서는 제외됩니다.",
    flExplainTitle: "지표 설명",
    flExpWinner: "한타 승패: 한타 종료 시 생존자가 더 많은 팀이 승리로 판정됩니다. 생존자가 같으면(무승부) 승률 집계에서 제외됩니다.",
    flExpTwoCols: "각 행에는 성격이 다른 두 숫자가 있습니다 — 그 상황이 얼마나 자주 벌어지는지는 '발생률' 열, 그 상황에 놓였을 때 한타를 이겨내는 능력은 '승률' 열입니다. 행 이름의 (승률)은 승률 열 기준이라는 뜻입니다.",
    flExpOccur: "발생률·승률: 현재 기간의 우리 값입니다. Δ열(vs 상대)은 같은 한타들에서 상대편의 대칭 상황 수치와의 차이입니다 — 예: 첫 킬 획득 행의 Δ발생률 = 우리 첫 킬 획득률 − 상대 첫 킬 획득률(=우리 첫데스율). '낮을수록 좋은' 상황은 색 반전, ±1%p 미만은 회색입니다. 셀에 마우스를 올리면 우리/상대 원값이 표시됩니다.",
    flExpFirstPick: "퍼스트 킬: 한타의 첫 킬을 우리가 낸 경우. 발생률(높을수록 좋음)은 첫 킬을 따내는 빈도, 승률은 첫 킬을 따낸 한타를 실제로 이겼는지입니다.",
    flExpFirstDeath: "퍼스트 데스: 한타의 첫 킬을 우리가 당한 경우. 발생률(낮을수록 좋음)은 먼저 잘리는 빈도, 승률은 그럼에도 한타를 뒤집은 비율입니다.",
    flExpFdRole: "탱커/딜러/힐러 퍼스트 데스: 우리 퍼스트 데스 중 죽은 선수의 영웅 역할별 분해. 발생률(낮을수록 좋음)은 '우리 퍼스트 데스' 안에서 그 역할이 차지하는 비중, 승률은 그 상황에서의 한타 승률입니다.",
    flExpFkTraded: "퍼킬 내고 트레이드 당함: 우리가 첫 킬을 낸 뒤 5초 안에 상대에게 킬을 되돌려받은 경우. 발생률(낮을수록 좋음)은 첫 킬 이득을 헌납하는 빈도, 승률은 그렇게 트레이드된 한타를 그래도 이겼는지입니다. 승률이 오르는 것은 좋은 신호이며, 트레이드가 잦아졌다는 뜻이 아닙니다.",
    flExpFdTraded: "퍼뎃 트레이드 성공: 우리가 첫데스를 당한 뒤 5초 안에 우리도 킬로 되갚은 경우. 발생률(높을수록 좋음)은 불리한 시작을 만회하는 빈도, 승률은 되갚은 한타를 실제로 이겼는지입니다.",
    flExpUltUsed: "궁 사용 한타: 우리가 궁극기를 1개 이상 쓴 한타. 이 행의 승률이 곧 '궁 전환율'입니다.",
    flExpFirstUlt: "선궁/상대 선궁: 한타에서 첫 궁극기를 어느 팀이 먼저 썼는가. 발생률 분모는 '어느 쪽이든 궁이 나온 한타'입니다.",
    flExpUltCount: "궁 우위/열세/동수: 그 한타에서 우리가 상대보다 궁을 많이/적게/같게 쓴 경우입니다.",
    flExpUltInvest: "궁 1·2·3개 이상 투자: 우리가 그 한타에 쓴 궁 개수별 승률. 적게 쓰고 이길수록 효율적입니다.",
    flExpDryFight: "드라이 파이트(궁을 보유하고도 쓰지 않은 한타)는 궁 게이지 데이터 부재로 미제공됩니다.",
    flExpTrend: "추세(vs 과거) = 최근 승률 − 과거 승률. ↑초록=개선, ↓빨강=악화, ±1%p 미만은 →(유지)입니다. 총평(개선/악화/유지)은 이 추세(과거 대비) 기준이며 Δ열(상대 대비)은 총평에 포함되지 않습니다. 추세 셀에 마우스를 올리면 과거→최근 원값이 표시됩니다.",
    flExpSample: "표본: 현재 기간 승률 계산에 쓰인 한타 수. 과거 표본은 행 툴팁에서 확인합니다. 최소 표본 미만 행은 흐리게 표시되고 상태 열에 '표본 부족'으로 표기됩니다.",
    flExpStability: "안정성: 현재·과거 표본이 모두 (최소 표본 × 4) 이상이면 '안정', 아니면 '변동'입니다. 변동 행의 추세는 표본이 작아 크게 출렁일 수 있으니 참고용으로만 보세요.",
    // 궁극기 콤보 분석
    flCmbTitle: "궁극기 콤보 분석",
    flCmbRoleFilter: "역할 필터",
    flCmbGroupBy: "그룹 기준",
    flCmbGroupPH: "선수+영웅", flCmbGroupH: "영웅만",
    flCmbSize: "콤보 크기", flCmbWindow: "콤보 간격(초)", flCmbTopK: "Top-k", flCmbMinSample: "최소 콤보 표본",
    flCmbGenerate: "콤보 생성",
    flCmbTopTitle: "상위 콤보", flCmbBottomTitle: "하위 콤보",
    flCmbColCombo: "콤보", flCmbColRoles: "역할", flCmbColAvgInvest: "평균 궁 투자",
    flCmbPrompt: "'콤보 생성'을 누르면 현재 사이드바 필터(기간·시점·상대·맵) 기준으로 집계합니다.",
    flCmbEmpty: "조건에 맞는 콤보가 없습니다.",
    flCmbNote: "승률은 현재 기간 기준이며, 추세는 추세 기간의 동일 콤보 승률 대비입니다. 표본 부족 콤보는 흐리게 표시되고 표본 충족 콤보보다 위로 올라가지 않습니다.",
    flExpCombo1: "궁극기 콤보: 우리(현재 시점 팀) 궁들의 '시간 연쇄'입니다 — 직전 우리 궁으로부터 콤보 간격(기본 3초) 이내에 이어 쓴 궁이 같은 콤보 체인으로 묶입니다. 두 우리 궁 사이에 상대 궁이 끼면 체인이 끊기고(뒤 궁은 콤보가 아니라 응수 — 아래 응수 분석 참조), 단독으로 쓴 궁은 콤보가 아닙니다. 승률·평균 궁 투자는 그 콤보가 나온 한타 기준이며, 두 값 모두 승패 판정 가능 한타(무승부 제외) 기준입니다.",
    flExpCombo2: "부분조합 집계: 체인에 콤보 크기보다 많은 궁이 있으면 체인 멤버에서 크기 N의 모든 부분조합을 각각 셉니다(체인이 시간 근접을 보장) — 예: 3궁 체인은 크기 2 콤보 3개로 집계되어 한 한타가 여러 콤보에 중복 포함됩니다.",
    flExpCombo3: "주의: 콤보 승률은 상관관계일 뿐 인과가 아닙니다 — 특정 맵·상대·전황에서만 나오는 콤보일 수 있으니 표본 수와 함께 해석하세요.",
    // 궁극기 시퀀스 분석
    flSeqTitle: "궁극기 시퀀스 분석",
    flSeqStep1: "1단계 — 첫 궁 선택", flSeqStep2: "2단계 — 후속 궁",
    flSeqStep3: "3단계 — 두 번째 궁", flSeqStep4: "4단계 — 궁 상호작용",
    flSeqSide: "측", flSeqSideOur: "우리", flSeqSideOpp: "상대",
    flSeqHero: "영웅", flSeqUltWord: "궁", flSeqRespWin: "응수 창(초)",
    flSeqAnalyze: "분석", flSeqAnalyze2: "상호작용 분석",
    flSeqNoData: "선택한 궁이 나온 승패 판정 가능 한타가 없습니다.",
    flSeqSummaryTpl: "{n}한타 · 승률 {win} · Δ(vs 상대) {d} · 추세 {trend}",
    flSeqTopCounters: "카운터 (상대 후속)", flSeqTopFollowups: "우리 후속",
    flSeqColFollow: "후속 궁", flSeqColSeqRate: "시퀀스율", flSeqColDWin: "Δ승률", flSeqColReact: "평균 반응시간",
    flSeqNote: "승률은 항상 우리(현재 시점) 기준 한타 승률입니다. 표본 부족 행은 흐리게 표시되고 승률순으로 승격되지 않습니다.",
    flSeqPrefill: "후속에서 선택", flSeqManualOpt: "(직접 선택)",
    flSeqSecondLabel: "두 번째 궁",
    flSeqPickSecond: "두 번째 궁을 선택하고 '상호작용 분석'을 누르세요.",
    flSeqSameWarn: "첫 궁과 두 번째 궁이 같습니다 — 다른 궁을 선택하세요.",
    flSeqDiffWord: "차이",
    flSeqStep4Note: "승률은 우리(현재 시점) 기준 한타 승률이며, Δ승률은 현재 스코프 전체 한타 승률 대비 차이입니다. 승률 차이는 상관관계이며 인과관계가 아닙니다.",
    flExpSeq1: "궁극기 시퀀스: 선택한 궁이 나온 한타에서, 그 궁의 첫 사용 시각보다 '이후'(초과) 응수 창(기본 3초) 이내에 사용된 궁을 후속 궁으로 집계합니다. timestamp가 같으면(동시 사용) 후속으로 세지 않습니다 — 동시 콤보는 위 콤보 분석 영역입니다. 표본·시퀀스율·반응시간 모두 승패 판정 가능 한타(무승부 제외) 기준입니다.",
    flExpSeq2: "시퀀스율 = 그 후속이 나온 한타 수 ÷ 선택 궁이 나온 전체 한타 수. 평균 반응시간 = 선택 궁 → 후속 궁(각 한타 내 첫 사용 기준) 시간차의 평균. 2단계 Δ승률은 '선택 궁 전체 승률' 대비, 4단계 Δ승률은 '현재 스코프 전체 한타 승률' 대비 차이입니다.",
    flExpSeq3: "카운터: 선택 궁 이후 나온 상대 후속 궁 중 우리 승률이 가장 낮은 궁 — 상대가 이 궁으로 응수할 때 우리가 자주 진다는 뜻입니다. 다만 승률 차이는 상관관계일 뿐 인과가 아니므로 표본 수와 함께 해석하세요.",
    // 해당 장면 VOD 목록
    flVodMore: "더 보기", flVodReact: "응수",
    flExpVod: "행을 클릭하면 해당 한타 VOD 목록이 열립니다. 영상은 한타 시작 약 12초 전부터 재생됩니다.",
    // 궁극기 응수(카운터) 분석
    flCtrTitle: "궁극기 응수(카운터) 분석",
    flCtrDesc: "상대 궁이 열렸을 때 우리가 어떤 궁으로 응수하면 승률이 높았는지 — 상대 궁별 검증된 해법 목록입니다. 행을 클릭하면 응수 궁 전체가 펼쳐집니다.",
    flCtrOverviewTitle: "상대 주요 궁 개요",
    flCtrColEnemyUlt: "상대 궁", flCtrColWinWith: "그때 우리 승률", flCtrColNoResp: "무응수 시 승률",
    flCtrColBest: "최고 응수 궁", flCtrColBestWin: "응수 시 승률", flCtrColBestN: "응수 표본",
    flCtrColResp: "우리 응수 궁", flCtrColRespRate: "응수율", flCtrColDNo: "Δ(무응수 대비)",
    flCtrNote: "승률 차이는 상관관계이며 인과가 아닙니다. 표본이 작은 응수는 참고만 하세요.",
    flExpCtr1: "응수: 상대 궁의 첫 사용 이후(초과) 응수 창(기본 3초) 이내에 우리가 쓴 모든 후속 궁(첫 후속 포함) — 시퀀스 분석의 후속 규칙과 동일하며 같은 계산을 재사용합니다.",
    flExpCtr2: "무응수 = 그 상대 궁 이후 응수 창(기본 3초) 내에 우리 궁이 하나도 없던 한타. Δ(무응수 대비) = 그 응수가 나온 한타의 승률 − 무응수 한타의 승률로, '응수의 가치'를 직접 보여줍니다. 최고 응수 궁은 최소 표본을 충족한 응수 중 승률 1위입니다(충족 후보가 없으면 표본 부족).",
    flExpCtr3: "한 한타에 우리 응수가 여러 개면 각각의 응수에 모두 집계됩니다 — 따라서 응수율의 합이 100%를 넘을 수 있고, 무응수율과 단순 합산되지 않습니다.",
    flExpWindows: "시간 창 기준 통일: 콤보는 콤보 간격(기본 3초) 내 '아군 궁 연쇄'(시너지), 응수/시퀀스는 응수 창(기본 3초) 내 '상대(또는 선택) 궁에 대한 즉각 반응'입니다. 두 창은 별개 설정으로 각각 조정할 수 있습니다.",

    // ── 맵 분석 탭 ──
    navMapAnalysis: "맵 분석",
    maTitle: "맵 분석",
    maDesc: "어떤 맵·맵 타입에 강하고 약한지 — 맵 선택과 밴픽 판단의 근거가 되는 실측 데이터입니다.",
    maSummaryOverall: "전체 맵 승률", maSummaryBest: "최강 맵 타입", maSummaryWorst: "최약 맵 타입",
    maSummaryNone: "표본 충족 타입 없음",
    maTypeTitle: "맵 타입 요약",
    maTypeHint: "행을 클릭하면 그 타입에 속한 맵별 통계가 펼쳐집니다.",
    maMapsTitle: "맵별 상세",
    maMapsHint: "행을 클릭하면 그 맵의 매치 목록이 펼쳐집니다. 플레이율 내림차순 정렬.",
    maWeeklyTitle: "주별 추이",
    maColType: "맵 타입", maColMap: "맵", maColPlayRate: "플레이율", maColMapWin: "맵 승률",
    maColFightWin: "한타 승률", maColDelta: "Δ (vs 상대)", maColTrend: "추세 (vs 과거)",
    maColTopHeroes: "Top 영웅", maColStatus: "상태",
    maCellPlayTpl: "{p} ({n}맵)", maCellWinTpl: "{p} ({w}승)",
    maMlDate: "날짜", maMlOpp: "상대", maMlScore: "스코어", maMlResult: "결과", maMlLink: "세션 상세",
    maMlOpen: "이동 →",
    maResultWin: "승", maResultLoss: "패", maResultDraw: "무", maResultUnknown: "미기록",
    maTopHeroNone: "표본 부족",
    maWeeklyRowAll: "전체",
    maWeeklyMetricFight: "한타 승률", maWeeklyMetricMap: "맵 승률", maWeeklyMetricPicks: "픽 횟수",
    maWeekLabelTpl: "{m}월 {n}주차",
    maWeekDetailTpl: "{label} 상세 ({range} · 총 {n}맵)",
    maColPicks: "픽 수",
    maWlDrawTpl: "{w}승 {l}패 {d}무",
    maSrcSplitTpl: "로그 {n} · 수기 {m}", msNoLogNotice: "이 경기는 로그가 없습니다. 로그를 추가해 주세요.", msWatchVod: "VOD 보기",
    maPushTip: "미보정 밀기 매치는 무승부로 집계됩니다.",
    maCorrected: "보정",
    maWeeklyCellTipTpl: "{range} · {metric} {p} · {w}승 / 표본 {n}",
    maWeeklyPicksTipTpl: "{range} · 픽 {n}회",
    maWeeklyLowTipTpl: "{range} · 표본 {n}",
    maTipUsOppTpl: "우리 {a} vs 상대 {b}",
    maTipTrendTpl: "과거 {b} → 최근 {a}",
    // 지표 설명
    maExpMapWin: "맵 승률 = 매치(맵) 단위 승수 ÷ 결과가 기록된 매치 수(무승부는 분모에 포함, 결과 미기록 매치는 제외). 한타 승률 = 한타 단위 승수 ÷ 승자 판정 가능한 한타 수. 두 지표는 집계 단위가 다르므로 함께 읽어야 합니다.",
    maExpPlayRate: "플레이율 = 그 맵(타입)의 매치 수 ÷ 스코프 내 전체 매치 수. 한타 기록이 하나도 없는 매치는 데이터 특성상 집계에 포함되지 않습니다.",
    maExpDelta: "Δ(vs 상대) = 우리 한타 승률 − 상대 한타 승률(같은 한타들의 반대 시점). 추세(vs 과거) = 최근 기간 한타 승률 − 과거 기간 한타 승률(사이드바의 추세 기간 기준).",
    maExpTopHeroes: "Top 영웅은 근사치입니다 — 완전한 출전 영웅 데이터가 없어 \"그 맵에서 우리가 궁을 쓴 영웅\"이 포함된 한타의 승률로 계산합니다(영웅별 최소 {n}한타, 승률 내림차순). 궁을 쓰지 않은 출전은 잡히지 않으므로 참고용으로만 보세요.",
    maExpWeek: "주별 추이의 '주'는 월요일 시작(월~일)이며 최근 주가 오른쪽입니다. 주 라벨 '6월 4주차'는 그 주 월요일 기준 — 달은 월요일이 속한 달, 주차는 그 달의 몇 번째 월요일인지입니다(예: 6/23 월요일 주 = 6월 4주차). 주 헤더를 클릭하면 그 주에 픽한 맵별 상세가 열립니다. 승률 모드에서 그 주 표본이 없는 셀은 회색 \"—\", 픽 횟수 모드는 매치 수를 색 없이 표시합니다.",
    maExpPushFix: "밀기맵 특례: 밀기맵 로그에는 스코어가 없어 자동 판정이 무승부(0:0)로 저장됩니다. 스크림 세션 화면에서 수기 보정(승패 보정)된 매치는 보정된 승패로 집계되고, 미보정 매치만 무승부로 남습니다. 보정은 원본 기록과 분리 저장되어 언제든 되돌릴 수 있습니다.",
    maExpStatus: "표본 하한 없음 — 1경기 이상 플레이한 맵·타입은 모두 집계에 포함됩니다. 맵 승률 셀의 방향색(초록/빨강)은 50% 기준이며, 표본이 작은 행은 괄호의 표본 수와 함께 신중히 해석하세요. 상대팀 필터는 '상대 시점'에서만 표시됩니다(우리 시점 전환 시 자동 해제).",
    maExpCausal: "승률 차이는 상관관계일 뿐 인과가 아닙니다 — 상대 수준·조합·패치 등 맥락과 함께 해석하세요.",
    // 승패 보정 (밀기맵) — 스크림 생성 모달 전용
    woLabel: "승패 보정",
    woNone: "미보정",
    woWinSuffix: "승",
    woHint: "밀기맵은 로그에 스코어가 없어 자동 판정이 무승부로 저장됩니다. 실제 승리 팀을 선택하면 맵 분석·통계에 반영됩니다(원본 기록은 유지).",
    // 사후 승패 보정 배지·인라인 편집(매치 상세·세션 매치 목록)
    woBadgeDraw: "무승부 · 수기 판정",
    woBadgeOverridden: "수기 보정됨",
    woPick: "판정",
    woSaving: "저장 중…",
    woSaveFail: "보정 저장 실패"
  },
  en: {
    back: "Back", loading: "Loading data...", noData: "No data available.", add: "Add",
    dashboard: "Dashboard", sessions: "Sessions", overall: "Overall Stats", teamManage: "Team Manage (WIP)",
    navGroupStats: "Stats", navGroupAnalysis: "Analysis", navBanpick: "Ban/Pick",
    ssCalendar: "Calendar", ssList: "List",
    title: "Scrim Data Center", desc: "Upload Overwatch scrim logs to analyze team performance.", desc2: "Data is safely stored on the server.",
    createScrim: "Create Scrim", viewHistory: "View History", uploading: "Uploading...",
    modalTitle: "Create Scrim Record", step1Title: "Basic Information", step1Desc: "Please enter the scrim date and time.",
    scrimName: "Scrim Name", scrimNamePlace: "ex: 2024-05-20 vs Opponent Scrim", videoUrl: "Video URL",
    date: "Date", time: "Time", next: "Next", prev: "Prev", save: "Save", success: "Scrim saved successfully!",
    backToList: "Back to List", totalDuration: "Total Duration", roundScore: "Round Score",
    finalBlows: "Final Blows", fightWins: "Fight Wins", ultEconomy: "Ult Economy", lowerBetter: "Lower is better",
    lead: "Lead", draw: "Draw", win: "Win", tabStats: "Stats", tabKillLog: "Kill Log", tabChart: "Charts",
    tabEvent: "Events", tabPlayer: "Player Stats", totalCumulative: "Total (Cumulative)", round: "Round",
    fightSurvivors: "Survivors per Fight", survivors: "Alive", duration: "Dur", avgSurvivors: "Avg Survivors",
    firstBloodAnalysis: "First Blood Analysis", standard: "Perspective", situation: "Situation", fightCount: "Fights",
    winRate: "Win Rate", fbSecured: "First Kill Secured", fbSuffered: "First Death Suffered", ultsPerFight: "Ults per Fight",
    fbByRole: "Final Blows by Role", cumulativeDmg: "Cumulative Dmg by Round", dmgEfficiency: "Damage Efficiency",
    heroDmgDealt: "Hero Damage Dealt", battery: "Trash Damage", carry: "Carry", role: "Role",
    player: "Player", team: "Team", playTime: "Time", elims: "Elims", deaths: "Deaths", assists: "Assists",
    heroDmg: "Hero Dmg", barrierDmg: "Barrier Dmg", healRcvd: "Heal Rcvd", dhRatio: "D/H Ratio", healing: "Healing",
    dmgTaken: "Dmg Taken", ults: "Ults", fight: "Fight", noEvents: "No events.", noUlts: "No ultimates recorded.",
    events: "Events", ultimatesUsed: "Ultimates Used", pickRate: "Pick Rate", soloKills: "Solo Kills", ultUsage: "Ultimates Used",
    per10: "/ 10m", tank: "Tank", dps: "DPS", support: "Support",
    filterPlaceholder: "Filter (ex: Lijiang, Lucio, Win...)", filterTip: "Use filters (Player, Map, Hero) for detailed analysis.",
    searchedGames: "Searched Games", avgWinRate: "Avg Win Rate", avgKills: "Avg Kills", avgDeaths: "Avg Deaths", avgDmg: "Avg Dmg",
    tabHighlights: "Highlights & Summary", tabHeroes: "Hero Stats", tabMaps: "Map Stats", highlights: "Highlights",
    noMoments: "No moments found matching conditions.", heroStatsTitle: "Hero Stats (Filtered)", mapStatsTitle: "Map Stats",
    hero: "Hero", gamesPlayed: "Games", kda: "KDA",
    dateFilter: "Date Range", startDate: "Start Date", endDate: "End Date", allDates: "All Time",
    ultStatsTitle: "Ultimate Value & Fight Analysis", ultCountVsWin: "Fight Win Rate by Ult Count", ultEfficiency: "Ultimate Efficiency (by Win Rate)",
    ultUses: "Uses",
    baseTeam: "Base Team", allTeams: "All Teams",
    matchStart: "Game Start Time", matchEnd: "Game End Time",
    objectiveCaptured: "Objective captured", flNoDataInPeriod: "No scrim data in the selected period (last scrim: {date})", flShowAllPeriod: "Show all time",
    matchStartTip: "Video timestamp when countdown ends (setup_complete)",
    navUltimateStats: "Ultimate Stats", navFirstKill: "First Kill Stats", navFirstDeath: "First Death Stats", navFirstFight: "First Fight", navPersonal: "Personal Stats",
    ffTitle: "First Fights", ffDesc: "Jump straight to the first engagement of each map/round. (Control/Escort/Hybrid: per round, Flashpoint/Push: one per match)",
    ffAllOpponents: "All Opponents", ffAllMaps: "All Maps", ffColDate: "Date", ffColMap: "Map", ffColRound: "Round", ffColMatchup: "Matchup", ffColTime: "Fight Time", ffColLink: "Video",
    ffWatch: "Watch", ffNoVideo: "No video", ffLoading: "Loading…", ffError: "Failed to load data.",
    // FirstKillStats
    fkTitle: "First Kill Stats", fkDesc: "Detailed breakdown of fight-opening carry potential, top victims, and abilities used.",
    allPositions: "All Roles", matchup: "Matchup:", myTeamAll: "My Team (All)", enemyTeamAll: "Enemy Team (All)",
    position: "Role", fkColFights: "Teamfights", fkColCount: "First Kills", fkColRate: "First Kill %",
    timesUnit: "", fkTopVictims: "Top Victims (Player)", fkTopHeroes: "Targeted Heroes (Hero)", fkKillSkill: "Finishing Ability (on whom?)",
    noFilteredData: "No data matches the filter.",
    // FirstDeathStats
    fdTitle: "First Death Stats", fdDesc: "Detailed analysis of player survivability and who/what ability they died to first.",
    fdColCount: "First Deaths", fdColRate: "First Death %",
    fdNemesis: "Nemesis (Player)", fdWatchHeroes: "Threat Heroes (Hero)", fdDeadlySkill: "Deadly Ability (hit by whom)",
    // PlayerProfileView
    all: "All", ppNoPlayers: "No player data available.", ppRosterTitle: "Roster", ppSearchPlaceholder: "Search player...",
    ppOverallKd: "Overall K/D", ppDmgPer10: "Damage / 10min", ppHealPer10: "Healing / 10min", ppUltPerMatch: "Ults / Match",
    ppHeroPool: "Most Played Heroes", ppNoHeroes: "No hero play records.", ppRecentForm: "Recent K/D Form",
    ppSelectPrompt: "Select a player from the list on the left.",
    // PlayerCompareView
    navCompare: "Compare Players",
    pcRosterTitle: "Select Players", pcSelectHint: "Pick 2 or more players", pcSelectedCount: " selected",
    pcSelectPrompt: "Select at least 2 players to compare.",
    pcMetricCompare: "Metric Comparison", pcScopeLabel: "Scope", pcScopeAll: "All (Overall)",
    pcRadarTitle: "Overall Stats (Relative)", pcRadarHint: "Scaled to 100% of the best value among selected players",
    pcHeroCompare: "Hero Comparison", pcSelectHeroLabel: "Select hero:", pcNoHeroRecord: "No record",
    pcHeroPlayTime: "Play Time", pcBest: "Best", pcMetricKd: "K/D", pcMetricWinRate: "Win Rate",
    pcHeroUltEff: "Kills per Ult", pcHeroUltWin: "Ult Fight Win%", pcHeroUltGames: "tf", pcHeroUltUses: "ult", pcHeroUltCharge: "Avg Ult Charge", pcSecUnit: "s", pcHeroImpact: "Impact (Elim/10)",
    pcMetricDmg: "Dmg / 10min", pcMetricHeal: "Heal / 10min", pcMetricUlt: "Ults / Match", pcMin: "min",
    pcMetricMitig: "Mitigated / 10min", pcMetricFb: "Final Blows / 10min", pcMetricSecondaryMixed: "Secondary / 10min",
    pcTagHeal: "Heal", pcTagMitig: "Mitig.", pcTagFb: "FB",
    // MatchStats
    msNoFights: "No recorded fights (kills).", msUltEffWin: "Efficient Win (fewer ults)", msUltSaveLoss: "Lost While Saving Ults", msUltOverInvest: "Over-Investment (2+ excess)",
    msLostFightTitle: "Resistance in Lost Fights (Kill Exchange)", msAvgKillRateOnLoss: "Avg Enemy Kill Rate on Loss",
    msAvgWord: "avg ", msKillsUnit: " kills", msLossUnit: " losses", msResistKills: "Resist Kills",
    msMomentumTitle: "Teamfight Momentum (Streaks & Turnovers)", msWinRateAfterWin: "Win Rate After Winning", msWinToWin: "(Win ➔ Win)", msSnowball: "Snowballing ability",
    msWinRateAfterLoss: "Win Rate After Losing", msLossToWin: "(Loss ➔ Win)", msComeback: "Comeback ability",
    msFirstDeathAnalysis: "First Kills & Individual Death Analysis", msFirstKillCountTeam: "First Kills (Team)", msFirstDeathRank: "First Death Ranking",
    msPlayerHero: "Player (Hero)", msFirstBloodDeaths: "First Deaths", msDeathCause: "Main Death Causes (hit by whose ability)", msNoDataShort: "No data",
    msUltSummary: "Ultimate Summary", msTotalUlts: "Total Ultimates Used", msFirstUltInFight: "Used Ult First in Fight", msUltTiming: "Ultimate Timing",
    msPhaseEarly: "Early (Initiation)", msPhaseMid: "Midfight", msPhaseLate: "Late", msUltExchange: "Ult Exchange & Over-Investment",
    msAvgConsumed: "Avg Consumed", msWonFight: "Won fights:", msLostFightLabel: "Lost fights:", msCountUnit: "",
    msNoVideo: "No video record for this match", msTabStats: "Stats Table", msTabKill: "Kill Log", msTabChart: "Analysis Charts", msTabTimeline: "Timeline", msTabCompare: "Player Comparison",
    // Ult Timeline subtab
    msTabUltTl: "Ult Timeline",
    msUltTlNote: "Ultimate flow per fight. +X.Xs next to each ult is relative to the fight's first ultimate; video links start about 12 seconds before the fight begins.",
    msUltTlFight: "Fight", msUltTlWinner: "Winner", msUltTlDraw: "Undecided", msUltTlNoUlt: "No ultimates used",
    // Match detail summary card / round tabs / event labels (i18n)
    msBackToOverview: "Back to Overview", msTotalTime: "Total Match Time", msScoreLabel: "Score", msWinnerLabel: "Winner",
    msFinalBlows: "Final Blows", msFightWins: "Fight Wins", msUltEconomy: "Ult Economy",
    msOverview: "Overview", msRoundLabel: "Round {n}",
    msMultiKill: "Multi Kill", msTeamKill: "Team Kill", msKillsUnit: " Kills",
    // Session list / scrim detail (i18n)
    matchCount: "{n} matches", sdMatchList: "Match List", sdResult: "Result", sdAnalyze: "Analyze", sdUnknown: "Unknown",
    sdEdit: "Edit", sdEditSession: "Edit Session Info", sdSave: "Save", sdCancel: "Cancel",
    sdOppRename: "Rename Opponent", sdOppRenameHint: "The base team ({team}) cannot be renamed. For fixing typos made at registration.",
    sdMatchEdit: "Edit", sdOrder: "Order", sdVodOffset: "VOD offset (MM:SS)",
    sdAddLog: "Add Log", sdReplaceLog: "Replace Log",
    sdReplaceWarn: "This match's existing log data (rounds/events/player stats) will be deleted and re-parsed from the new log. Recovery is only possible via a previous git commit or daily backup. Continue?",
    sdDiffTitle: "Manual values differ from parsed results:",
    sdDiffAdopt: "[OK] = adopt parsed values · [Cancel] = keep manual values (winner moves to override)",
    sdManualBadge: "Manual", sdEditFail: "Edit failed: ", sdUploadDone: "Log applied.",
    // Common (buttons / delete dialogs)
    delete: "Delete", reset: "Reset", cancelSelection: "Cancel", selectAll: "Select All", deselectAll: "Deselect All",
    selectedCount: "selected", deleting: "Deleting...", deleteSelected: "Delete Selected", deleteConfirmPre: "Delete ",
    sdIrreversible: "This action cannot be undone.", sdDeleteDone: "Deleted", sdWarnings: "Warnings:",
    sdPartialFail: "Partial delete failure: ", sdDeleteFail: "Delete failed: ", sdDeleteMatchPost: " selected matches?",
    ssDeleteSessionMid: " selected sessions?\nThis will also delete a total of ", ssDeleteSessionPost: " included matches.",
    ssRebuildConfirm: "Rebuild DB?",
    // ScrimModal
    smCloseConfirm: "Your input will be lost. Close anyway?", smEnterName: "Please enter a scrim name.", smMinOneMatch: "Please record at least one match.",
    smMatchPre: "Match ", smMatchPost: ": ", smPauseSelectedWarn: "You selected 'Has Pause'. Add a pause range or select 'No'.",
    smPauseTimeWarn: "Enter both pause start/end times. (ex: 10:00)", smYoutubeLink: "YouTube Video Link", smOptional: "(Optional)",
    smTeam1Label: "Team 1 Name (Left)", smTeam2Label: "Team 2 Name (Right)", smStartPlaceholder: "ex: 03:30 (fight start)",
    smSourceLabel: "Match Type", smSourceLog: "Log match", smSourceManual: "Manual match (no log)",
    smManualHint: "Records map/result/score without a log. Excluded from log-based metrics (fights, ults, player stats); you can attach a log later.",
    smWinnerLabel: "Winner", smScoreLabel: "Score (Team 1 : Team 2)", smVodStart: "VOD start (MM:SS)", smVodEnd: "VOD end (MM:SS, optional)",
    // UltimateStats
    ultFivePlus: "5+", ultTotal: "Total", ultValue: "Value", ultLowSampleNote: "Low sample (under 5) · reference",
    // OverallStats
    osAnalysis: "Analysis", osTabFights: "Teamfight Stats", osWinBadge: "Win", osLossBadge: "Loss", osAllAvg: "All Avg",
    osTabSummary: "Summary", osMapWinCard: "Map win rate", osSummaryBasisTpl: "Based on {team}", osTrendCard: "Trend (vs previous period)",
    osTrendHint: "Set a start date to see the trend vs. the previous period", osTrendPrevTpl: "prev {p} · {n} fights", osFightSampleTpl: "{w}/{n} fights",
    osSummaryEntryHeroes: "View hero stats", osSummaryEntryMaps: "View map stats", osSummaryEntryHint: "Details →",
    osTopHeroTpl: "Most played: {hero}", osTopMapTpl: "Most played map: {map}", osSecondaryMetrics: "Player average metrics (by period · filter)",
    osShowMore: "Show more", osShowingCountTpl: "{shown} / {total}", osSummaryNoData: "No match data for our team.",
    osNoMatchDataPre: "No match data for ", osNoMatchDataPost: "", osNoFightData: "No teamfight data to analyze",
    osLostFightsSuffix: " lost fights", osResistDescPre: "Eliminated ", osResistDescMid: " enemies in lost fights → ", osResistDescPost: "% kill rate. Higher means better trades even in losses.",
    osFirstDeathTop3: "First Death TOP 3", osFirstDeathLabel: "First Death", osLostFightCarryTop3: "Lost Fight Carry TOP 3", osNoMin10: "No players with 10+ participations",
    osKillsPerFight: "kills/fight", osTotalWord: "", osKillUnit: " kills", osMin10Note: "* Based on 10+ lost fight participations",
    osMomentumNotePre: "* No match-boundary crossing · Draw fights excluded · Matches: ", osMomentumNotePost: " games", osEliminated: "eliminated", osKill: "kill",
    // Tab restructure: Ult Analysis / First Kill·Death
    navUltAnalysis: "Ult Analysis",
    navKillDeath: "First Kill·Death",
    kdToggleFk: "First Kill", kdToggleFd: "First Death",
    flUaTitle: "Ultimate Analysis",
    flUaDesc: "Win rates by ultimate situation plus combos, sequences and responses. From the base team's view.",
    flUaTabSituation: "Situations", flUaTabComboSeq: "Combos & Sequences",
    // [Exchange Patterns]
    flPatTab: "Exchange Patterns",
    flPatUs: "A", flPatOpp: "E", flPatNone: "no ults",
    flPatChipUs: "ALLY", flPatChipOpp: "ENEMY",
    flPatChipUsTip: "Our ultimate", flPatChipOppTip: "Enemy ultimate",
    flPatSumFights: "Fights (decidable)", flPatSumKinds: "Distinct patterns", flPatSumTop: "Most common",
    flPatColPattern: "Pattern",
    flPatSecUs: "We ult first", flPatSecOpp: "They ult first",
    flPatSecSub: "subtotal: {n} fights · {w} WR",
    flPatHotTitle: "Notable",
    flPatBarToggle: "WR bars",
    flPatTableNote: "Pattern = the ORDER of the ult exchange. Click a row to see actual hero compositions and VODs.",
    flPatOppOther: "other {n}",
    flPatInsFirst: "First ult ours: {a} WR ({an} fights) vs theirs first: {b} ({bn} fights)",
    flPatInsLast: "Last ult ours: {a} WR ({an} fights) vs theirs: {b} ({bn} fights)",
    flExpPat1: "Pattern notation (per-ult): all ultimates in a fight are listed chronologically, one chip per ult — blue badge = our ult, red badge = enemy ult (same team colors as the timeline viewer); fights with no ults are 'no ults'. Patterns longer than 6 chips are truncated to the first 6 + '…' and bucketed together. This table is about the ORDER of the exchange — for time-clustered combos see the [Combos & Sequences] subtab.",
    flExpPat2: "Ordering rule: when both teams ult at exactly the same timestamp, ours is ordered first (same rule as the combo/initiation analyses). Occurrence, win rate and samples all count only fights with a decidable winner. The table splits into [We ult first] / [They ult first] sections by the first chip; each section header's subtotal WR is the weighted average over all fights in that section.",
    flExpPat3: "Δ (vs opp) = this pattern's our win rate − the opponent's win rate in the MIRROR pattern (ally↔enemy swapped), which equals 1 − our win rate there. E.g. [ALLY]→[ENEMY] compares against the opponent's win rate in [ENEMY]→[ALLY]. Self-mirror (symmetric) patterns, including 'no ults', show '—'.",
    flExpPat4: "Caution: pattern win rates are correlation, not causation — the effect of ult COUNT (investment) is mixed with the effect of ORDER, so always read them together with the sample size.",
    flPatOnlyUlt: "Ult fights only",
    flExpPat5: "'Ult fights only' (default on) excludes no-ult fights from the sample; occurrence rates, summary numbers and trends use that population. Turning it off includes the 'no ults' pattern in the table and denominators (the insight lines are unaffected — they already cover ult fights only).",
    flPatCompTitle: "Top compositions",
    flPatCompNotice: "Small samples — treat as directional only.",
    flPatCompCol: "Composition",
    // [Initiation]
    flInitTab: "Initiation",
    flInitSumRate: "Our first-ult rate ({m}/{n} fights)",
    flInitSumUsWin: "WR when we ult first ({n} fights)",
    flInitSumThemWin: "WR when they ult first ({n} fights)",
    flInitOurTitle: "Our initiating ultimates",
    flInitOurDesc: "Fights we opened, grouped by the first ult's hero — which ult wins fights when it opens. Click a row for the per-player breakdown + VODs.",
    flInitOppTitle: "Opponent initiating ultimates",
    flInitOppDesc: "Fights the opponent opened. Win rate is OURS — lower means that initiation hurts us. Click a row for our top 3 responses within 3s + VODs.",
    flInitColUlt: "Initiating ult", flInitColShare: "Initiation share", flInitColDelta: "Δ (vs all inits)",
    flInitColPlayer: "Player", flInitPlayersTitle: "Who opened (by player)",
    flInitRespTitle: "Our top 3 responses within 3s to this initiation",
    flInitRespNone: "No fights had a response from us within 3s.",
    flExpInit1: "Initiation = the chronologically first ultimate of a fight. The call reuses the exchange-pattern first-move definition as-is — when both teams ult at exactly the same timestamp, ours is ordered first (counted as our initiation). The population is decidable-winner fights WITH ults; no-ult fights are excluded everywhere (identical calculation and numbers as the exchange-pattern insight line).",
    flExpInit2: "Initiation share = within that table (our inits / opponent inits), the share of fights this hero opened — each table sums to 100%. Δ = this initiating ult's win rate − the table-wide win rate (all our inits, or all opponent inits, ours-basis).",
    flExpInit3: "The opponent table's win rate is also always OURS (lower = that initiation threatens us). The response mini table shown when expanding a row uses the same calculation as the Response (Counter) analysis (our ults within 3s AFTER the first use, simultaneous excluded, one fastest response per fight), only narrowing the population to fights where that ult was the INITIATION.",
    flExpInit4: "Caution: initiation win rates are correlation, not causation — opening with a certain ult may just signal an already-favorable comp or fight state, so read them together with sample sizes.",
    flExpPatComp: "Composition (the mini table inside an expanded pattern row): groups are keyed by OUR ult heroes only, in per-ult order — enemy ults are NOT part of the key, so samples stay intact (switching perspective turns this into the opponent's compositions). The display shows the full sequence: our slots as hero names (blue), enemy slots as the actual enemy-ult frequencies across that group's fights (red, top 2 + 'other N'), e.g. 'Kiriko → E(Ana 2/Ramattra 1) → Sigma'. Patterns with no our-ults have no composition table. Clicking a composition row narrows the VOD list to that composition's fights, and each VOD item then shows the fight's complete ult sequence (side + hero) on one line.",
    // FightLabStats (Fight Lab Beta)
    navFightLab: "Fight Lab",
    flTitle: "Fight Lab",
    flDesc: "Compares per-fight win rates by situation across periods. From the base team's view.",
    flTabFights: "Engagements", flTabUlts: "Ultimates", flTabUltSeq: "Ult Combos & Sequences",
    flPresetAll: "All Time", flPreset1w: "Last 1 Week", flPreset2w: "Last 2 Weeks", flPreset1m: "Last 1 Month", flPresetCustom: "Custom Range",
    flPresetAllBefore: "All Earlier", flPresetPrevSame: "Previous Same Length",
    flMinSample: "Min Sample",
    flSideDate: "Date filter", flSideTrend: "Trend window", flSideView: "Perspective", flSideOpp: "Opponent", flSideMap: "Map", flSideMin: "Min sample", flSideFilter: "Filter",
    flApply: "Apply",
    flScopePeriod: "Period", flScopeTrend: "Trend", flScopeView: "View", flScopeOpp: "Opp", flScopeMap: "Map", flScopeNone: "none",
    flOverlapWarn: "The recent and past periods overlap. Samples are double-counted — interpret with care.",
    flColSituation: "Situation", flColOccur: "Rate", flColDOcc: "Δ rate (vs opp)",
    flColWin: "Win rate", flColDWin: "Δ win (vs opp)", flColSampleOne: "Sample",
    flColTrend: "Trend (vs past)", flColStability: "Stability", flColStatus: "Status",
    flStabStable: "stable", flStabVolatile: "volatile", flStatusOk: "available",
    flUnitPp: " pp", flTipUs: "us", flTipOpp: "opp",
    flLowSample: "Low sample",
    flRecentShort: "Recent", flPastShort: "Past",
    flCmpPastAll: "All past", flCmpPrevPrefix: "previous ",
    flVerdictImproved: "Improved", flVerdictWorse: "Worse", flVerdictSame: "Unchanged",
    flPerspUs: "Our View", flPerspThem: "Opponent View",
    flPerspNotice: "Opponent view — all win rates, occurrence rates and the summary are from the opponents' side. Opponent data covers only scrims played against us.",
    // [Players] subtab
    flTabPlayers: "Players",
    flPbGroupPlayer: "By Player", flPbGroupPlayerHero: "By Player + Hero",
    flPbColPlayer: "Player", flPbGroupFight: "Fight Metrics", flPbGroupRound: "Round Metrics",
    flPbFights: "Fights", flPbKp: "Kill Part.", flPbFk: "FK / Fight", flPbFd: "FD / Fight",
    flPbUpf: "Ults / Fight", flPbUwin: "Ult Fight WR", flPbKd: "K/D", flPbDmg10: "Dmg /10min",
    flPbHeal10: "Heal /10min", flPbUlt10: "Ults /10min",
    flPbPoolAvg: "pool", flPbPoolShortPre: "small pool (", flPbPoolShortPost: ")",
    flPbTipSample: "Sample",
    flPbRankTpl: "#{k} of {n}",
    flPbRankShortTpl: "#{k}", flPbNoPool: "small pool",
    flPbRankRoleTpl: "{role} #{k}",
    flPbRoleTank: "Tank", flPbRoleDps: "DPS", flPbRoleSup: "Sup",
    flPbTipVsPast: "vs past",
    flPbColSignals: "Signals",
    flPbSigTopSuffix: " — top 20%", flPbSigLowSuffix: " — bottom 20%",
    flPbGroupLabel: "Group player breakdown by", flPbSortLabel: "Sort by", flPbSortName: "Player",
    flPbUnitFight: " fights", flPbUnitRound: " rounds",
    flPbPDashSample: "no rank: player's own sample is below the pool minimum (20 fights / 10 rounds)",
    flPbFootnote: "Each cell is value, trend arrow (vs past window), and (parentheses = rank within the same-role pool of ours + opponents). Hover a cell for pool size and details. (—) or (small pool) is shown where a rank is not meaningful.",
    flPbPoolTpl: "{role} pool: {us} ours + {them} opponents",
    flPbPoolWarn: "※ Ranks are based only on data collected from scrims against us. Opponent numbers are limited to games played against our team; small pools can make ranks volatile.",
    flPbExpSrc: "Two data sources — [Fight Metrics] come from kill/ult events (same data as the Engagements/Ultimates tabs); [Round Metrics] come from the round summary table (same data as the Personal Stats tab). Their baselines may differ.",
    flPbExpFights: "Fights: number of our team's fights in rounds the player appeared in.",
    flPbExpKp: "Kill Participation: average of (player kills ÷ team kills) over fights where the team scored at least one kill.",
    flPbExpFkFd: "FK/FD per fight: share of fights where the player scored / suffered the fight's first kill. FD is lower-is-better — arrows, team-average colors and ranks are all inverted.",
    flPbExpAxes: "Reading a cell: one line — 'value ↑ (#5)'. Value = current period; arrow = vs the player's OWN past window (inverted metrics like FD flip colors; → = no change); parentheses = tied rank within the same-role pool (ours + opponents; inverted metrics rank by the good direction). Hover for pool size ('#5 of 13'), change vs past, samples, pool-average diff, and pool composition. The Signals top/bottom-20% rule also uses rank ÷ pool size.",
    flExpSidebar: "Set the date filter, trend window, perspective, opponent/map and min sample in the left sidebar, then press Apply. With 'All Time' selected, no comparison (Δ/arrows) is shown.",
    flPbExpSignals: "Signals: within metrics whose pool is large enough, top 20% → green (strength), bottom 20% → red (watch). Inverted metrics use the inverted direction. Max 2 per player (watch flags first); display-only — not counted in any summary.",
    flPbExpPool: "The rank pool ignores the opponent/map filters and uses all data in the recent period (so filters cannot shrink the pool into meaninglessness). Min sample: 20 fights (fight metrics) / 10 rounds (round metrics). Pools under 8 players show 'small pool'.",
    flPbExpHeal: "Heal /10min is shown for supports only. Per-10min values are based on the sum of round durations played; rounds without a duration are excluded.",
    // Leaderboard
    flLbTitle: "Leaderboard",
    flLbMetric: "Metric", flLbRole: "Role",
    flLbColRank: "Rank", flLbColTeam: "Team", flLbColValue: "Value",
    flLbUnranked: "Unranked (low sample)",
    flLbSupportOnly: "This metric is tracked for supports only — select the Support role.",
    flLbPoolWarnTpl: "Pool has only {n} players (minimum {min}) — ranks are indicative only.",
    flPbExpLb: "Leaderboard: the same pool as the cell ranks ('Sup #3') — all data in the recent period, ours + opponents, same role, min sample met — with the same tied-rank rule, laid out as a table. It ignores the opponent/map filters (existing pool rule); inverted metrics (e.g. FD/fight) rank the good direction first. Players below the min sample appear at the bottom as 'Unranked' with their value shown.",
    flRowFirstPick: "First Pick Secured", flRowFirstDeath: "First Death Suffered",
    flRowFdTank: "Tank First Death", flRowFdDamage: "DPS First Death", flRowFdSupport: "Support First Death", flRowFdOther: "Other First Death",
    flRowFkTraded: "First Pick Traded", flRowFdTraded: "First Death Traded Back",
    flRowUltUsed: "Fights Using Ults", flRowFirstUlt: "First Ult (Us)", flRowEnemyFirstUlt: "First Ult (Enemy)",
    flRowUltAdv: "Ult Advantage", flRowUltDis: "Ult Disadvantage", flRowUltEven: "Ult Even (both ≥1)",
    flRowUlt1: "1 Ult Invested", flRowUlt2: "2 Ults Invested", flRowUlt3: "3+ Ults Invested",
    flSumAvgUlt: "Avg Ults per Fight (Us)", flSumUltConv: "Ult Conversion (Win% with Ults)",
    flUnknownNotePre: "Fights with undecidable winner (equal survivors = draw): ",
    flUnknownNotePost: " — included in occurrence denominators but excluded from win-rate samples.",
    flExplainTitle: "Metric Definitions",
    flExpWinner: "Fight winner: the team with more survivors when the fight ends. Fights with equal survivors (draws) are excluded from win rates.",
    flExpTwoCols: "Each row carries two different numbers — how often the situation happens is the 'Rate' column; how well we win once in that situation is the win-rate columns.",
    flExpOccur: "Rate / Win rate: our values for the current period. Δ columns (vs opp) compare against the opponents' symmetric situation in the SAME fights — e.g. Δ rate for First Pick = our first-pick rate − opponents' first-pick rate (= our first-death rate). 'Lower is better' situations flip colors; under ±1 pp is gray. Hover a Δ cell for both raw values.",
    flExpFirstPick: "First Pick Secured: we scored the fight's first kill. Rate (higher is better) = how often; WR = whether we actually won those fights.",
    flExpFirstDeath: "First Death Suffered: the fight's first kill was against us. Rate (lower is better) = how often; WR = how often we still turned those fights around.",
    flExpFdRole: "Tank/DPS/Support First Death: breakdown of our first deaths by the victim's hero role. Rate (lower is better) = share within our first deaths; WR = fight win rate in that situation.",
    flExpFkTraded: "First Pick Traded: after our first pick, the enemy killed one of us within 5 seconds. Rate (lower is better) = how often we give the advantage back; WR = whether we still won those fights. A rising WR is good news — it does not mean trades became more frequent.",
    flExpFdTraded: "First Death Traded Back: after suffering first death, we answered with a kill within 5 seconds. Rate (higher is better) = how often we recover; WR = whether we won those fights.",
    flExpUltUsed: "Fights Using Ults: fights where we used at least one ultimate. This row's win rate is the 'Ult Conversion'.",
    flExpFirstUlt: "First Ult (Us/Enemy): which team used the fight's first ultimate. Denominator: fights where any ult was used.",
    flExpUltCount: "Ult Advantage/Disadvantage/Even: we used more / fewer / the same number of ults as the enemy in that fight.",
    flExpUltInvest: "1·2·3+ Ults Invested: win rate by the number of ults we spent in the fight. Winning with fewer ults is more efficient.",
    flExpDryFight: "Dry fights (holding an ult without using it) are not provided — ult charge data is unavailable.",
    flExpTrend: "Trend (vs past) = recent win rate − past win rate. Green ↑ = improved, red ↓ = worse, → under ±1 pp (unchanged). The summary (improved/worse/unchanged) uses this past-based trend; the Δ (vs opp) columns are not counted. Hover the trend cell for past→recent raw values.",
    flExpSample: "Sample: fights counted toward the current-period win rate. Past samples are in the row tooltip. Rows below the min sample are dimmed and marked 'Low sample' in the Status column.",
    flExpStability: "Stability: 'stable' when both current and past samples are at least (min sample × 4), otherwise 'volatile'. Trends on volatile rows can swing wildly — treat them as indicative only.",
    // Ultimate Combo Analysis
    flCmbTitle: "Ultimate Combo Analysis",
    flCmbRoleFilter: "Role filter",
    flCmbGroupBy: "Group combo by",
    flCmbGroupPH: "Player + Hero", flCmbGroupH: "Hero only",
    flCmbSize: "Combo size", flCmbWindow: "Combo window (s)", flCmbTopK: "Top-k", flCmbMinSample: "Min combo sample",
    flCmbGenerate: "Generate ultimate combos",
    flCmbTopTitle: "Top ultimate combos", flCmbBottomTitle: "Bottom ultimate combos",
    flCmbColCombo: "Combo", flCmbColRoles: "Role(s)", flCmbColAvgInvest: "Avg ults invested",
    flCmbPrompt: "Press 'Generate ultimate combos' to aggregate with the current sidebar filters (period · perspective · opponent · map).",
    flCmbEmpty: "No combos match the criteria.",
    flCmbNote: "Win rate is over the current period; trend compares against the same combo's win rate in the trend window. Low-sample combos are dimmed and are not promoted above qualifying ones.",
    flExpCombo1: "Ultimate combo: a TIME CHAIN of our (current perspective) ultimates — an ultimate joins the chain when used within the combo window (default 3s) of our previous ultimate. An opponent ultimate between two of ours BREAKS the chain (the later ult is a response, not a combo — see the Response Analysis below), and a lone ultimate is not a combo. Win rate / Avg ults invested are per fights containing the combo; both count only fights with a decidable winner (draws excluded).",
    flExpCombo2: "Subset counting: when a chain has more ults than the combo size, every subset of size N drawn from the chain members is counted separately (the chain guarantees time proximity) — e.g. a 3-ult chain yields three size-2 combos, so one fight can appear under multiple combos.",
    flExpCombo3: "Caution: combo win rates are correlation, not causation — a combo may only appear on certain maps/opponents/game states, so always read them together with the sample size.",
    // Ultimate Sequence Analysis
    flSeqTitle: "Ultimate Sequence Analysis",
    flSeqStep1: "Step 1 — First ultimate", flSeqStep2: "Step 2 — Top followups",
    flSeqStep3: "Step 3 — Second ultimate", flSeqStep4: "Step 4 — Ultimate interaction",
    flSeqSide: "Side", flSeqSideOur: "Our", flSeqSideOpp: "Opponent",
    flSeqHero: "Hero", flSeqUltWord: "ultimate", flSeqRespWin: "Response window (s)",
    flSeqAnalyze: "Analyze first ultimate", flSeqAnalyze2: "Analyze ultimate interaction",
    flSeqNoData: "No fights with a decidable winner contain the selected ultimate.",
    flSeqSummaryTpl: "{n} fights · {win} win rate · Δ (vs opp) {d} · trend {trend}",
    flSeqTopCounters: "Top counters (opponent followups)", flSeqTopFollowups: "Top same-side followups",
    flSeqColFollow: "Followup ultimate", flSeqColSeqRate: "Sequence rate", flSeqColDWin: "Δ win", flSeqColReact: "Avg response time",
    flSeqNote: "Win rate is always our (current perspective) fight win rate; low-sample rows are flagged and never promoted.",
    flSeqPrefill: "Prefill from a followup", flSeqManualOpt: "(choose manually)",
    flSeqSecondLabel: "Second ultimate",
    flSeqPickSecond: "Pick a second ultimate and press 'Analyze ultimate interaction'.",
    flSeqSameWarn: "The second ultimate is the same as the first — pick a different one.",
    flSeqDiffWord: "difference",
    flSeqStep4Note: "Win rate is our (current perspective) fight win rate; Δ win compares against our overall fight win rate in the current scope. Win-rate differences are correlational, not causal.",
    flExpSeq1: "Ultimate sequence: in fights containing the selected ultimate, any ultimate used strictly AFTER its first use and within the response window (default 3s) is counted as a followup. Equal timestamps (simultaneous use) are NOT counted as followups — simultaneous combos belong to the Combo Analysis section above. Samples, sequence rates and response times all count only fights with a decidable winner (draws excluded).",
    flExpSeq2: "Sequence rate = fights containing the followup ÷ all fights containing the selected ultimate. Avg response time = average gap from the selected ultimate to the followup (first use within each fight). Step 2 Δ win compares against the selected ultimate's overall win rate; Step 4 Δ win compares against our overall fight win rate in scope.",
    flExpSeq3: "Counters: opponent followups after our selected ultimate where our win rate is lowest — meaning we often lose when the opponent answers with that ultimate. Win-rate differences are correlational, not causal — always read them together with the sample size.",
    // Fight VOD list
    flVodMore: "Show more", flVodReact: "response",
    flExpVod: "Click a row to open the list of its sample fights with VOD links. Videos start about 12 seconds before the fight begins.",
    // Ultimate Response (Counter) Analysis
    flCtrTitle: "Ultimate Response (Counter) Analysis",
    flCtrDesc: "When an opponent ultimate opens, which of our ultimates has the best verified win rate as a response — a defensive playbook per opponent ultimate. Click a row to expand all responses.",
    flCtrOverviewTitle: "Opponent key ultimates overview",
    flCtrColEnemyUlt: "Opponent ult", flCtrColWinWith: "Our WR then", flCtrColNoResp: "WR w/o response",
    flCtrColBest: "Best response", flCtrColBestWin: "WR with response", flCtrColBestN: "Response sample",
    flCtrColResp: "Our response ult", flCtrColRespRate: "Response rate", flCtrColDNo: "Δ vs no response",
    flCtrNote: "Win-rate differences are correlational, not causal. Treat low-sample responses as indicative only.",
    flExpCtr1: "Response: every ultimate we use strictly AFTER the opponent ultimate's first use and within the response window (default 3s), including the first followup — identical to the sequence analysis followup rule, reusing the same computation.",
    flExpCtr2: "No response = fights where we used no ultimate within the response window (default 3s) after that opponent ultimate. Δ vs no response = win rate with that response − win rate without any response, directly showing the value of responding. Best response = the highest-win-rate response among those meeting the min sample (otherwise 'Low sample').",
    flExpCtr3: "If we respond with several ultimates in one fight, the fight is counted under each response — so response rates can sum past 100% and do not simply add up with the no-response rate.",
    flExpWindows: "Unified time windows: combos use the combo window (default 3s) for ALLIED ult chains (synergy); responses/sequences use the response window (default 3s) for IMMEDIATE reactions to the opponent's (or selected) ultimate. The two windows are separate settings and can be tuned independently.",

    // ── Map Analysis tab ──
    navMapAnalysis: "Maps",
    maTitle: "Map Analysis",
    maDesc: "Which maps and map types we are strong or weak on — measured evidence for map picks and vetoes.",
    maSummaryOverall: "Overall map win rate", maSummaryBest: "Best map type", maSummaryWorst: "Worst map type",
    maSummaryNone: "No type meets min sample",
    maTypeTitle: "Map type summary",
    maTypeHint: "Click a row to expand per-map stats for that type.",
    maMapsTitle: "Maps",
    maMapsHint: "Click a row to expand that map's match list. Sorted by play rate (desc).",
    maWeeklyTitle: "Weekly trend",
    maColType: "Map type", maColMap: "Map", maColPlayRate: "Play rate", maColMapWin: "Map win rate",
    maColFightWin: "Fight win rate", maColDelta: "Δ (vs opp)", maColTrend: "Trend (vs past)",
    maColTopHeroes: "Top heroes", maColStatus: "Status",
    maCellPlayTpl: "{p} ({n} maps)", maCellWinTpl: "{p} ({w} wins)",
    maMlDate: "Date", maMlOpp: "Opponent", maMlScore: "Score", maMlResult: "Result", maMlLink: "Session",
    maMlOpen: "Open →",
    maResultWin: "W", maResultLoss: "L", maResultDraw: "D", maResultUnknown: "N/A",
    maTopHeroNone: "Low sample",
    maWeeklyRowAll: "All",
    maWeeklyMetricFight: "Fight win rate", maWeeklyMetricMap: "Map win rate", maWeeklyMetricPicks: "Pick count",
    maWeekLabelTpl: "{mon} W{n}",
    maWeekDetailTpl: "{label} detail ({range} · {n} maps)",
    maColPicks: "Picks",
    maWlDrawTpl: "{w}W {l}L {d}D",
    maSrcSplitTpl: "Log {n} · Manual {m}", msNoLogNotice: "This match has no log. Please add a log.", msWatchVod: "Watch VOD",
    maPushTip: "Uncorrected Push matches are counted as draws.",
    maCorrected: "corrected",
    maWeeklyCellTipTpl: "{range} · {metric} {p} · {w} wins / sample {n}",
    maWeeklyPicksTipTpl: "{range} · {n} picks",
    maWeeklyLowTipTpl: "{range} · sample {n}",
    maTipUsOppTpl: "Us {a} vs Opp {b}",
    maTipTrendTpl: "Past {b} → Recent {a}",
    // Metric explanations
    maExpMapWin: "Map win rate = match-level wins ÷ matches with a recorded result (draws stay in the denominator; matches without a recorded result are excluded). Fight win rate = teamfight wins ÷ fights with a decidable winner. The two metrics use different units — read them together.",
    maExpPlayRate: "Play rate = matches on that map (type) ÷ all matches in scope. Matches with no recorded fights cannot appear in this data and are not counted.",
    maExpDelta: "Δ (vs opp) = our fight win rate − the opponent's fight win rate (the same fights, mirrored). Trend (vs past) = recent-period fight win rate − past-period fight win rate (per the sidebar trend window).",
    maExpTopHeroes: "Top heroes are an APPROXIMATION — full playtime data is unavailable, so we use the fight win rate of fights where we used that hero's ultimate on that map (min {n} fights per hero, sorted by win rate). Appearances without an ultimate are invisible to this metric; treat as indicative only.",
    maExpWeek: "Weeks start on Monday (Mon–Sun) with the most recent week on the right. The week label (e.g. \"Jun W4\") follows that week's Monday — the month is the Monday's month and N is which Monday of that month it is (e.g. the week of Mon Jun 23 = Jun W4). Click a week header to open that week's per-map detail. In win-rate modes, cells with no sample that week show a gray \"—\"; pick-count mode shows match counts without coloring.",
    maExpPushFix: "Push-map caveat: Push logs carry no score, so the automatic result is stored as a draw (0:0). Matches manually corrected in the Sessions screen count with their corrected result; only uncorrected matches remain draws. Corrections are stored separately from the original record and can be reverted anytime.",
    maExpStatus: "No minimum sample — every map/type with at least one match is included. Map win rate cells are colored green/red around the 50% line; read small-sample rows carefully alongside the sample counts in parentheses. The opponent filter is shown only in the opponent perspective (auto-reset when switching back to our perspective).",
    maExpCausal: "Win-rate differences are correlational, not causal — interpret alongside opponent strength, compositions, and patches.",
    // Result correction (Push maps) — scrim creation modal only
    woLabel: "Result correction",
    woNone: "Not corrected",
    woWinSuffix: "win",
    woHint: "Push maps carry no score in the log, so the automatic result is stored as a draw. Pick the actual winner to reflect it in Map Analysis and stats (the original record is preserved).",
    // Post-hoc result correction badge & inline edit (match detail · session match list)
    woBadgeDraw: "Draw · set winner",
    woBadgeOverridden: "Overridden",
    woPick: "Set",
    woSaving: "Saving…",
    woSaveFail: "Failed to save override"
  },
  zh: {
    back: "返回", loading: "数据加载中...", noData: "暂无数据。", add: "添加",
    dashboard: "仪表盘", sessions: "训练赛场次", overall: "总体统计", teamManage: "队伍管理（开发中）",
    navGroupStats: "统计", navGroupAnalysis: "分析", navBanpick: "禁选",
    ssCalendar: "日历", ssList: "列表",
    title: "训练赛数据中心", desc: "上传守望先锋训练赛日志，分析队伍表现。", desc2: "数据将安全存储在服务器。",
    createScrim: "创建训练赛", viewHistory: "查看记录", uploading: "上传中...",
    modalTitle: "创建训练赛记录", step1Title: "基本信息", step1Desc: "请输入训练赛日期与时间。",
    scrimName: "训练赛名称", scrimNamePlace: "例：2024-05-20 vs 对手训练赛", videoUrl: "视频链接",
    date: "日期", time: "时间", next: "下一步：录入对局", prev: "上一步", save: "保存并完成", success: "训练赛保存成功！",
    backToList: "返回列表", totalDuration: "总比赛时长", roundScore: "回合比分",
    finalBlows: "决定性击杀", fightWins: "团战胜利", ultEconomy: "大招效率", lowerBetter: "越低越好",
    lead: "领先", draw: "平局", win: "胜利", tabStats: "数据", tabKillLog: "击杀日志", tabChart: "图表",
    tabEvent: "事件", tabPlayer: "选手数据", totalCumulative: "全部（累计）", round: "回合",
    fightSurvivors: "每场团战存活人数", survivors: "人存活", duration: "持续", avgSurvivors: "平均存活",
    firstBloodAnalysis: "首杀分析胜率", standard: "视角", situation: "情形", fightCount: "团战次数",
    winRate: "胜率", fbSecured: "取得首杀时", fbSuffered: "被首杀时", ultsPerFight: "每团大招使用数",
    fbByRole: "各定位决定性击杀", cumulativeDmg: "各回合累计英雄伤害", dmgEfficiency: "输出效率分析",
    heroDmgDealt: "造成英雄伤害", battery: "只打伤害的电池（低效）", carry: "Carry（伤害+击杀）", role: "定位",
    player: "选手", team: "队伍", playTime: "时长", elims: "击杀", deaths: "死亡", assists: "助攻",
    heroDmg: "英雄伤害", barrierDmg: "屏障伤害", healRcvd: "承受治疗", dhRatio: "伤/疗比", healing: "治疗量",
    dmgTaken: "承受伤害", ults: "大招", fight: "团战", noEvents: "暂无事件。", noUlts: "无大招使用记录。",
    events: "事件", ultimatesUsed: "已用大招", pickRate: "使用率", soloKills: "单杀", ultUsage: "大招使用",
    per10: "/ 10分钟", tank: "重装", dps: "输出", support: "支援",
    filterPlaceholder: "输入筛选条件（例：漓江塔、卢西奥、胜利…）", filterTip: "输入选手、地图、英雄等进行详细分析。",
    searchedGames: "检索到的对局", avgWinRate: "平均胜率", avgKills: "平均击杀", avgDeaths: "平均死亡", avgDmg: "平均伤害量",
    tabHighlights: "高光时刻与摘要", tabHeroes: "英雄统计", tabMaps: "地图统计", highlights: "高光时刻",
    noMoments: "没有符合条件的场面。", heroStatsTitle: "英雄战绩（按筛选）", mapStatsTitle: "地图统计",
    hero: "英雄", gamesPlayed: "对局数", kda: "KDA",
    dateFilter: "时间段", startDate: "开始日期", endDate: "结束日期", allDates: "全部时间",
    ultStatsTitle: "大招价值与团战分析", ultCountVsWin: "按大招投入数的团战胜率", ultEfficiency: "各英雄大招价值（按团战胜率）",
    ultUses: "使用次数",
    baseTeam: "基准队伍", allTeams: "全部队伍",
    matchStart: "对局开始时间", matchEnd: "对局结束时间",
    objectiveCaptured: "占领点占领", flNoDataInPeriod: "所选时间段内没有训练赛数据（最后一次：{date}）", flShowAllPeriod: "查看全部时间",
    matchStartTip: "视频中战斗开始（倒计时结束）的时间点",
    navUltimateStats: "大招统计", navFirstKill: "首杀统计", navFirstDeath: "首死统计", navFirstFight: "首次团战", navPersonal: "个人统计",
    ffTitle: "首次团战合集", ffDesc: "汇总各地图/回合的首次交战时间，可直接跳转视频。（占领要点/运载/混合按回合，闪点/推进每场1个）",
    ffAllOpponents: "全部对手", ffAllMaps: "全部地图", ffColDate: "日期", ffColMap: "地图", ffColRound: "回合", ffColMatchup: "对阵", ffColTime: "交战时间", ffColLink: "视频",
    ffWatch: "观看", ffNoVideo: "无视频", ffLoading: "加载中…", ffError: "数据加载失败。",
    // FirstKillStats
    fkTitle: "首杀分析", fkDesc: "详细分析开团Carry能力、主要目标及所用技能。",
    allPositions: "全部位置", matchup: "指定对阵：", myTeamAll: "我方（全部）", enemyTeamAll: "敌方（全部）",
    position: "位置", fkColFights: "团战次数", fkColCount: "首杀次数", fkColRate: "首杀率 (%)",
    timesUnit: "次", fkTopVictims: "主要目标 (Player)", fkTopHeroes: "重点针对英雄 (Hero)", fkKillSkill: "决定性击杀技能（命中了谁？）",
    noFilteredData: "没有符合条件的数据。",
    // FirstDeathStats
    fdTitle: "首死分析", fdDesc: "详细分析选手的生存能力，以及主要死于谁/什么技能。",
    fdColCount: "首死次数", fdColRate: "首死率 (%)",
    fdNemesis: "克星 (Player)", fdWatchHeroes: "需警惕英雄 (Hero)", fdDeadlySkill: "致命技能（被谁的技能命中）",
    // PlayerProfileView
    all: "全部", ppNoPlayers: "暂无选手统计数据。", ppRosterTitle: "选手名单", ppSearchPlaceholder: "搜索选手...",
    ppOverallKd: "综合 K/D", ppDmgPer10: "每10分钟伤害量", ppHealPer10: "每10分钟治疗量", ppUltPerMatch: "场均大招",
    ppHeroPool: "常用英雄池", ppNoHeroes: "暂无英雄使用记录。", ppRecentForm: "近期 K/D 状态 (Form)",
    ppSelectPrompt: "请从左侧列表选择一名选手。",
    // PlayerCompareView
    navCompare: "选手对比",
    pcRosterTitle: "选择选手", pcSelectHint: "请选择2名以上", pcSelectedCount: "人已选",
    pcSelectPrompt: "请选择至少2名选手进行对比。",
    pcMetricCompare: "指标对比", pcScopeLabel: "范围", pcScopeAll: "全部（综合）",
    pcRadarTitle: "综合能力（相对对比）", pcRadarHint: "按所选选手中最高值折算为100%",
    pcHeroCompare: "英雄对比", pcSelectHeroLabel: "选择英雄：", pcNoHeroRecord: "无记录",
    pcHeroPlayTime: "游戏时长", pcBest: "最佳", pcMetricKd: "K/D", pcMetricWinRate: "胜率",
    pcHeroUltEff: "每大击杀", pcHeroUltWin: "用大团战胜率", pcHeroUltGames: "团战", pcHeroUltUses: "大招", pcHeroUltCharge: "平均充能时间", pcSecUnit: "秒", pcHeroImpact: "影响力（击杀/10分钟）",
    pcMetricDmg: "每10分钟伤害", pcMetricHeal: "每10分钟治疗", pcMetricUlt: "场均大招", pcMin: "分钟",
    pcMetricMitig: "每10分钟减伤", pcMetricFb: "每10分钟决定性击杀", pcMetricSecondaryMixed: "每10分钟辅助指标",
    pcTagHeal: "治疗", pcTagMitig: "减伤", pcTagFb: "决定击杀",
    // MatchStats
    msNoFights: "没有记录的团战（击杀）。", msUltEffWin: "高效胜利（用得更少）", msUltSaveLoss: "省大招而落败", msUltOverInvest: "过度投入（超出2个以上）",
    msLostFightTitle: "败方团战抵抗力 (Kill Exchange in Lost Fights)", msAvgKillRateOnLoss: "落败时平均击杀敌方比例",
    msAvgWord: "平均 ", msKillsUnit: "人击杀", msLossUnit: "次失利", msResistKills: "抵抗击杀数",
    msMomentumTitle: "团战势头（连胜与翻盘）", msWinRateAfterWin: "占住位置后胜率", msWinToWin: "（胜 ➔ 胜）", msSnowball: "巩固优势的能力",
    msWinRateAfterLoss: "未占住位置后胜率", msLossToWin: "（负 ➔ 胜）", msComeback: "扭转局面的能力",
    msFirstDeathAnalysis: "首杀获取与个人死亡分析 (First Deaths)", msFirstKillCountTeam: "首杀获取次数（队伍）", msFirstDeathRank: "首死排名",
    msPlayerHero: "选手 (Hero)", msFirstBloodDeaths: "首死次数", msDeathCause: "主要死亡原因（被谁的技能命中）", msNoDataShort: "无数据",
    msUltSummary: "大招总览 (Ultimates)", msTotalUlts: "大招总使用次数 (Total Ultimates Used)", msFirstUltInFight: "团战先手大招 (Used Ult First in Fight)", msUltTiming: "大招使用时机 (Timing)",
    msPhaseEarly: "前期（开团）", msPhaseMid: "中期", msPhaseLate: "后期", msUltExchange: "大招交换比与过度投入 (Ult Exchange)",
    msAvgConsumed: "平均消耗", msWonFight: "获胜团战：", msLostFightLabel: "落败团战：", msCountUnit: "个",
    msNoVideo: "该对局没有视频记录", msTabStats: "数据表", msTabKill: "击杀日志", msTabChart: "详细分析图表", msTabTimeline: "时间线", msTabCompare: "选手对比",
    // 大招时间线子标签
    msTabUltTl: "大招时间线",
    msUltTlNote: "按团战展示大招走势。大招旁的 +X.Xs 为相对该团战首个大招的时间，视频链接从团战开始前约12秒起播。",
    msUltTlFight: "团战", msUltTlWinner: "胜方", msUltTlDraw: "无法判定", msUltTlNoUlt: "未使用大招",
    // 对局详情摘要卡·回合标签·事件标签 (i18n)
    msBackToOverview: "返回总览", msTotalTime: "总比赛时长", msScoreLabel: "比分", msWinnerLabel: "胜方",
    msFinalBlows: "决定性击杀", msFightWins: "团战胜利", msUltEconomy: "大招效率",
    msOverview: "总览", msRoundLabel: "第{n}回合",
    msMultiKill: "多杀", msTeamKill: "团灭", msKillsUnit: "杀",
    // 场次列表·训练赛详情 (i18n)
    matchCount: "{n} 场对局", sdMatchList: "对局列表", sdResult: "结果", sdAnalyze: "分析", sdUnknown: "未知",
    sdEdit: "编辑", sdEditSession: "编辑场次信息", sdSave: "保存", sdCancel: "取消",
    sdOppRename: "修改对手队名", sdOppRenameHint: "基准队伍（{team}）不可修改。用于更正登记时的笔误。",
    sdMatchEdit: "编辑", sdOrder: "顺序", sdVodOffset: "视频偏移 (MM:SS)",
    sdAddLog: "补传日志", sdReplaceLog: "替换日志",
    sdReplaceWarn: "该对局现有日志数据（回合/事件/选手数据）将被删除并按新日志重新解析。仅能通过之前的 git 提交或每日备份恢复。继续吗？",
    sdDiffTitle: "手动输入与解析结果不一致：",
    sdDiffAdopt: "[确定] = 采用解析结果 · [取消] = 保留手动值（胜者移入胜负修正）",
    sdManualBadge: "手动", sdEditFail: "编辑失败：", sdUploadDone: "日志已应用。",
    // Common (buttons / delete dialogs)
    delete: "删除", reset: "重置", cancelSelection: "取消选择", selectAll: "全选", deselectAll: "全部取消",
    selectedCount: "已选", deleting: "删除中...", deleteSelected: "删除所选", deleteConfirmPre: "确定删除所选 ",
    sdIrreversible: "此操作无法撤销。", sdDeleteDone: "删除完成", sdWarnings: "警告：",
    sdPartialFail: "部分删除失败：", sdDeleteFail: "删除失败：", sdDeleteMatchPost: " 场对局吗？",
    ssDeleteSessionMid: " 个场次吗？\n该场次包含的共 ", ssDeleteSessionPost: " 场对局也将一并删除。",
    ssRebuildConfirm: "确定重建数据库吗？(Rebuild DB?)",
    // ScrimModal
    smCloseConfirm: "正在输入的内容将丢失。确定关闭吗？", smEnterName: "请输入训练赛名称。", smMinOneMatch: "请至少录入1场对局。",
    smMatchPre: "第 ", smMatchPost: " 场对局：", smPauseSelectedWarn: "已选择“有暂停”。请添加暂停区间或选择“否”。",
    smPauseTimeWarn: "请填写暂停开始/结束时间。（例：10:00）", smYoutubeLink: "YouTube 视频链接", smOptional: "（可选）",
    smTeam1Label: "1队名称（左）", smTeam2Label: "2队名称（右）", smStartPlaceholder: "例：03:30（战斗开始）",
    smSourceLabel: "比赛类型", smSourceLog: "日志比赛", smSourceManual: "手动登记（无日志）",
    smManualHint: "无日志，仅记录地图/胜负/比分。不计入日志样本指标（团战、大招、选手数据），之后可补传日志。",
    smWinnerLabel: "获胜队伍", smScoreLabel: "比分（1队 : 2队）", smVodStart: "视频开始 (MM:SS)", smVodEnd: "视频结束 (MM:SS，可选)",
    // UltimateStats
    ultFivePlus: "5个以上", ultTotal: "总计", ultValue: "价值", ultLowSampleNote: "样本不足（少于5次）· 仅供参考",
    // OverallStats
    osAnalysis: "分析", osTabFights: "团战统计", osWinBadge: "胜", osLossBadge: "负", osAllAvg: "总体平均",
    osTabSummary: "摘要", osMapWinCard: "地图胜率", osSummaryBasisTpl: "以 {team} 为基准", osTrendCard: "趋势（vs 上一时段）",
    osTrendHint: "设置开始日期后将显示与上一时段的对比趋势", osTrendPrevTpl: "上期 {p} · {n} 场团战", osFightSampleTpl: "{w}/{n} 团战",
    osSummaryEntryHeroes: "查看英雄统计", osSummaryEntryMaps: "查看地图统计", osSummaryEntryHint: "详情 →",
    osTopHeroTpl: "最常用英雄：{hero}", osTopMapTpl: "最常打地图：{map}", osSecondaryMetrics: "选手平均指标（按时间段·筛选）",
    osShowMore: "查看更多", osShowingCountTpl: "{shown} / {total}", osSummaryNoData: "没有我方队伍的对局数据。",
    osNoMatchDataPre: "没有 ", osNoMatchDataPost: " 的对局数据", osNoFightData: "没有可分析的团战数据",
    osLostFightsSuffix: " 次落败团战", osResistDescPre: "在落败团战中击杀敌方 ", osResistDescMid: " 人 → 击杀率 ", osResistDescPost: "%。数值越高，说明即使输团也换得更好。",
    osFirstDeathTop3: "首死 TOP 3", osFirstDeathLabel: "首死", osLostFightCarryTop3: "落败团战 Carry TOP 3", osNoMin10: "没有参与10次以上的选手",
    osKillsPerFight: "击杀/团战", osTotalWord: "共 ", osKillUnit: " 杀", osMin10Note: "* 以参与10次以上落败团战为准",
    osMomentumNotePre: "* 不跨对局边界 · 排除平局团战 · 对象对局：", osMomentumNotePost: " 场", osEliminated: "阵亡", osKill: "杀",
    // 标签重组：大招分析 / 首杀·首死统计
    navUltAnalysis: "大招分析",
    navKillDeath: "首杀·首死统计",
    kdToggleFk: "首杀", kdToggleFd: "首死",
    flUaTitle: "大招分析",
    flUaDesc: "分析各大招情形下的胜率，以及连招、序列与反制。以基准队伍视角。",
    flUaTabSituation: "情形", flUaTabComboSeq: "连招·序列",
    // [交换模式]
    flPatTab: "交换模式",
    flPatUs: "我", flPatOpp: "敌", flPatNone: "无大招",
    flPatChipUs: "我方", flPatChipOpp: "敌方",
    flPatChipUsTip: "我方大招", flPatChipOppTip: "敌方大招",
    flPatSumFights: "总团战数（可判定）", flPatSumKinds: "模式种类", flPatSumTop: "最常见模式",
    flPatColPattern: "模式",
    flPatSecUs: "我方先手大招模式", flPatSecOpp: "敌方先手大招模式",
    flPatSecSub: "小计：样本 {n} · 胜率 {w}",
    flPatHotTitle: "值得关注的模式",
    flPatBarToggle: "胜率条",
    flPatTableNote: "模式 = 大招交换的先后顺序。点击行可查看实际英雄构成与VOD。",
    flPatOppOther: "其他 {n}",
    flPatInsFirst: "我方先手（首个大招为我方）时胜率 {a}（{an} 团战）vs 后手时 {b}（{bn} 团战）",
    flPatInsLast: "最后一个大招为我方时胜率 {a}（{an} 团战）vs 为敌方时 {b}（{bn} 团战）",
    flExpPat1: "模式记法（逐个）：将团战中所有大招按时间顺序排列，一个大招 = 一个标签 — 蓝色徽章 = 我方大招，红色徽章 = 敌方大招（与时间线查看器的队伍配色一致），无大招的团战记为“无大招”。超过6个标签时截断为前6个 + “…”并归为同一模式。此表关注的是大招“交换的顺序” — 时间聚合（连招）分析请见[连招·序列]子标签。",
    flExpPat2: "排序规则：双方在完全相同时刻使用大招时，我方大招排在前面（与连招/开团分析同一规则）。发生率、胜率、样本均以可判定胜负的团战为准。表格按首个标签分为[我方先手]/[敌方先手]两节，节标题的小计胜率为该节全部团战的加权平均。",
    flExpPat3: "Δ(vs 敌方) = 此模式下我方胜率 − 镜像模式（我方↔敌方互换）下敌方的胜率（= 1 − 该模式下我方胜率）。例：[我方]→[敌方]的对照是[敌方]→[我方]中敌方的胜率。镜像为自身的对称模式（含无大招）显示为“—”。",
    flExpPat4: "注意：模式胜率只是相关性而非因果 — 大招数量本身（投入量）的影响与顺序的影响混在一起，请结合样本量解读。",
    flPatOnlyUlt: "仅看使用大招的团战",
    flExpPat5: "“仅看使用大招的团战”（默认开启）将无大招团战从样本中排除，发生率、摘要数字和趋势也以该总体为准。关闭后，无大招模式将计入表格与发生率分母（洞察行本就仅针对使用大招的团战，不受影响）。",
    flPatCompTitle: "构成排行",
    flPatCompNotice: "样本较小 — 仅供参考趋势。",
    flPatCompCol: "构成",
    // [开团]
    flInitTab: "开团",
    flInitSumRate: "我方先手大招率（{m}/{n} 团战）",
    flInitSumUsWin: "先手时胜率（{n} 团战）",
    flInitSumThemWin: "后手时胜率（{n} 团战）",
    flInitOurTitle: "我方开团大招",
    flInitOurDesc: "按首个大招的英雄汇总我方先手的团战 — 用哪个大招开团更容易赢。点击行 → 按选手分解 + VOD。",
    flInitOppTitle: "敌方开团大招",
    flInitOppDesc: "敌方先手的团战。胜率以我方为准 — 越低说明该开团让我们越难受。点击行 → 我方3秒内反制前3 + VOD。",
    flInitColUlt: "开团大招", flInitColShare: "开团占比", flInitColDelta: "Δ(vs 全部先手)",
    flInitColPlayer: "选手", flInitPlayersTitle: "谁开的团（按选手）",
    flInitRespTitle: "针对此开团我方3秒内反制前3",
    flInitRespNone: "没有我方在3秒内做出反制的团战。",
    flExpInit1: "先手大招（开团）= 团战中时间上的第一个大招。判定完全复用交换模式的首手定义 — 双方在完全相同时刻使用大招时，我方大招排前（计为我方先手）。总体为可判定胜负 + 使用了大招的团战，无大招团战不计入任何摘要与表格（与交换模式洞察行完全相同的计算与数字）。",
    flExpInit2: "开团占比 = 在该表（我方先手/敌方先手）内该英雄作为首个大招的比例 — 每表合计100%。Δ = 该开团大招的胜率 − 该表整体（我方先手全部或敌方先手全部）的我方胜率。",
    flExpInit3: "敌方开团表的胜率同样始终以我方为准（越低说明该开团对我们越具威胁）。展开行显示的反制迷你表与反制（克制）分析计算相同（首次使用后3秒内的我方大招，排除同时刻，每团战取最快的1个反制），只是把总体缩小为“该大招作为开团的团战”。",
    flExpInit4: "注意：开团胜率只是相关性而非因果 — 用某个大招开团可能只是阵容·局势本就有利的信号，请结合样本量解读。",
    flExpPatComp: "构成（模式行展开的迷你表）：分组依据仅为“我方大招英雄（逐个顺序）” — 敌方大招不进入分组键，以免样本被切碎（切换视角后即变为敌方构成分析）。展示为完整序列：我方位置显示英雄名（蓝色），敌方位置并列显示该组团战中敌方大招的实际频次（红色，前2 + 其他N）。例：“雾子 → 敌(安娜 2/拉玛刹 1) → 西格玛”。没有我方大招的模式（仅敌方）无构成表。点击构成行后，VOD列表将缩小为该构成的团战，且每个VOD条目会以一行显示该团战完整的大招序列（我/敌 + 英雄）。",
    // FightLabStats (团战分析)
    navFightLab: "团战分析",
    flTitle: "团战分析",
    flDesc: "按时间段对比各情形下以团战为单位的胜率。以基准队伍视角。",
    flTabFights: "交战", flTabUlts: "大招", flTabUltSeq: "大招连招·序列",
    flPresetAll: "全部", flPreset1w: "最近1周", flPreset2w: "最近2周", flPreset1m: "最近1个月", flPresetCustom: "自定义",
    flPresetAllBefore: "此前全部", flPresetPrevSame: "上一个同长时段",
    flMinSample: "最小样本",
    flSideDate: "时间段", flSideTrend: "趋势时段", flSideView: "视角", flSideOpp: "对手", flSideMap: "地图", flSideMin: "最小样本", flSideFilter: "筛选",
    flApply: "应用",
    flScopePeriod: "时间段", flScopeTrend: "趋势", flScopeView: "视角", flScopeOpp: "对手", flScopeMap: "地图", flScopeNone: "无",
    flOverlapWarn: "最近时段与过去时段有重叠。样本会被重复统计，解读时请注意。",
    flColSituation: "情形", flColOccur: "发生率", flColDOcc: "Δ发生率 (vs 敌方)",
    flColWin: "胜率", flColDWin: "Δ胜率 (vs 敌方)", flColSampleOne: "样本",
    flColTrend: "趋势 (vs 过去)", flColStability: "稳定性", flColStatus: "状态",
    flStabStable: "稳定", flStabVolatile: "波动", flStatusOk: "可用",
    flUnitPp: "%p", flTipUs: "我方", flTipOpp: "敌方",
    flLowSample: "样本不足",
    flRecentShort: "最近", flPastShort: "过去",
    flCmpPastAll: "过去全部", flCmpPrevPrefix: "上一个 ",
    flVerdictImproved: "改善", flVerdictWorse: "恶化", flVerdictSame: "持平",
    flPerspUs: "我方视角", flPerspThem: "敌方视角",
    flPerspNotice: "敌方视角 — 显示的胜率、发生率和总评均以对手队伍为准。对手数据仅来自与我方的训练赛样本。",
    // [选手] 子标签
    flTabPlayers: "选手",
    flPbGroupPlayer: "按选手", flPbGroupPlayerHero: "按选手+英雄",
    flPbColPlayer: "选手", flPbGroupFight: "团战指标", flPbGroupRound: "回合指标",
    flPbFights: "团战数", flPbKp: "击杀参与率", flPbFk: "首杀/团战", flPbFd: "首死/团战",
    flPbUpf: "大招/团战", flPbUwin: "用大团战胜率", flPbKd: "K/D", flPbDmg10: "伤害量/10分钟",
    flPbHeal10: "治疗量/10分钟", flPbUlt10: "大招数/10分钟",
    flPbPoolAvg: "池平均", flPbPoolShortPre: "池不足（", flPbPoolShortPost: "人）",
    flPbTipSample: "样本",
    flPbRankTpl: "{n}人中第{k}",
    flPbRankShortTpl: "第{k}", flPbNoPool: "池不足",
    flPbRankRoleTpl: "{role}第{k}",
    flPbRoleTank: "重装", flPbRoleDps: "输出", flPbRoleSup: "支援",
    flPbTipVsPast: "较过去",
    flPbColSignals: "信号",
    flPbSigTopSuffix: " 靠前", flPbSigLowSuffix: " 需注意",
    flPbGroupLabel: "分组依据", flPbSortLabel: "排序依据", flPbSortName: "选手名",
    flPbUnitFight: " 团战", flPbUnitRound: " 回合",
    flPbPDashSample: "无排名：本人样本低于池的最低标准（团战20 / 回合10）",
    flPbFootnote: "每格为数值、趋势箭头（较过去）、（括号 = 同定位池（我方+对手）内排名）。悬停单元格可查看池人数等详情。排名无意义时显示 (—) 或（池不足）。",
    flPbPoolTpl: "{role}池：我方 {us} 人 + 对手 {them} 人",
    flPbPoolWarn: "※ 排名基于与我方训练赛收集的数据。对手选手数值仅限对阵我方的样本，池较小时排名可能大幅波动。",
    flPbExpSrc: "指标来自两个数据源 — [团战指标]基于击杀·大招事件（与交战/大招标签同一数据），[回合指标]基于回合汇总表（与个人统计标签同一数据），因此二者口径可能不同。",
    flPbExpFights: "团战数：本人出场的回合中我方发生的团战数。",
    flPbExpKp: "击杀参与率：在队伍至少击杀1人的团战中，（本人击杀 ÷ 队伍击杀）的平均值。",
    flPbExpFkFd: "首杀/团战·首死/团战：团战首杀由本人取得 / 本人被首杀的比例。首死越低越好，箭头、队伍平均配色与排名方向均反转。",
    flPbExpAxes: "单元格读法：“数值 ↑ (第5)”一行 — 数值为当前时段，箭头为与自身过去（趋势时段）对比（首死等反转指标颜色反转，无变化为 →），括号 = 同定位池（我方+对手）内并列排名（同分共享名次，反转指标以好的方向为第1）。悬停可查看池人数（例：13人中第5）、较过去的变化、样本、与池平均的差距及池构成。信号的前/后20%判定也以此名次÷人数为准。",
    flExpSidebar: "在左侧边栏设置时间段、趋势时段、视角、对手/地图、最小样本后，需点击“应用”才会生效。时间段选择“全部”时不显示对比（Δ·箭头）。",
    flPbExpSignals: "信号：在池人数达标的指标中，进入前20%为绿色（强项），落入后20%为红色（需注意）。反转指标以反转方向为准。每名选手最多2个（优先显示需注意），仅用于展示 — 不计入总评。",
    flPbExpPool: "排名池与对手/地图筛选无关，以“最近时段全部数据”为准（防止筛选把池缩小到排名失去意义）。最小样本：团战指标20团战 / 回合指标10回合。池少于8人时显示“池不足”。",
    flPbExpHeal: "治疗量/10分钟仅对治疗（支援）显示。每10分钟折算以出场回合的 duration 之和为准，缺少 duration 的回合从样本中排除。",
    // 排行榜
    flLbTitle: "排行榜",
    flLbMetric: "指标", flLbRole: "定位",
    flLbColRank: "排名", flLbColTeam: "所属", flLbColValue: "数值",
    flLbUnranked: "未入榜（样本不足）",
    flLbSupportOnly: "该指标仅统计支援定位 — 请将定位选择为“支援”。",
    flLbPoolWarnTpl: "池仅有 {n} 人，低于最低标准（{min} 人）— 排名仅供参考。",
    flPbExpLb: "排行榜：与单元格括号中“(支援 第3)”相同的池（最近时段全部数据 · 我方+对手 · 同定位 · 满足最小样本）及相同的并列排名规则，展开为表格。与对手/地图筛选无关，以整个时段为准（沿用原池规则），反转指标（首死等）以好的数值为第1。样本不达标的选手在底部以“未入榜”仅显示数值。",
    flRowFirstPick: "首杀", flRowFirstDeath: "首死",
    flRowFdTank: "重装首死", flRowFdDamage: "输出首死", flRowFdSupport: "支援首死", flRowFdOther: "其他首死",
    flRowFkTraded: "取得首杀后被换", flRowFdTraded: "首死后换回",
    flRowUltUsed: "使用大招的团战", flRowFirstUlt: "先手大招（我方先手）", flRowEnemyFirstUlt: "敌方先手大招",
    flRowUltAdv: "大招优势", flRowUltDis: "大招劣势", flRowUltEven: "大招持平（双方各≥1）",
    flRowUlt1: "投入1个大招", flRowUlt2: "投入2个大招", flRowUlt3: "投入3个以上大招",
    flSumAvgUlt: "每团平均大招投入（我方）", flSumUltConv: "大招转化率（用大团战胜率）",
    flUnknownNotePre: "无法判定胜方的团战（双方存活人数相同 = 按平局处理）：",
    flUnknownNotePost: " — 计入发生率分母，但从胜率样本中排除。",
    flExplainTitle: "指标说明",
    flExpWinner: "团战胜负：团战结束时存活人数更多的一方判为获胜。存活人数相同（平局）时不计入胜率统计。",
    flExpTwoCols: "每行有两类性质不同的数字 — 该情形出现的频率看“发生率”列，处于该情形时打赢团战的能力看“胜率”列。行名中的（胜率）指以胜率列为准。",
    flExpOccur: "发生率·胜率：当前时段我方的数值。Δ列（vs 敌方）为同一批团战中对手对称情形数值的差 — 例：取得首杀行的Δ发生率 = 我方首杀率 − 敌方首杀率（=我方首死率）。“越低越好”的情形颜色反转，±1%p 以内为灰色。悬停单元格可查看我方/敌方原值。",
    flExpFirstPick: "首杀：团战首杀由我方取得。发生率（越高越好）为拿下首杀的频率，胜率为取得首杀的团战是否真的打赢。",
    flExpFirstDeath: "首死：团战首杀发生在我方身上。发生率（越低越好）为先被击杀的频率，胜率为即便如此仍翻盘的比例。",
    flExpFdRole: "重装/输出/支援首死：我方首死中按阵亡选手英雄定位的分解。发生率（越低越好）为该定位在“我方首死”中的占比，胜率为该情形下的团战胜率。",
    flExpFkTraded: "取得首杀后被换：我方取得首杀后5秒内被对手回敬一杀。发生率（越低越好）为拱手让出首杀优势的频率，胜率为被换后仍打赢的比例。胜率上升是好信号，并不代表被换变频繁。",
    flExpFdTraded: "首死后换回：我方被首杀后5秒内也以击杀回敬。发生率（越高越好）为挽回不利开局的频率，胜率为换回后是否真的打赢。",
    flExpUltUsed: "使用大招的团战：我方使用至少1个大招的团战。此行胜率即为“大招转化率”。",
    flExpFirstUlt: "先手/敌方先手大招：团战首个大招由哪一方先用。发生率分母为“任一方使用过大招的团战”。",
    flExpUltCount: "大招优势/劣势/持平：该团战中我方比对手用的大招更多/更少/相同。",
    flExpUltInvest: "投入1·2·3个以上大招：按我方在该团战投入的大招数量统计胜率。用得越少赢下越高效。",
    flExpDryFight: "干团（持有大招却不使用的团战）因缺少大招充能数据暂不提供。",
    flExpTrend: "趋势（vs 过去）= 最近胜率 − 过去胜率。↑绿=改善，↓红=恶化，±1%p 以内为 →（持平）。总评（改善/恶化/持平）以该趋势（较过去）为准，Δ列（较对手）不计入总评。悬停趋势单元格可查看过去→最近的原值。",
    flExpSample: "样本：当前时段胜率计算所用的团战数。过去样本见行的悬浮提示。低于最小样本的行会变暗，并在状态列标注“样本不足”。",
    flExpStability: "稳定性：当前与过去样本均不低于（最小样本 × 4）时为“稳定”，否则为“波动”。波动行的趋势因样本小可能大幅摆动，仅供参考。",
    // 大招连招分析
    flCmbTitle: "大招连招分析",
    flCmbRoleFilter: "定位筛选",
    flCmbGroupBy: "分组依据",
    flCmbGroupPH: "选手+英雄", flCmbGroupH: "仅英雄",
    flCmbSize: "连招规模", flCmbWindow: "连招间隔（秒）", flCmbTopK: "Top-k", flCmbMinSample: "最小连招样本",
    flCmbGenerate: "生成连招",
    flCmbTopTitle: "最佳连招", flCmbBottomTitle: "最差连招",
    flCmbColCombo: "连招", flCmbColRoles: "定位", flCmbColAvgInvest: "平均大招投入",
    flCmbPrompt: "点击“生成连招”后，将按当前侧边栏筛选（时间段·视角·对手·地图）进行统计。",
    flCmbEmpty: "没有符合条件的连招。",
    flCmbNote: "胜率以当前时段为准，趋势为与趋势时段内同一连招胜率的对比。样本不足的连招会变暗，且不会排到样本达标的连招之上。",
    flExpCombo1: "大招连招：我方（当前视角队伍）大招的“时间链” — 在上一个我方大招后连招间隔（默认3秒）内接续使用的大招归入同一连招链。两个我方大招之间夹入敌方大招时链条中断（后一个大招属于反制而非连招 — 见下方反制分析），单独使用的大招不算连招。胜率·平均大招投入以出现该连招的团战为准，且两者均以可判定胜负的团战（排除平局）为准。",
    flExpCombo2: "子组合统计：当链中大招数多于连招规模时，从链成员中取规模为N的所有子组合分别计数（链条保证了时间上的接近）— 例：3大招的链计为3个规模2的连招，因此一场团战可能重复计入多个连招。",
    flExpCombo3: "注意：连招胜率只是相关性而非因果 — 某连招可能只在特定地图·对手·局势下出现，请结合样本量解读。",
    // 大招序列分析
    flSeqTitle: "大招序列分析",
    flSeqStep1: "第1步 — 选择首个大招", flSeqStep2: "第2步 — 后续大招",
    flSeqStep3: "第3步 — 第二个大招", flSeqStep4: "第4步 — 大招交互",
    flSeqSide: "阵营", flSeqSideOur: "我方", flSeqSideOpp: "敌方",
    flSeqHero: "英雄", flSeqUltWord: "大招", flSeqRespWin: "反制窗口（秒）",
    flSeqAnalyze: "分析", flSeqAnalyze2: "交互分析",
    flSeqNoData: "没有出现所选大招且可判定胜负的团战。",
    flSeqSummaryTpl: "{n} 团战 · 胜率 {win} · Δ(vs 敌方) {d} · 趋势 {trend}",
    flSeqTopCounters: "克制（敌方后续）", flSeqTopFollowups: "我方后续",
    flSeqColFollow: "后续大招", flSeqColSeqRate: "序列率", flSeqColDWin: "Δ胜率", flSeqColReact: "平均反应时间",
    flSeqNote: "胜率始终以我方（当前视角）团战胜率为准。样本不足的行会变暗，不会按胜率被提升排序。",
    flSeqPrefill: "从后续中选择", flSeqManualOpt: "（手动选择）",
    flSeqSecondLabel: "第二个大招",
    flSeqPickSecond: "选择第二个大招并点击“交互分析”。",
    flSeqSameWarn: "第二个大招与第一个相同 — 请选择不同的大招。",
    flSeqDiffWord: "差值",
    flSeqStep4Note: "胜率为我方（当前视角）团战胜率，Δ胜率为与当前范围内全部团战胜率的差值。胜率差异是相关性而非因果关系。",
    flExpSeq1: "大招序列：在出现所选大招的团战中，统计其首次使用时刻“之后”（严格晚于）且在反制窗口（默认3秒）内使用的大招为后续大招。timestamp 相同（同时使用）不计为后续 — 同时连招属于上方的连招分析范畴。样本·序列率·反应时间均以可判定胜负的团战（排除平局）为准。",
    flExpSeq2: "序列率 = 出现该后续的团战数 ÷ 出现所选大招的全部团战数。平均反应时间 = 所选大招 → 后续大招（以各团战内首次使用为准）时间差的平均值。第2步Δ胜率对比“所选大招整体胜率”，第4步Δ胜率对比“当前范围全部团战胜率”。",
    flExpSeq3: "克制：所选大招之后出现的敌方后续大招中，我方胜率最低的大招 — 意味着对手用该大招应对时我们经常输。但胜率差异只是相关性而非因果，请结合样本量解读。",
    // 该场面 VOD 列表
    flVodMore: "查看更多", flVodReact: "反制",
    flExpVod: "点击行可打开对应团战的VOD列表。视频从团战开始前约12秒起播。",
    // 大招反制（克制）分析
    flCtrTitle: "大招反制（克制）分析",
    flCtrDesc: "对手大招打开时，我方用哪个大招反制胜率更高 — 针对每个敌方大招的已验证解法清单。点击行可展开全部反制大招。",
    flCtrOverviewTitle: "敌方主要大招概览",
    flCtrColEnemyUlt: "敌方大招", flCtrColWinWith: "此时我方胜率", flCtrColNoResp: "无反制时胜率",
    flCtrColBest: "最佳反制大招", flCtrColBestWin: "反制时胜率", flCtrColBestN: "反制样本",
    flCtrColResp: "我方反制大招", flCtrColRespRate: "反制率", flCtrColDNo: "Δ(相对无反制)",
    flCtrNote: "胜率差异是相关性而非因果。样本较小的反制仅供参考。",
    flExpCtr1: "反制：敌方大招首次使用之后（严格晚于）且在反制窗口（默认3秒）内我方使用的所有后续大招（含首个后续）— 与序列分析的后续规则一致，复用同一计算。",
    flExpCtr2: "无反制 = 该敌方大招之后反制窗口（默认3秒）内我方未使用任何大招的团战。Δ(相对无反制) = 出现该反制的团战胜率 − 无反制团战的胜率，直接体现“反制的价值”。最佳反制大招为满足最小样本的反制中胜率第1者（无达标候选时显示样本不足）。",
    flExpCtr3: "一场团战中我方有多个反制时，会分别计入每个反制 — 因此反制率之和可能超过100%，且不能与无反制率简单相加。",
    flExpWindows: "时间窗口统一标准：连招是连招间隔（默认3秒）内的“我方大招连锁”（协同），反制/序列是反制窗口（默认3秒）内“对敌方（或所选）大招的即时反应”。两个窗口为独立设置，可分别调整。",

    // ── 地图分析标签 ──
    navMapAnalysis: "地图分析",
    maTitle: "地图分析",
    maDesc: "我们在哪些地图·地图类型上强或弱 — 为地图选择与BP判断提供实测依据。",
    maSummaryOverall: "全部地图胜率", maSummaryBest: "最强地图类型", maSummaryWorst: "最弱地图类型",
    maSummaryNone: "没有样本达标的类型",
    maTypeTitle: "地图类型汇总",
    maTypeHint: "点击行可展开该类型下各地图的统计。",
    maMapsTitle: "各地图详情",
    maMapsHint: "点击行可展开该地图的对局列表。按游玩率降序排列。",
    maWeeklyTitle: "每周走势",
    maColType: "地图类型", maColMap: "地图", maColPlayRate: "游玩率", maColMapWin: "地图胜率",
    maColFightWin: "团战胜率", maColDelta: "Δ (vs 敌方)", maColTrend: "趋势 (vs 过去)",
    maColTopHeroes: "Top 英雄", maColStatus: "状态",
    maCellPlayTpl: "{p}（{n} 图）", maCellWinTpl: "{p}（{w} 胜）",
    maMlDate: "日期", maMlOpp: "对手", maMlScore: "比分", maMlResult: "结果", maMlLink: "场次详情",
    maMlOpen: "前往 →",
    maResultWin: "胜", maResultLoss: "负", maResultDraw: "平", maResultUnknown: "未记录",
    maTopHeroNone: "样本不足",
    maWeeklyRowAll: "全部",
    maWeeklyMetricFight: "团战胜率", maWeeklyMetricMap: "地图胜率", maWeeklyMetricPicks: "选用次数",
    maWeekLabelTpl: "{m}月第{n}周",
    maWeekDetailTpl: "{label} 详情（{range} · 共 {n} 图）",
    maColPicks: "选用数",
    maWlDrawTpl: "{w}胜 {l}负 {d}平",
    maSrcSplitTpl: "日志 {n} · 手动 {m}", msNoLogNotice: "该对局没有日志，请补传日志。", msWatchVod: "观看 VOD",
    maPushTip: "未修正的推进对局按平局统计。",
    maCorrected: "已修正",
    maWeeklyCellTipTpl: "{range} · {metric} {p} · {w} 胜 / 样本 {n}",
    maWeeklyPicksTipTpl: "{range} · 选用 {n} 次",
    maWeeklyLowTipTpl: "{range} · 样本 {n}",
    maTipUsOppTpl: "我方 {a} vs 敌方 {b}",
    maTipTrendTpl: "过去 {b} → 最近 {a}",
    // 指标说明
    maExpMapWin: "地图胜率 = 以对局（地图）为单位的胜场 ÷ 有结果记录的对局数（平局计入分母，未记录结果的对局除外）。团战胜率 = 以团战为单位的胜场 ÷ 可判定胜方的团战数。两个指标统计单位不同，需一并解读。",
    maExpPlayRate: "游玩率 = 该地图（类型）的对局数 ÷ 范围内全部对局数。没有任何团战记录的对局因数据特性不计入统计。",
    maExpDelta: "Δ(vs 敌方) = 我方团战胜率 − 敌方团战胜率（同一批团战的对侧视角）。趋势(vs 过去) = 最近时段团战胜率 − 过去时段团战胜率（按侧边栏的趋势时段）。",
    maExpTopHeroes: "Top 英雄为近似值 — 因缺少完整出场英雄数据，以“该地图上我方使用过其大招的英雄”所在团战的胜率计算（每英雄至少 {n} 团战，按胜率降序）。未使用大招的出场无法被捕捉，仅供参考。",
    maExpWeek: "每周走势的“周”从周一开始（周一~周日），最近的周在右侧。周标签“6月第4周”以该周周一为准 — 月份为周一所在的月份，周次为该月的第几个周一（例：6/23周一所在周 = 6月第4周）。点击周表头可打开该周所选地图的详情。胜率模式下，该周无样本的单元格显示灰色“—”，选用次数模式则以无颜色的方式显示对局数。",
    maExpPushFix: "推进图特例：推进图日志中没有比分，自动判定会存为平局（0:0）。在训练赛场次页面手动修正（胜负修正）过的对局按修正后的胜负统计，仅未修正的对局保留为平局。修正与原始记录分开存储，可随时撤销。",
    maExpStatus: "无样本下限 — 打过1局以上的地图·类型均计入统计。地图胜率单元格的方向色（绿/红）以50%为界，样本较小的行请结合括号中的样本数谨慎解读。对手筛选仅在“敌方视角”下显示（切回我方视角时自动清除）。",
    maExpCausal: "胜率差异只是相关性而非因果 — 请结合对手水平、阵容、版本等背景解读。",
    // 胜负修正（推进图）— 仅训练赛创建弹窗
    woLabel: "胜负修正",
    woNone: "未修正",
    woWinSuffix: "胜",
    woHint: "推进图日志中没有比分，自动判定会存为平局。选择实际获胜队伍后将反映到地图分析与统计（原始记录保留）。",
    // 事后胜负修正徽章·内联编辑（对局详情·场次对局列表）
    woBadgeDraw: "平局 · 手动判定",
    woBadgeOverridden: "已手动修正",
    woPick: "判定",
    woSaving: "保存中…",
    woSaveFail: "修正保存失败"
  }
};

// [i18n zh] 지원 언어 목록·localStorage 키. 저장값이 목록 밖이면 기본 ko.
export const LANGUAGES = ['ko', 'en', 'zh'];
const LANG_STORAGE_KEY = 'lang';
const loadLang = () => {
  try {
    const v = localStorage.getItem(LANG_STORAGE_KEY);
    return LANGUAGES.includes(v) ? v : 'ko';
  } catch { return 'ko'; }
};

export const LanguageProvider = ({ children }) => {
  const [language, _setLanguage] = useState(loadLang);
  const setLanguage = (lang) => {
    const v = LANGUAGES.includes(lang) ? lang : 'ko';
    _setLanguage(v);
    setDisplayLanguage(v); // gameData 표시명(영웅/맵/스킬) 언어 동기화
    try { localStorage.setItem(LANG_STORAGE_KEY, v); } catch { /* ignore */ }
  };
  // 초기 마운트 시 저장된 언어를 gameData 에도 반영
  if (typeof window !== 'undefined') setDisplayLanguage(language);
  // 하위호환: 기존 토글은 ko→en→zh 순환으로 유지(현재 UI는 드롭다운 사용)
  const toggleLanguage = () => setLanguage(LANGUAGES[(LANGUAGES.indexOf(language) + 1) % LANGUAGES.length]);
  const t = translations[language] || translations.ko;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);