// src/LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  ko: {
    back: "뒤로", loading: "데이터 로딩 중...", noData: "데이터가 없습니다.", add: "추가",
    dashboard: "대시보드", sessions: "스크림 세션", overall: "전체 통계", teamManage: "팀 관리 (준비중)",
    navGroupStats: "통계", navGroupAnalysis: "분석", navBanpick: "밴픽",
    ssCalendar: "달력", ssList: "리스트",
    title: "스크림 데이터 센터", desc: "오버워치 스크림 로그를 업로드하여 팀의 퍼포먼스를 분석하세요.", desc2: "데이터는 서버에 안전하게 저장됩니다.",
    createScrim: "스크림 생성하기", viewHistory: "기록 보기", uploading: "업로드 중...",
    modalTitle: "스크림 기록 생성", step1Title: "기본 정보 입력", step1Desc: "스크림 날짜와 시간을 입력해주세요.",
    scrimName: "스크림 이름", scrimNamePlace: "예: 2024-05-20 vs 상대팀 스크림", videoUrl: "유튜브 전체 영상 링크",
    date: "날짜", time: "시간", next: "다음: 경기 입력하기", prev: "이전", save: "저장 및 완료", success: "스크림 저장 완료!",
    backToList: "목록으로 돌아가기", totalDuration: "총 경기 시간", roundScore: "라운드 스코어",
    finalBlows: "최종 타격", fightWins: "전투 승리", ultEconomy: "궁극기 효율", lowerBetter: "낮을수록 좋음",
    lead: "우세", draw: "무승부", win: "승리", tabStats: "스텟", tabKillLog: "킬 로그", tabChart: "차트",
    tabEvent: "이벤트", tabPlayer: "플레이어 통계", totalCumulative: "전체 (누적)", round: "라운드",
    fightSurvivors: "한타별 생존 인원", survivors: "명 생존", duration: "지속", avgSurvivors: "평균 생존",
    firstBloodAnalysis: "선취점 분석 승률", standard: "기준", situation: "상황", fightCount: "전투 횟수",
    winRate: "승률", fbSecured: "선취점 획득 시", fbSuffered: "선취점 허용 시", ultsPerFight: "한타 당 궁극기 사용",
    fbByRole: "역할별 결정타", cumulativeDmg: "라운드별 누적 영웅 피해", dmgEfficiency: "딜링 효율성 분석",
    heroDmgDealt: "가한 영웅 피해", battery: "딜만 넣는 배터리 (비효율)", carry: "캐리 (딜+킬)", role: "역할",
    player: "플레이어", team: "팀", playTime: "시간", elims: "처치", deaths: "죽음", assists: "지원",
    heroDmg: "영웅 딜", barrierDmg: "방벽 딜", healRcvd: "받은 힐", dhRatio: "딜:힐 비", healing: "준 힐",
    dmgTaken: "받은 딜", ults: "궁극기", fight: "전투", noEvents: "이벤트 없음", noUlts: "궁극기 사용 기록 없음",
    events: "이벤트", ultimatesUsed: "사용된 궁극기", pickRate: "점유율", soloKills: "단독 처치", ultUsage: "궁극기 사용",
    per10: "/ 10분", tank: "탱크", dps: "딜러", support: "지원",
    filterPlaceholder: "필터 입력 (예: 리장 타워, 우양, 루시우, 승리 ...)", filterTip: "선수 이름, 맵, 영웅 등을 입력하여 상세 분석을 해보세요.",
    searchedGames: "검색된 경기", avgWinRate: "평균 승률", avgKills: "평균 처치", avgDeaths: "평균 데스", avgDmg: "평균 딜량",
    tabHighlights: "하이라이트 & 요약", tabHeroes: "영웅별 통계", tabMaps: "맵별 통계", highlights: "하이라이트",
    noMoments: "조건에 맞는 장면이 없습니다.", heroStatsTitle: "영웅별 성적 (필터 기준)", mapStatsTitle: "맵별 통계",
    hero: "영웅", gamesPlayed: "게임 수", kda: "KDA",
    dateFilter: "기간 설정", startDate: "시작일", endDate: "종료일", allDates: "전체 기간",
    ultStatsTitle: "궁극기 가치 및 한타 분석", ultCountVsWin: "팀 궁극기 투자 개수 대비 한타 승률", ultEfficiency: "영웅별 궁극기 가치 (한타 승률 순)",
    ultUses: "사용 횟수",
    baseTeam: "기준 팀", allTeams: "전체 팀",
    matchStart: "경기 시작 시점", matchEnd: "경기 종료 시점",
    objectiveCaptured: "거점 점령", flNoDataInPeriod: "선택한 기간에 스크림 데이터가 없습니다 (마지막 스크림: {date})", flShowAllPeriod: "전체 기간 보기",
    matchStartTip: "영상에서 전투 시작(카운트다운 끝) 시점",
    navUltimateStats: "궁극기 통계", navFirstKill: "퍼킬 통계", navFirstDeath: "퍼뎃 통계", navFirstFight: "첫한타", navPersonal: "개인 통계",
    ffTitle: "첫 한타 모아보기", ffDesc: "각 맵·라운드의 첫 교전 시점을 모아 영상으로 바로 점프합니다. (쟁탈/화물/혼합은 라운드별, 플래시포인트/밀기는 매치당 1개)",
    ffAllOpponents: "전체 상대", ffAllMaps: "전체 맵", ffColDate: "날짜", ffColMap: "맵", ffColRound: "라운드", ffColMatchup: "매치업", ffColTime: "교전 시각", ffColLink: "영상",
    ffWatch: "보기", ffNoVideo: "영상 없음", ffLoading: "불러오는 중…", ffError: "데이터를 불러오지 못했습니다.",
    // FirstKillStats
    fkTitle: "퍼킬 분석", fkDesc: "한타를 터뜨리는 캐리력과 주력 희생양, 사용 스킬을 상세히 분석합니다.",
    allPositions: "전체 포지션", matchup: "특정 매치업:", myTeamAll: "우리 팀 (전체)", enemyTeamAll: "상대 팀 (전체)",
    position: "포지션", fkColFights: "한타 횟수", fkColCount: "퍼킬 횟수", fkColRate: "퍼킬 비율 (%)",
    timesUnit: "회", fkTopVictims: "주요 희생양 (Player)", fkTopHeroes: "집중 공략 영웅 (Hero)", fkKillSkill: "결정타 스킬 (누구에게 적중?)",
    noFilteredData: "조건에 맞는 데이터가 없습니다.",
    // FirstDeathStats
    fdTitle: "퍼뎃 분석", fdDesc: "선수들의 생존 능력과, 주로 누구에게/어떤 스킬에 먼저 죽었는지를 상세히 분석합니다.",
    fdColCount: "퍼뎃 횟수", fdColRate: "퍼뎃 비율 (%)",
    fdNemesis: "천적 (Player)", fdWatchHeroes: "경계 대상 영웅 (Hero)", fdDeadlySkill: "치명적 스킬 (누구의 스킬을 맞았는가)",
    // PlayerProfileView
    all: "전체", ppNoPlayers: "집계된 선수 데이터가 없습니다.", ppRosterTitle: "선수단 목록", ppSearchPlaceholder: "선수 검색...",
    ppOverallKd: "종합 K/D", ppDmgPer10: "10분당 딜량", ppHealPer10: "10분당 힐량", ppUltPerMatch: "경기당 궁극기",
    ppHeroPool: "모스트 영웅 풀", ppNoHeroes: "영웅 플레이 기록이 없습니다.", ppRecentForm: "최근 K/D 폼 (Form)",
    ppSelectPrompt: "왼쪽 목록에서 선수를 선택해주세요.",
    // PlayerCompareView
    navCompare: "선수 비교",
    pcRosterTitle: "선수 선택", pcSelectHint: "2명 이상 선택하세요", pcSelectedCount: "명 선택됨",
    pcSelectPrompt: "비교할 선수를 2명 이상 선택해주세요.",
    pcMetricCompare: "지표 비교", pcScopeLabel: "범위", pcScopeAll: "전체 (종합)",
    pcRadarTitle: "종합 능력치 (상대 비교)", pcRadarHint: "선택된 선수 중 최고값 기준 100% 환산",
    pcHeroCompare: "영웅별 비교", pcSelectHeroLabel: "영웅 선택:", pcNoHeroRecord: "기록 없음",
    pcHeroPlayTime: "플레이 시간", pcBest: "최고", pcMetricKd: "K/D", pcMetricWinRate: "승률",
    pcHeroUltEff: "궁당 킬", pcHeroUltWin: "궁 한타 승률", pcHeroUltGames: "한타", pcHeroUltUses: "궁", pcHeroUltCharge: "평균 궁 충전", pcSecUnit: "초", pcHeroImpact: "영향력 (처치/10)",
    pcMetricDmg: "10분당 딜", pcMetricHeal: "10분당 힐", pcMetricUlt: "경기당 궁극기", pcMin: "분",
    pcMetricMitig: "10분당 경감", pcMetricFb: "10분당 결정타", pcMetricSecondaryMixed: "10분당 보조 지표",
    pcTagHeal: "힐", pcTagMitig: "경감", pcTagFb: "결정타",
    // MatchStats
    msNoFights: "기록된 전투(킬)가 없습니다.", msUltEffWin: "효율적 승리 (덜 씀)", msUltSaveLoss: "궁 아끼다 패배", msUltOverInvest: "과투자 (2개 이상 초과)",
    msLostFightTitle: "패배 한타 저항력 (Kill Exchange in Lost Fights)", msAvgKillRateOnLoss: "패배 시 평균 적 처치율",
    msAvgWord: "평균 ", msKillsUnit: "명 처치", msLossUnit: "회 패배", msResistKills: "저항 킬 수",
    msMomentumTitle: "한타 모멘텀 (연속 승률 및 턴 뒤집기)", msWinRateAfterWin: "자리 먹었을 때 승률", msWinToWin: "(승리 ➔ 승리)", msSnowball: "유리함을 굳히는 능력",
    msWinRateAfterLoss: "자리 못 먹었을 때 승률", msLossToWin: "(패배 ➔ 승리)", msComeback: "턴을 뒤집는 능력",
    msFirstDeathAnalysis: "선취점 획득 및 개인별 데스 분석 (First Deaths)", msFirstKillCountTeam: "선취점 획득 횟수 (팀)", msFirstDeathRank: "퍼스트 데스 순위",
    msPlayerHero: "선수 (Hero)", msFirstBloodDeaths: "퍼블 데스", msDeathCause: "주요 데스 원인 (누구의 스킬을 맞았는가)", msNoDataShort: "데이터 없음",
    msUltSummary: "궁극기 종합 (Ultimates)", msTotalUlts: "총 궁극기 사용 횟수 (Total Ultimates Used)", msFirstUltInFight: "한타 첫 궁극기 사용 (Used Ult First in Fight)", msUltTiming: "궁극기 사용 타이밍 (Timing)",
    msPhaseEarly: "초반 (진입)", msPhaseMid: "중반", msPhaseLate: "후반", msUltExchange: "궁극기 교환비 및 과투자 (Ult Exchange)",
    msAvgConsumed: "평균 소모", msWonFight: "승리한 한타:", msLostFightLabel: "패배한 한타:", msCountUnit: "개",
    msNoVideo: "해당 경기는 영상 기록이 없습니다", msTabStats: "스탯표", msTabKill: "킬 로그", msTabChart: "상세 분석 차트", msTabTimeline: "타임라인", msTabCompare: "선수 비교",
    // 궁극기 타임라인 서브탭
    msTabUltTl: "궁극기 타임라인",
    msUltTlNote: "한타별 궁 흐름입니다. 궁 옆의 +X.Xs는 그 한타의 첫 궁 기준 상대 시간이며, 영상 링크는 한타 시작 약 12초 전부터 재생됩니다.",
    msUltTlFight: "한타", msUltTlWinner: "승자", msUltTlDraw: "판정 불가", msUltTlNoUlt: "궁 사용 없음",
    // 매치 상세 요약 카드·라운드 탭·이벤트 라벨 (i18n)
    msBackToOverview: "요약으로", msTotalTime: "총 경기 시간", msScoreLabel: "스코어", msWinnerLabel: "승자",
    msFinalBlows: "결정타", msFightWins: "한타 승리", msUltEconomy: "궁 효율",
    msOverview: "종합", msRoundLabel: "{n}라운드",
    msMultiKill: "멀티킬", msTeamKill: "팀킬", msKillsUnit: "킬",
    // 세션 리스트·스크림 상세 (i18n)
    matchCount: "매치 {n}개", sdMatchList: "매치 목록", sdResult: "결과", sdAnalyze: "분석", sdUnknown: "알 수 없음",
    // Common (buttons / delete dialogs)
    delete: "삭제", reset: "초기화", cancelSelection: "선택 취소", selectAll: "전체 선택", deselectAll: "전체 해제",
    selectedCount: "선택됨", deleting: "삭제 중...", deleteSelected: "선택 삭제", deleteConfirmPre: "선택한 ",
    sdIrreversible: "이 작업은 되돌릴 수 없습니다.", sdDeleteDone: "삭제 완료", sdWarnings: "경고:",
    sdPartialFail: "일부 삭제 실패: ", sdDeleteFail: "삭제 실패: ", sdDeleteMatchPost: "개 매치를 삭제하시겠습니까?",
    ssDeleteSessionMid: "개 세션을 삭제하시겠습니까?\n이 세션에 포함된 총 ", ssDeleteSessionPost: "개의 매치도 함께 삭제됩니다.",
    ssRebuildConfirm: "DB를 복구하시겠습니까? (Rebuild DB?)",
    // ScrimModal
    smCloseConfirm: "입력 중인 내용이 사라집니다. 정말 닫으시겠습니까?", smEnterName: "스크림 이름을 입력해주세요.", smMinOneMatch: "최소 1개의 경기를 기록해주세요.",
    smMatchPre: "", smMatchPost: "번 경기: ", smPauseSelectedWarn: "'퍼즈 있음'을 선택하셨습니다. 퍼즈 구간을 추가하거나 '아니오'를 선택해주세요.",
    smPauseTimeWarn: "퍼즈 시작/종료 시간을 모두 입력해주세요. (예: 10:00)", smYoutubeLink: "유튜브 영상 링크", smOptional: "(선택)",
    smTeam1Label: "1팀 이름 (왼쪽)", smTeam2Label: "2팀 이름 (오른쪽)", smStartPlaceholder: "예: 03:30 (전투 시작)",
    // UltimateStats
    ultFivePlus: "5개 이상", ultTotal: "총합", ultValue: "가치", ultLowSampleNote: "표본 부족 (5회 미만) · 참고용",
    // OverallStats
    osAnalysis: "분석", osTabFights: "한타 통계", osWinBadge: "승", osLossBadge: "패", osAllAvg: "전체 평균",
    osTabSummary: "요약", osMapWinCard: "맵 승률", osSummaryBasisTpl: "{team} 기준", osTrendCard: "추세 (vs 이전 기간)",
    osTrendHint: "시작일을 설정하면 이전 기간 대비 추세가 표시됩니다", osTrendPrevTpl: "이전 {p} · {n}한타", osFightSampleTpl: "{w}/{n}한타",
    osSummaryEntryHeroes: "영웅별 통계 보기", osSummaryEntryMaps: "맵별 통계 보기", osSummaryEntryHint: "자세히 →",
    osTopHeroTpl: "많이 쓴 영웅: {hero}", osTopMapTpl: "많이 한 맵: {map}", osSecondaryMetrics: "선수 평균 지표 (기간·필터 기준)",
    osShowMore: "더보기", osShowingCountTpl: "{shown} / {total}", osSummaryNoData: "우리 팀 경기 데이터가 없습니다.",
    osNoMatchDataPre: "", osNoMatchDataPost: "의 경기 데이터가 없습니다", osNoFightData: "분석할 한타 데이터가 없습니다",
    osLostFightsSuffix: "회 패배 한타", osResistDescPre: "패배한 한타에서 상대를 ", osResistDescMid: "명 처치 → ", osResistDescPost: "% 처치율. 값이 높을수록 지면서도 교환을 잘 함.",
    osFirstDeathTop3: "퍼스트 데스 TOP 3", osFirstDeathLabel: "퍼스트 데스", osLostFightCarryTop3: "패배 한타 캐리 TOP 3", osNoMin10: "최소 10회 이상 참여 선수 없음",
    osKillsPerFight: "킬/한타", osTotalWord: "총 ", osKillUnit: "킬", osMin10Note: "* 최소 10회 이상 패배 한타 참여 기준",
    osMomentumNotePre: "* 매치 경계를 넘지 않음 · Draw 한타 제외 · 대상 매치: ", osMomentumNotePost: "경기", osEliminated: "사망", osKill: "킬",
    // 탭 재편: 궁극기 분석 / 킬데스 통계
    navUltAnalysis: "궁극기 분석",
    navKillDeath: "킬데스 통계",
    kdToggleFk: "퍼스트킬", kdToggleFd: "퍼스트데스",
    flUaTitle: "궁극기 분석",
    flUaDesc: "궁극기 상황별 승률과 콤보·시퀀스·응수를 분석합니다. 기준 팀 관점.",
    flUaTabSituation: "상황", flUaTabComboSeq: "콤보·시퀀스",
    // [교환 패턴]
    flPatTab: "교환 패턴",
    flPatUs: "아", flPatOpp: "적", flPatNone: "무궁",
    flPatChipUs: "아군", flPatChipOpp: "적군",
    flPatChipUsTip: "아군 궁", flPatChipOppTip: "적군 궁",
    flPatSumFights: "총 한타(판정 가능)", flPatSumKinds: "패턴 종류", flPatSumTop: "최빈 패턴",
    flPatColPattern: "패턴",
    flPatSecUs: "우리 선궁 패턴", flPatSecOpp: "상대 선궁 패턴",
    flPatSecSub: "소계: 표본 {n} · 승률 {w}",
    flPatHotTitle: "주목 패턴",
    flPatBarToggle: "승률 바",
    flPatTableNote: "패턴 = 궁 교환의 순서. 행을 클릭하면 실제 영웅 구성과 VOD가 표시됩니다.",
    flPatOppOther: "기타 {n}",
    flPatInsFirst: "선궁 시(첫 궁이 아군) 승률 {a} ({an}한타) vs 후궁 시 {b} ({bn}한타)",
    flPatInsLast: "마지막 궁이 우리일 때 승률 {a} ({an}한타) vs 상대일 때 {b} ({bn}한타)",
    flExpPat1: "패턴 표기(낱개): 한타의 전체 궁을 시간순으로 궁 하나 = 칩 하나로 나열합니다 — 파랑 배지 = 아군 궁, 빨강 배지 = 적군 궁(타임라인 뷰어와 동일한 팀 색), 궁 0개 한타는 '무궁'. 칩이 6개를 넘으면 앞 6칩 + '…'로 절단해 같은 패턴으로 묶습니다. 이 표의 역할은 궁 '교환의 순서'입니다 — 시간 묶음(콤보) 분석은 [콤보·시퀀스] 서브탭을 참조하세요.",
    flExpPat2: "정렬 규칙: 양팀이 정확히 같은 시각에 궁을 쓰면 우리 궁을 앞으로 정렬합니다(콤보/이니시 분석과 동일 규칙). 발생률·승률·표본은 모두 승패 판정 가능 한타 기준입니다. 표는 첫 칩 기준 [우리 선궁]/[상대 선궁] 섹션으로 나뉘며, 섹션 헤더의 소계 승률은 그 섹션 한타 전체의 가중 평균입니다.",
    flExpPat3: "Δ(vs 상대) = 이 패턴의 우리 승률 − 미러 패턴(아군↔적군 반전)의 상대 승률(= 1 − 그 패턴의 우리 승률). 예: [아군]→[적군]의 비교 대상은 [적군]→[아군]에서의 상대 승률입니다. 미러가 자기 자신인 대칭 패턴(무궁 포함)은 '—'로 표시합니다.",
    flExpPat4: "주의: 패턴 승률은 상관관계일 뿐 인과가 아닙니다 — 궁 개수 자체(투자량)의 효과와 순서의 효과가 섞여 있으니 표본과 함께 해석하세요.",
    flPatOnlyUlt: "궁 사용 한타만 보기",
    flExpPat5: "'궁 사용 한타만 보기'(기본 켬)는 무궁 한타를 표본에서 제외하며, 발생률·요약 숫자·추세도 그 모집단 기준으로 계산됩니다. 끄면 무궁 패턴이 표와 발생률 분모에 포함됩니다(인사이트 줄은 원래 궁 사용 한타만 대상이라 영향 없음).",
    flPatCompTitle: "구성 상위",
    flPatCompNotice: "표본이 작습니다 — 경향 참고용.",
    flPatCompCol: "구성",
    // [이니시]
    flInitTab: "이니시",
    flInitSumRate: "우리 선궁률 ({m}/{n}한타)",
    flInitSumUsWin: "선궁 시 승률 ({n}한타)",
    flInitSumThemWin: "후궁 시 승률 ({n}한타)",
    flInitOurTitle: "우리 이니시 궁",
    flInitOurDesc: "우리가 선궁한 한타를 첫 궁 영웅별로 집계합니다 — 어떤 궁으로 열 때 이기는가. 행 클릭 → 선수별 분해 + VOD.",
    flInitOppTitle: "상대 이니시 궁",
    flInitOppDesc: "상대가 선궁한 한타입니다. 승률은 우리 기준 — 낮을수록 그 이니시에 우리가 힘들었다는 뜻. 행 클릭 → 우리 3초 응수 상위 3 + VOD.",
    flInitColUlt: "이니시 궁", flInitColShare: "이니시 점유율", flInitColDelta: "Δ(vs 선궁 전체)",
    flInitColPlayer: "선수", flInitPlayersTitle: "누가 열었나 (선수별)",
    flInitRespTitle: "이 이니시에 대한 우리 3초 응수 상위 3",
    flInitRespNone: "3초 내 우리 응수가 있었던 한타가 없습니다.",
    flExpInit1: "선궁(이니시) = 한타에서 시간상 첫 번째 궁입니다. 판정은 교환 패턴의 첫 수 정의를 그대로 재사용합니다 — 양팀이 정확히 같은 시각에 궁을 쓰면 우리 궁을 앞으로 정렬(우리 선궁으로 집계). 모집단은 승패 판정 가능 + 궁 사용 한타이며, 무궁 한타는 요약·표 어디에도 포함되지 않습니다(교환 패턴 인사이트 줄과 동일 계산·동일 수치).",
    flExpInit2: "이니시 점유율 = 그 표(우리 선궁/상대 선궁) 안에서 해당 영웅이 첫 궁이었던 비율 — 표별 합 100%. Δ = 그 이니시 궁의 승률 − 그 표 전체(우리 선궁 전체 또는 상대 선궁 전체)의 우리 승률.",
    flExpInit3: "상대 이니시 표의 승률도 항상 우리 기준입니다(낮을수록 그 이니시가 우리에게 위협적). 행을 펼치면 나오는 응수 미니 표는 응수(카운터) 분석과 동일 계산(첫 사용 이후 3초 내 우리 궁, 동시각 제외, 한타당 가장 빠른 응수 1개)이며, 모집단만 '그 궁이 이니시였던 한타'로 좁힌 것입니다.",
    flExpInit4: "주의: 이니시 승률은 상관관계일 뿐 인과가 아닙니다 — 특정 궁으로 열었다는 것은 조합·전황이 이미 유리했다는 신호일 수 있으니 표본과 함께 해석하세요.",
    flExpPatComp: "구성(패턴 행 펼침의 미니 표): 그룹 기준은 '우리 궁 영웅(낱개 순서)'만입니다 — 상대 궁은 그룹 키에 넣지 않아 표본이 쪼개지지 않습니다(시점 전환 시 상대 구성 분석이 됨). 표시는 전체 시퀀스로: 우리 자리는 영웅명(파랑), 상대 자리는 그 그룹 한타들의 실제 상대 궁 빈도를 병기(빨강, 상위 2 + 기타 N)합니다. 예: '키리코 → 적(아나 2/라마트라 1) → 시그마'. 우리 궁이 없는 패턴(적군만)은 구성 표가 없습니다. 구성 행을 클릭하면 VOD 목록이 그 구성의 한타로 좁혀지고, 각 VOD 항목에 그 한타의 완전한 궁 시퀀스(아/적 + 영웅)가 한 줄로 표시됩니다.",
    // FightLabStats (한타 분석 베타)
    navFightLab: "한타 분석",
    flTitle: "한타 분석",
    flDesc: "한타 단위 상황별 승률을 기간별로 비교합니다. 기준 팀 관점.",
    flTabFights: "교전", flTabUlts: "궁극기", flTabUltSeq: "궁 콤보·시퀀스",
    flPresetAll: "전체", flPreset1w: "최근 1주", flPreset2w: "최근 2주", flPreset1m: "최근 1달", flPresetCustom: "직접 선택",
    flPresetAllBefore: "이전 전체", flPresetPrevSame: "직전 동일 기간",
    flMinSample: "최소 표본",
    flSideDate: "기간", flSideTrend: "추세 기간", flSideView: "시점", flSideOpp: "상대팀", flSideMap: "맵", flSideMin: "최소 표본", flSideFilter: "필터",
    flApply: "적용",
    flScopePeriod: "기간", flScopeTrend: "추세", flScopeView: "시점", flScopeOpp: "상대", flScopeMap: "맵", flScopeNone: "없음",
    flOverlapWarn: "최근 기간과 과거 기간이 겹칩니다. 표본이 중복 집계되므로 해석에 주의하세요.",
    flColSituation: "상황", flColOccur: "발생률", flColDOcc: "Δ발생률 (vs 상대)",
    flColWin: "승률", flColDWin: "Δ승률 (vs 상대)", flColSampleOne: "표본",
    flColTrend: "추세 (vs 과거)", flColStability: "안정성", flColStatus: "상태",
    flStabStable: "안정", flStabVolatile: "변동", flStatusOk: "제공",
    flUnitPp: "%p", flTipUs: "우리", flTipOpp: "상대",
    flLowSample: "표본 부족",
    flRecentShort: "최근", flPastShort: "과거",
    flCmpPastAll: "과거 전체", flCmpPrevPrefix: "직전 ",
    flVerdictImproved: "개선", flVerdictWorse: "악화", flVerdictSame: "유지",
    flPerspUs: "우리 시점", flPerspThem: "상대 시점",
    flPerspNotice: "상대 시점 — 표시된 승률·발생률·총평은 모두 상대팀 기준입니다. 상대 데이터는 우리 팀과의 스크림에서만 수집된 표본입니다.",
    // [선수] 서브탭
    flTabPlayers: "선수",
    flPbGroupPlayer: "선수별", flPbGroupPlayerHero: "선수+영웅별",
    flPbColPlayer: "선수", flPbGroupFight: "한타 지표", flPbGroupRound: "라운드 지표",
    flPbFights: "한타 수", flPbKp: "킬 관여율", flPbFk: "첫 킬/한타", flPbFd: "첫데스/한타",
    flPbUpf: "궁/한타", flPbUwin: "궁 사용 한타 승률", flPbKd: "K/D", flPbDmg10: "딜량/10분",
    flPbHeal10: "힐량/10분", flPbUlt10: "궁 수/10분",
    flPbPoolAvg: "풀평균", flPbPoolShortPre: "풀 부족(", flPbPoolShortPost: "명)",
    flPbTipSample: "표본",
    flPbRankTpl: "{n}명 중 {k}위",
    flPbRankShortTpl: "{k}위", flPbNoPool: "풀 부족",
    flPbRankRoleTpl: "{role} {k}위",
    flPbRoleTank: "탱커", flPbRoleDps: "딜러", flPbRoleSup: "지원",
    flPbTipVsPast: "과거 대비",
    flPbColSignals: "시그널",
    flPbSigTopSuffix: " 상위", flPbSigLowSuffix: " 주의",
    flPbGroupLabel: "그룹 기준", flPbSortLabel: "정렬 기준", flPbSortName: "선수명",
    flPbUnitFight: "한타", flPbUnitRound: "라운드",
    flPbPDashSample: "순위 없음: 본인 표본이 풀 최소 기준(한타 20 / 라운드 10) 미달",
    flPbFootnote: "각 셀은 값, 추세 화살표(과거 대비), (괄호 = 같은 역할 풀(우리+상대) 내 순위)입니다. 셀에 마우스를 올리면 풀 인원 등 상세가 표시됩니다. 순위가 무의미하면 (—) 또는 (풀 부족)으로 표기합니다.",
    flPbPoolTpl: "{role} 풀: 우리 {us}명 + 상대 {them}명",
    flPbPoolWarn: "※ 순위는 우리 팀과의 스크림에서 수집된 데이터 기준입니다. 상대 선수 수치는 우리 팀전 한정 표본이며, 풀이 작을 경우 순위가 크게 요동칠 수 있습니다.",
    flPbExpSrc: "지표는 두 출처를 씁니다 — [한타 지표]는 킬·궁 이벤트 기반(교전/궁극기 탭과 동일 데이터), [라운드 지표]는 라운드 요약표(개인 통계 탭과 동일 데이터) 기반이라 서로 기준이 다를 수 있습니다.",
    flPbExpFights: "한타 수: 본인이 출전한 라운드에서 발생한 우리 팀의 한타 수.",
    flPbExpKp: "킬 관여율: 팀 킬이 1개 이상 나온 한타에서 (본인 킬 ÷ 팀 킬)의 평균.",
    flPbExpFkFd: "첫 킬/한타·첫데스/한타: 한타의 첫 킬을 본인이 낸 / 본인이 당한 비율. 첫데스는 낮을수록 좋으며 화살표·팀평균 색·순위 방향이 모두 반전됩니다.",
    flPbExpAxes: "셀 읽는 법: '값 ↑ (5위)' 한 줄 — 값은 현재 기간, 화살표는 자기 과거(추세 기간) 대비(첫데스 등 반전 지표는 색 반전, 변화 없음은 →), 괄호 = 같은 역할 풀(우리+상대) 내 공동 순위(동점은 순위 공유, 반전 지표는 좋은 방향 기준 1위). 마우스를 올리면 풀 인원(예: 13명 중 5위)·과거 대비 변화·표본·풀평균 대비·풀 구성이 표시됩니다. 시그널의 상·하위 20% 판정도 이 등수÷인원 기준입니다.",
    flExpSidebar: "왼쪽 사이드바에서 기간·추세 기간·시점·상대팀/맵·최소 표본을 설정한 뒤 '적용'을 눌러야 반영됩니다. 기간을 '전체'로 선택하면 비교(Δ·화살표)가 표시되지 않습니다.",
    flPbExpSignals: "시그널: 풀 인원이 충족된 지표에서 상위 20% 이내면 초록(강점), 하위 20% 이내면 빨강(주의). 반전 지표는 반전 방향 기준입니다. 선수당 최대 2개(주의 우선)이며 표시 전용 — 총평에는 집계되지 않습니다.",
    flPbExpPool: "순위 풀은 상대팀/맵 필터와 무관하게 '최근 기간 전체 데이터' 기준입니다(필터로 풀이 줄어 순위가 무의미해지는 것 방지). 최소 표본: 한타 지표 20한타 / 라운드 지표 10라운드. 풀이 8명 미만이면 '풀 부족'으로 표시합니다.",
    flPbExpHeal: "힐량/10분은 힐러(지원)만 표시합니다. 10분당 환산은 출전 라운드의 duration 합 기준이며, duration이 없는 라운드는 표본에서 제외합니다.",
    // 순위표(리더보드)
    flLbTitle: "순위표",
    flLbMetric: "지표", flLbRole: "역할",
    flLbColRank: "순위", flLbColTeam: "소속", flLbColValue: "값",
    flLbUnranked: "순위 외 (표본 부족)",
    flLbSupportOnly: "이 지표는 지원 역할만 집계됩니다 — 역할을 '지원'으로 선택하세요.",
    flLbPoolWarnTpl: "풀이 {n}명으로 최소 기준({min}명) 미만입니다 — 순위는 참고용입니다.",
    flPbExpLb: "순위표: 셀 괄호의 '(지원 3위)'와 동일한 풀(최근 기간 전체 데이터 · 우리+상대 · 같은 역할 · 최소 표본 충족)과 동일한 공동 순위 규칙을 표로 펼친 것입니다. 상대팀/맵 필터와 무관하게 기간 전체 기준이며(기존 풀 규칙), 반전 지표(첫데스 등)는 좋은 값이 1위입니다. 표본 미달 선수는 하단에 '순위 외'로 값만 표시됩니다.",
    flRowFirstPick: "퍼스트 킬", flRowFirstDeath: "퍼스트 데스",
    flRowFdTank: "탱커 퍼스트 데스", flRowFdDamage: "딜러 퍼스트 데스", flRowFdSupport: "힐러 퍼스트 데스", flRowFdOther: "기타 퍼스트 데스",
    flRowFkTraded: "퍼킬 내고 트레이드 당함", flRowFdTraded: "퍼뎃 트레이드 성공",
    flRowUltUsed: "궁 사용 한타", flRowFirstUlt: "선궁 (우리가 먼저)", flRowEnemyFirstUlt: "상대 선궁",
    flRowUltAdv: "궁 우위", flRowUltDis: "궁 열세", flRowUltEven: "궁 동수 (양쪽 1개 이상)",
    flRowUlt1: "궁 1개 투자", flRowUlt2: "궁 2개 투자", flRowUlt3: "궁 3개 이상 투자",
    flSumAvgUlt: "한타당 평균 궁 투자 (우리)", flSumUltConv: "궁 전환율 (궁 사용 한타 승률)",
    flUnknownNotePre: "승자 판정 불가 한타(양팀 생존자 동수 = 무승부 처리): ",
    flUnknownNotePost: " — 발생률 분모에는 포함되지만 승률 표본에서는 제외됩니다.",
    flExplainTitle: "지표 설명",
    flExpWinner: "한타 승패: 한타 종료 시 생존자가 더 많은 팀이 승리로 판정됩니다. 생존자가 같으면(무승부) 승률 집계에서 제외됩니다.",
    flExpTwoCols: "각 행에는 성격이 다른 두 숫자가 있습니다 — 그 상황이 얼마나 자주 벌어지는지는 '발생률' 열, 그 상황에 놓였을 때 한타를 이겨내는 능력은 '승률' 열입니다. 행 이름의 (승률)은 승률 열 기준이라는 뜻입니다.",
    flExpOccur: "발생률·승률: 현재 기간의 우리 값입니다. Δ열(vs 상대)은 같은 한타들에서 상대편의 대칭 상황 수치와의 차이입니다 — 예: 첫 킬 획득 행의 Δ발생률 = 우리 첫 킬 획득률 − 상대 첫 킬 획득률(=우리 첫데스율). '낮을수록 좋은' 상황은 색 반전, ±1%p 미만은 회색입니다. 셀에 마우스를 올리면 우리/상대 원값이 표시됩니다.",
    flExpFirstPick: "퍼스트 킬: 한타의 첫 킬을 우리가 낸 경우. 발생률(높을수록 좋음)은 첫 킬을 따내는 빈도, 승률은 첫 킬을 따낸 한타를 실제로 이겼는지입니다.",
    flExpFirstDeath: "퍼스트 데스: 한타의 첫 킬을 우리가 당한 경우. 발생률(낮을수록 좋음)은 먼저 잘리는 빈도, 승률은 그럼에도 한타를 뒤집은 비율입니다.",
    flExpFdRole: "탱커/딜러/힐러 퍼스트 데스: 우리 퍼스트 데스 중 죽은 선수의 영웅 역할별 분해. 발생률(낮을수록 좋음)은 '우리 퍼스트 데스' 안에서 그 역할이 차지하는 비중, 승률은 그 상황에서의 한타 승률입니다.",
    flExpFkTraded: "퍼킬 내고 트레이드 당함: 우리가 첫 킬을 낸 뒤 5초 안에 상대에게 킬을 되돌려받은 경우. 발생률(낮을수록 좋음)은 첫 킬 이득을 헌납하는 빈도, 승률은 그렇게 트레이드된 한타를 그래도 이겼는지입니다. 승률이 오르는 것은 좋은 신호이며, 트레이드가 잦아졌다는 뜻이 아닙니다.",
    flExpFdTraded: "퍼뎃 트레이드 성공: 우리가 첫데스를 당한 뒤 5초 안에 우리도 킬로 되갚은 경우. 발생률(높을수록 좋음)은 불리한 시작을 만회하는 빈도, 승률은 되갚은 한타를 실제로 이겼는지입니다.",
    flExpUltUsed: "궁 사용 한타: 우리가 궁극기를 1개 이상 쓴 한타. 이 행의 승률이 곧 '궁 전환율'입니다.",
    flExpFirstUlt: "선궁/상대 선궁: 한타에서 첫 궁극기를 어느 팀이 먼저 썼는가. 발생률 분모는 '어느 쪽이든 궁이 나온 한타'입니다.",
    flExpUltCount: "궁 우위/열세/동수: 그 한타에서 우리가 상대보다 궁을 많이/적게/같게 쓴 경우입니다.",
    flExpUltInvest: "궁 1·2·3개 이상 투자: 우리가 그 한타에 쓴 궁 개수별 승률. 적게 쓰고 이길수록 효율적입니다.",
    flExpDryFight: "드라이 파이트(궁을 보유하고도 쓰지 않은 한타)는 궁 게이지 데이터 부재로 미제공됩니다.",
    flExpTrend: "추세(vs 과거) = 최근 승률 − 과거 승률. ↑초록=개선, ↓빨강=악화, ±1%p 미만은 →(유지)입니다. 총평(개선/악화/유지)은 이 추세(과거 대비) 기준이며 Δ열(상대 대비)은 총평에 포함되지 않습니다. 추세 셀에 마우스를 올리면 과거→최근 원값이 표시됩니다.",
    flExpSample: "표본: 현재 기간 승률 계산에 쓰인 한타 수. 과거 표본은 행 툴팁에서 확인합니다. 최소 표본 미만 행은 흐리게 표시되고 상태 열에 '표본 부족'으로 표기됩니다.",
    flExpStability: "안정성: 현재·과거 표본이 모두 (최소 표본 × 4) 이상이면 '안정', 아니면 '변동'입니다. 변동 행의 추세는 표본이 작아 크게 출렁일 수 있으니 참고용으로만 보세요.",
    // 궁극기 콤보 분석
    flCmbTitle: "궁극기 콤보 분석",
    flCmbRoleFilter: "역할 필터",
    flCmbGroupBy: "그룹 기준",
    flCmbGroupPH: "선수+영웅", flCmbGroupH: "영웅만",
    flCmbSize: "콤보 크기", flCmbWindow: "콤보 간격(초)", flCmbTopK: "Top-k", flCmbMinSample: "최소 콤보 표본",
    flCmbGenerate: "콤보 생성",
    flCmbTopTitle: "상위 콤보", flCmbBottomTitle: "하위 콤보",
    flCmbColCombo: "콤보", flCmbColRoles: "역할", flCmbColAvgInvest: "평균 궁 투자",
    flCmbPrompt: "'콤보 생성'을 누르면 현재 사이드바 필터(기간·시점·상대·맵) 기준으로 집계합니다.",
    flCmbEmpty: "조건에 맞는 콤보가 없습니다.",
    flCmbNote: "승률은 현재 기간 기준이며, 추세는 추세 기간의 동일 콤보 승률 대비입니다. 표본 부족 콤보는 흐리게 표시되고 표본 충족 콤보보다 위로 올라가지 않습니다.",
    flExpCombo1: "궁극기 콤보: 우리(현재 시점 팀) 궁들의 '시간 연쇄'입니다 — 직전 우리 궁으로부터 콤보 간격(기본 3초) 이내에 이어 쓴 궁이 같은 콤보 체인으로 묶입니다. 두 우리 궁 사이에 상대 궁이 끼면 체인이 끊기고(뒤 궁은 콤보가 아니라 응수 — 아래 응수 분석 참조), 단독으로 쓴 궁은 콤보가 아닙니다. 승률·평균 궁 투자는 그 콤보가 나온 한타 기준이며, 두 값 모두 승패 판정 가능 한타(무승부 제외) 기준입니다.",
    flExpCombo2: "부분조합 집계: 체인에 콤보 크기보다 많은 궁이 있으면 체인 멤버에서 크기 N의 모든 부분조합을 각각 셉니다(체인이 시간 근접을 보장) — 예: 3궁 체인은 크기 2 콤보 3개로 집계되어 한 한타가 여러 콤보에 중복 포함됩니다.",
    flExpCombo3: "주의: 콤보 승률은 상관관계일 뿐 인과가 아닙니다 — 특정 맵·상대·전황에서만 나오는 콤보일 수 있으니 표본 수와 함께 해석하세요.",
    // 궁극기 시퀀스 분석
    flSeqTitle: "궁극기 시퀀스 분석",
    flSeqStep1: "1단계 — 첫 궁 선택", flSeqStep2: "2단계 — 후속 궁",
    flSeqStep3: "3단계 — 두 번째 궁", flSeqStep4: "4단계 — 궁 상호작용",
    flSeqSide: "측", flSeqSideOur: "우리", flSeqSideOpp: "상대",
    flSeqHero: "영웅", flSeqUltWord: "궁", flSeqRespWin: "응수 창(초)",
    flSeqAnalyze: "분석", flSeqAnalyze2: "상호작용 분석",
    flSeqNoData: "선택한 궁이 나온 승패 판정 가능 한타가 없습니다.",
    flSeqSummaryTpl: "{n}한타 · 승률 {win} · Δ(vs 상대) {d} · 추세 {trend}",
    flSeqTopCounters: "카운터 (상대 후속)", flSeqTopFollowups: "우리 후속",
    flSeqColFollow: "후속 궁", flSeqColSeqRate: "시퀀스율", flSeqColDWin: "Δ승률", flSeqColReact: "평균 반응시간",
    flSeqNote: "승률은 항상 우리(현재 시점) 기준 한타 승률입니다. 표본 부족 행은 흐리게 표시되고 승률순으로 승격되지 않습니다.",
    flSeqPrefill: "후속에서 선택", flSeqManualOpt: "(직접 선택)",
    flSeqSecondLabel: "두 번째 궁",
    flSeqPickSecond: "두 번째 궁을 선택하고 '상호작용 분석'을 누르세요.",
    flSeqSameWarn: "첫 궁과 두 번째 궁이 같습니다 — 다른 궁을 선택하세요.",
    flSeqDiffWord: "차이",
    flSeqStep4Note: "승률은 우리(현재 시점) 기준 한타 승률이며, Δ승률은 현재 스코프 전체 한타 승률 대비 차이입니다. 승률 차이는 상관관계이며 인과관계가 아닙니다.",
    flExpSeq1: "궁극기 시퀀스: 선택한 궁이 나온 한타에서, 그 궁의 첫 사용 시각보다 '이후'(초과) 응수 창(기본 3초) 이내에 사용된 궁을 후속 궁으로 집계합니다. timestamp가 같으면(동시 사용) 후속으로 세지 않습니다 — 동시 콤보는 위 콤보 분석 영역입니다. 표본·시퀀스율·반응시간 모두 승패 판정 가능 한타(무승부 제외) 기준입니다.",
    flExpSeq2: "시퀀스율 = 그 후속이 나온 한타 수 ÷ 선택 궁이 나온 전체 한타 수. 평균 반응시간 = 선택 궁 → 후속 궁(각 한타 내 첫 사용 기준) 시간차의 평균. 2단계 Δ승률은 '선택 궁 전체 승률' 대비, 4단계 Δ승률은 '현재 스코프 전체 한타 승률' 대비 차이입니다.",
    flExpSeq3: "카운터: 선택 궁 이후 나온 상대 후속 궁 중 우리 승률이 가장 낮은 궁 — 상대가 이 궁으로 응수할 때 우리가 자주 진다는 뜻입니다. 다만 승률 차이는 상관관계일 뿐 인과가 아니므로 표본 수와 함께 해석하세요.",
    // 해당 장면 VOD 목록
    flVodMore: "더 보기", flVodReact: "응수",
    flExpVod: "행을 클릭하면 해당 한타 VOD 목록이 열립니다. 영상은 한타 시작 약 12초 전부터 재생됩니다.",
    // 궁극기 응수(카운터) 분석
    flCtrTitle: "궁극기 응수(카운터) 분석",
    flCtrDesc: "상대 궁이 열렸을 때 우리가 어떤 궁으로 응수하면 승률이 높았는지 — 상대 궁별 검증된 해법 목록입니다. 행을 클릭하면 응수 궁 전체가 펼쳐집니다.",
    flCtrOverviewTitle: "상대 주요 궁 개요",
    flCtrColEnemyUlt: "상대 궁", flCtrColWinWith: "그때 우리 승률", flCtrColNoResp: "무응수 시 승률",
    flCtrColBest: "최고 응수 궁", flCtrColBestWin: "응수 시 승률", flCtrColBestN: "응수 표본",
    flCtrColResp: "우리 응수 궁", flCtrColRespRate: "응수율", flCtrColDNo: "Δ(무응수 대비)",
    flCtrNote: "승률 차이는 상관관계이며 인과가 아닙니다. 표본이 작은 응수는 참고만 하세요.",
    flExpCtr1: "응수: 상대 궁의 첫 사용 이후(초과) 응수 창(기본 3초) 이내에 우리가 쓴 모든 후속 궁(첫 후속 포함) — 시퀀스 분석의 후속 규칙과 동일하며 같은 계산을 재사용합니다.",
    flExpCtr2: "무응수 = 그 상대 궁 이후 응수 창(기본 3초) 내에 우리 궁이 하나도 없던 한타. Δ(무응수 대비) = 그 응수가 나온 한타의 승률 − 무응수 한타의 승률로, '응수의 가치'를 직접 보여줍니다. 최고 응수 궁은 최소 표본을 충족한 응수 중 승률 1위입니다(충족 후보가 없으면 표본 부족).",
    flExpCtr3: "한 한타에 우리 응수가 여러 개면 각각의 응수에 모두 집계됩니다 — 따라서 응수율의 합이 100%를 넘을 수 있고, 무응수율과 단순 합산되지 않습니다.",
    flExpWindows: "시간 창 기준 통일: 콤보는 콤보 간격(기본 3초) 내 '아군 궁 연쇄'(시너지), 응수/시퀀스는 응수 창(기본 3초) 내 '상대(또는 선택) 궁에 대한 즉각 반응'입니다. 두 창은 별개 설정으로 각각 조정할 수 있습니다.",

    // ── 맵 분석 탭 ──
    navMapAnalysis: "맵 분석",
    maTitle: "맵 분석",
    maDesc: "어떤 맵·맵 타입에 강하고 약한지 — 맵 선택과 밴픽 판단의 근거가 되는 실측 데이터입니다.",
    maSummaryOverall: "전체 맵 승률", maSummaryBest: "최강 맵 타입", maSummaryWorst: "최약 맵 타입",
    maSummaryNone: "표본 충족 타입 없음",
    maTypeTitle: "맵 타입 요약",
    maTypeHint: "행을 클릭하면 그 타입에 속한 맵별 통계가 펼쳐집니다.",
    maMapsTitle: "맵별 상세",
    maMapsHint: "행을 클릭하면 그 맵의 매치 목록이 펼쳐집니다. 플레이율 내림차순 정렬.",
    maWeeklyTitle: "주별 추이",
    maColType: "맵 타입", maColMap: "맵", maColPlayRate: "플레이율", maColMapWin: "맵 승률",
    maColFightWin: "한타 승률", maColDelta: "Δ (vs 상대)", maColTrend: "추세 (vs 과거)",
    maColTopHeroes: "Top 영웅", maColStatus: "상태",
    maCellPlayTpl: "{p} ({n}맵)", maCellWinTpl: "{p} ({w}승)",
    maMlDate: "날짜", maMlOpp: "상대", maMlScore: "스코어", maMlResult: "결과", maMlLink: "세션 상세",
    maMlOpen: "이동 →",
    maResultWin: "승", maResultLoss: "패", maResultDraw: "무", maResultUnknown: "미기록",
    maTopHeroNone: "표본 부족",
    maWeeklyRowAll: "전체",
    maWeeklyMetricFight: "한타 승률", maWeeklyMetricMap: "맵 승률", maWeeklyMetricPicks: "픽 횟수",
    maWeekLabelTpl: "{m}월 {n}주차",
    maWeekDetailTpl: "{label} 상세 ({range} · 총 {n}맵)",
    maColPicks: "픽 수",
    maWlDrawTpl: "{w}승 {l}패 {d}무",
    maPushTip: "미보정 밀기 매치는 무승부로 집계됩니다.",
    maCorrected: "보정",
    maWeeklyCellTipTpl: "{range} · {metric} {p} · {w}승 / 표본 {n}",
    maWeeklyPicksTipTpl: "{range} · 픽 {n}회",
    maWeeklyLowTipTpl: "{range} · 표본 {n}",
    maTipUsOppTpl: "우리 {a} vs 상대 {b}",
    maTipTrendTpl: "과거 {b} → 최근 {a}",
    // 지표 설명
    maExpMapWin: "맵 승률 = 매치(맵) 단위 승수 ÷ 결과가 기록된 매치 수(무승부는 분모에 포함, 결과 미기록 매치는 제외). 한타 승률 = 한타 단위 승수 ÷ 승자 판정 가능한 한타 수. 두 지표는 집계 단위가 다르므로 함께 읽어야 합니다.",
    maExpPlayRate: "플레이율 = 그 맵(타입)의 매치 수 ÷ 스코프 내 전체 매치 수. 한타 기록이 하나도 없는 매치는 데이터 특성상 집계에 포함되지 않습니다.",
    maExpDelta: "Δ(vs 상대) = 우리 한타 승률 − 상대 한타 승률(같은 한타들의 반대 시점). 추세(vs 과거) = 최근 기간 한타 승률 − 과거 기간 한타 승률(사이드바의 추세 기간 기준).",
    maExpTopHeroes: "Top 영웅은 근사치입니다 — 완전한 출전 영웅 데이터가 없어 \"그 맵에서 우리가 궁을 쓴 영웅\"이 포함된 한타의 승률로 계산합니다(영웅별 최소 {n}한타, 승률 내림차순). 궁을 쓰지 않은 출전은 잡히지 않으므로 참고용으로만 보세요.",
    maExpWeek: "주별 추이의 '주'는 월요일 시작(월~일)이며 최근 주가 오른쪽입니다. 주 라벨 '6월 4주차'는 그 주 월요일 기준 — 달은 월요일이 속한 달, 주차는 그 달의 몇 번째 월요일인지입니다(예: 6/23 월요일 주 = 6월 4주차). 주 헤더를 클릭하면 그 주에 픽한 맵별 상세가 열립니다. 승률 모드에서 그 주 표본이 없는 셀은 회색 \"—\", 픽 횟수 모드는 매치 수를 색 없이 표시합니다.",
    maExpPushFix: "밀기맵 특례: 밀기맵 로그에는 스코어가 없어 자동 판정이 무승부(0:0)로 저장됩니다. 스크림 세션 화면에서 수기 보정(승패 보정)된 매치는 보정된 승패로 집계되고, 미보정 매치만 무승부로 남습니다. 보정은 원본 기록과 분리 저장되어 언제든 되돌릴 수 있습니다.",
    maExpStatus: "표본 하한 없음 — 1경기 이상 플레이한 맵·타입은 모두 집계에 포함됩니다. 맵 승률 셀의 방향색(초록/빨강)은 50% 기준이며, 표본이 작은 행은 괄호의 표본 수와 함께 신중히 해석하세요. 상대팀 필터는 '상대 시점'에서만 표시됩니다(우리 시점 전환 시 자동 해제).",
    maExpCausal: "승률 차이는 상관관계일 뿐 인과가 아닙니다 — 상대 수준·조합·패치 등 맥락과 함께 해석하세요.",
    // 승패 보정 (밀기맵) — 스크림 생성 모달 전용
    woLabel: "승패 보정",
    woNone: "미보정",
    woWinSuffix: "승",
    woHint: "밀기맵은 로그에 스코어가 없어 자동 판정이 무승부로 저장됩니다. 실제 승리 팀을 선택하면 맵 분석·통계에 반영됩니다(원본 기록은 유지).",
    // 사후 승패 보정 배지·인라인 편집(매치 상세·세션 매치 목록)
    woBadgeDraw: "무승부 · 수기 판정",
    woBadgeOverridden: "수기 보정됨",
    woPick: "판정",
    woSaving: "저장 중…",
    woSaveFail: "보정 저장 실패"
  },
  en: {
    back: "Back", loading: "Loading data...", noData: "No data available.", add: "Add",
    dashboard: "Dashboard", sessions: "Sessions", overall: "Overall Stats", teamManage: "Team Manage (WIP)",
    navGroupStats: "Stats", navGroupAnalysis: "Analysis", navBanpick: "Ban/Pick",
    ssCalendar: "Calendar", ssList: "List",
    title: "Scrim Data Center", desc: "Upload Overwatch scrim logs to analyze team performance.", desc2: "Data is safely stored on the server.",
    createScrim: "Create Scrim", viewHistory: "View History", uploading: "Uploading...",
    modalTitle: "Create Scrim Record", step1Title: "Basic Information", step1Desc: "Please enter the scrim date and time.",
    scrimName: "Scrim Name", scrimNamePlace: "ex: 2024-05-20 vs Opponent Scrim", videoUrl: "Video URL",
    date: "Date", time: "Time", next: "Next", prev: "Prev", save: "Save", success: "Scrim saved successfully!",
    backToList: "Back to List", totalDuration: "Total Duration", roundScore: "Round Score",
    finalBlows: "Final Blows", fightWins: "Fight Wins", ultEconomy: "Ult Economy", lowerBetter: "Lower is better",
    lead: "Lead", draw: "Draw", win: "Win", tabStats: "Stats", tabKillLog: "Kill Log", tabChart: "Charts",
    tabEvent: "Events", tabPlayer: "Player Stats", totalCumulative: "Total (Cumulative)", round: "Round",
    fightSurvivors: "Survivors per Fight", survivors: "Alive", duration: "Dur", avgSurvivors: "Avg Survivors",
    firstBloodAnalysis: "First Blood Analysis", standard: "Perspective", situation: "Situation", fightCount: "Fights",
    winRate: "Win Rate", fbSecured: "First Kill Secured", fbSuffered: "First Death Suffered", ultsPerFight: "Ults per Fight",
    fbByRole: "Final Blows by Role", cumulativeDmg: "Cumulative Dmg by Round", dmgEfficiency: "Damage Efficiency",
    heroDmgDealt: "Hero Damage Dealt", battery: "Trash Damage", carry: "Carry", role: "Role",
    player: "Player", team: "Team", playTime: "Time", elims: "Elims", deaths: "Deaths", assists: "Assists",
    heroDmg: "Hero Dmg", barrierDmg: "Barrier Dmg", healRcvd: "Heal Rcvd", dhRatio: "D/H Ratio", healing: "Healing",
    dmgTaken: "Dmg Taken", ults: "Ults", fight: "Fight", noEvents: "No events.", noUlts: "No ultimates recorded.",
    events: "Events", ultimatesUsed: "Ultimates Used", pickRate: "Pick Rate", soloKills: "Solo Kills", ultUsage: "Ultimates Used",
    per10: "/ 10m", tank: "Tank", dps: "DPS", support: "Support",
    filterPlaceholder: "Filter (ex: Lijiang, Lucio, Win...)", filterTip: "Use filters (Player, Map, Hero) for detailed analysis.",
    searchedGames: "Searched Games", avgWinRate: "Avg Win Rate", avgKills: "Avg Kills", avgDeaths: "Avg Deaths", avgDmg: "Avg Dmg",
    tabHighlights: "Highlights & Summary", tabHeroes: "Hero Stats", tabMaps: "Map Stats", highlights: "Highlights",
    noMoments: "No moments found matching conditions.", heroStatsTitle: "Hero Stats (Filtered)", mapStatsTitle: "Map Stats",
    hero: "Hero", gamesPlayed: "Games", kda: "KDA",
    dateFilter: "Date Range", startDate: "Start Date", endDate: "End Date", allDates: "All Time",
    ultStatsTitle: "Ultimate Value & Fight Analysis", ultCountVsWin: "Fight Win Rate by Ult Count", ultEfficiency: "Ultimate Efficiency (by Win Rate)",
    ultUses: "Uses",
    baseTeam: "Base Team", allTeams: "All Teams",
    matchStart: "Game Start Time", matchEnd: "Game End Time",
    objectiveCaptured: "Objective captured", flNoDataInPeriod: "No scrim data in the selected period (last scrim: {date})", flShowAllPeriod: "Show all time",
    matchStartTip: "Video timestamp when countdown ends (setup_complete)",
    navUltimateStats: "Ultimate Stats", navFirstKill: "First Kill Stats", navFirstDeath: "First Death Stats", navFirstFight: "First Fight", navPersonal: "Personal Stats",
    ffTitle: "First Fights", ffDesc: "Jump straight to the first engagement of each map/round. (Control/Escort/Hybrid: per round, Flashpoint/Push: one per match)",
    ffAllOpponents: "All Opponents", ffAllMaps: "All Maps", ffColDate: "Date", ffColMap: "Map", ffColRound: "Round", ffColMatchup: "Matchup", ffColTime: "Fight Time", ffColLink: "Video",
    ffWatch: "Watch", ffNoVideo: "No video", ffLoading: "Loading…", ffError: "Failed to load data.",
    // FirstKillStats
    fkTitle: "First Kill Stats", fkDesc: "Detailed breakdown of fight-opening carry potential, top victims, and abilities used.",
    allPositions: "All Roles", matchup: "Matchup:", myTeamAll: "My Team (All)", enemyTeamAll: "Enemy Team (All)",
    position: "Role", fkColFights: "Teamfights", fkColCount: "First Kills", fkColRate: "First Kill %",
    timesUnit: "", fkTopVictims: "Top Victims (Player)", fkTopHeroes: "Targeted Heroes (Hero)", fkKillSkill: "Finishing Ability (on whom?)",
    noFilteredData: "No data matches the filter.",
    // FirstDeathStats
    fdTitle: "First Death Stats", fdDesc: "Detailed analysis of player survivability and who/what ability they died to first.",
    fdColCount: "First Deaths", fdColRate: "First Death %",
    fdNemesis: "Nemesis (Player)", fdWatchHeroes: "Threat Heroes (Hero)", fdDeadlySkill: "Deadly Ability (hit by whom)",
    // PlayerProfileView
    all: "All", ppNoPlayers: "No player data available.", ppRosterTitle: "Roster", ppSearchPlaceholder: "Search player...",
    ppOverallKd: "Overall K/D", ppDmgPer10: "Damage / 10min", ppHealPer10: "Healing / 10min", ppUltPerMatch: "Ults / Match",
    ppHeroPool: "Most Played Heroes", ppNoHeroes: "No hero play records.", ppRecentForm: "Recent K/D Form",
    ppSelectPrompt: "Select a player from the list on the left.",
    // PlayerCompareView
    navCompare: "Compare Players",
    pcRosterTitle: "Select Players", pcSelectHint: "Pick 2 or more players", pcSelectedCount: " selected",
    pcSelectPrompt: "Select at least 2 players to compare.",
    pcMetricCompare: "Metric Comparison", pcScopeLabel: "Scope", pcScopeAll: "All (Overall)",
    pcRadarTitle: "Overall Stats (Relative)", pcRadarHint: "Scaled to 100% of the best value among selected players",
    pcHeroCompare: "Hero Comparison", pcSelectHeroLabel: "Select hero:", pcNoHeroRecord: "No record",
    pcHeroPlayTime: "Play Time", pcBest: "Best", pcMetricKd: "K/D", pcMetricWinRate: "Win Rate",
    pcHeroUltEff: "Kills per Ult", pcHeroUltWin: "Ult Fight Win%", pcHeroUltGames: "tf", pcHeroUltUses: "ult", pcHeroUltCharge: "Avg Ult Charge", pcSecUnit: "s", pcHeroImpact: "Impact (Elim/10)",
    pcMetricDmg: "Dmg / 10min", pcMetricHeal: "Heal / 10min", pcMetricUlt: "Ults / Match", pcMin: "min",
    pcMetricMitig: "Mitigated / 10min", pcMetricFb: "Final Blows / 10min", pcMetricSecondaryMixed: "Secondary / 10min",
    pcTagHeal: "Heal", pcTagMitig: "Mitig.", pcTagFb: "FB",
    // MatchStats
    msNoFights: "No recorded fights (kills).", msUltEffWin: "Efficient Win (fewer ults)", msUltSaveLoss: "Lost While Saving Ults", msUltOverInvest: "Over-Investment (2+ excess)",
    msLostFightTitle: "Resistance in Lost Fights (Kill Exchange)", msAvgKillRateOnLoss: "Avg Enemy Kill Rate on Loss",
    msAvgWord: "avg ", msKillsUnit: " kills", msLossUnit: " losses", msResistKills: "Resist Kills",
    msMomentumTitle: "Teamfight Momentum (Streaks & Turnovers)", msWinRateAfterWin: "Win Rate After Winning", msWinToWin: "(Win ➔ Win)", msSnowball: "Snowballing ability",
    msWinRateAfterLoss: "Win Rate After Losing", msLossToWin: "(Loss ➔ Win)", msComeback: "Comeback ability",
    msFirstDeathAnalysis: "First Kills & Individual Death Analysis", msFirstKillCountTeam: "First Kills (Team)", msFirstDeathRank: "First Death Ranking",
    msPlayerHero: "Player (Hero)", msFirstBloodDeaths: "First Deaths", msDeathCause: "Main Death Causes (hit by whose ability)", msNoDataShort: "No data",
    msUltSummary: "Ultimate Summary", msTotalUlts: "Total Ultimates Used", msFirstUltInFight: "Used Ult First in Fight", msUltTiming: "Ultimate Timing",
    msPhaseEarly: "Early (Initiation)", msPhaseMid: "Midfight", msPhaseLate: "Late", msUltExchange: "Ult Exchange & Over-Investment",
    msAvgConsumed: "Avg Consumed", msWonFight: "Won fights:", msLostFightLabel: "Lost fights:", msCountUnit: "",
    msNoVideo: "No video record for this match", msTabStats: "Stats Table", msTabKill: "Kill Log", msTabChart: "Analysis Charts", msTabTimeline: "Timeline", msTabCompare: "Player Comparison",
    // Ult Timeline subtab
    msTabUltTl: "Ult Timeline",
    msUltTlNote: "Ultimate flow per fight. +X.Xs next to each ult is relative to the fight's first ultimate; video links start about 12 seconds before the fight begins.",
    msUltTlFight: "Fight", msUltTlWinner: "Winner", msUltTlDraw: "Undecided", msUltTlNoUlt: "No ultimates used",
    // Match detail summary card / round tabs / event labels (i18n)
    msBackToOverview: "Back to Overview", msTotalTime: "Total Match Time", msScoreLabel: "Score", msWinnerLabel: "Winner",
    msFinalBlows: "Final Blows", msFightWins: "Fight Wins", msUltEconomy: "Ult Economy",
    msOverview: "Overview", msRoundLabel: "Round {n}",
    msMultiKill: "Multi Kill", msTeamKill: "Team Kill", msKillsUnit: " Kills",
    // Session list / scrim detail (i18n)
    matchCount: "{n} matches", sdMatchList: "Match List", sdResult: "Result", sdAnalyze: "Analyze", sdUnknown: "Unknown",
    // Common (buttons / delete dialogs)
    delete: "Delete", reset: "Reset", cancelSelection: "Cancel", selectAll: "Select All", deselectAll: "Deselect All",
    selectedCount: "selected", deleting: "Deleting...", deleteSelected: "Delete Selected", deleteConfirmPre: "Delete ",
    sdIrreversible: "This action cannot be undone.", sdDeleteDone: "Deleted", sdWarnings: "Warnings:",
    sdPartialFail: "Partial delete failure: ", sdDeleteFail: "Delete failed: ", sdDeleteMatchPost: " selected matches?",
    ssDeleteSessionMid: " selected sessions?\nThis will also delete a total of ", ssDeleteSessionPost: " included matches.",
    ssRebuildConfirm: "Rebuild DB?",
    // ScrimModal
    smCloseConfirm: "Your input will be lost. Close anyway?", smEnterName: "Please enter a scrim name.", smMinOneMatch: "Please record at least one match.",
    smMatchPre: "Match ", smMatchPost: ": ", smPauseSelectedWarn: "You selected 'Has Pause'. Add a pause range or select 'No'.",
    smPauseTimeWarn: "Enter both pause start/end times. (ex: 10:00)", smYoutubeLink: "YouTube Video Link", smOptional: "(Optional)",
    smTeam1Label: "Team 1 Name (Left)", smTeam2Label: "Team 2 Name (Right)", smStartPlaceholder: "ex: 03:30 (fight start)",
    // UltimateStats
    ultFivePlus: "5+", ultTotal: "Total", ultValue: "Value", ultLowSampleNote: "Low sample (under 5) · reference",
    // OverallStats
    osAnalysis: "Analysis", osTabFights: "Teamfight Stats", osWinBadge: "Win", osLossBadge: "Loss", osAllAvg: "All Avg",
    osTabSummary: "Summary", osMapWinCard: "Map win rate", osSummaryBasisTpl: "Based on {team}", osTrendCard: "Trend (vs previous period)",
    osTrendHint: "Set a start date to see the trend vs. the previous period", osTrendPrevTpl: "prev {p} · {n} fights", osFightSampleTpl: "{w}/{n} fights",
    osSummaryEntryHeroes: "View hero stats", osSummaryEntryMaps: "View map stats", osSummaryEntryHint: "Details →",
    osTopHeroTpl: "Most played: {hero}", osTopMapTpl: "Most played map: {map}", osSecondaryMetrics: "Player average metrics (by period · filter)",
    osShowMore: "Show more", osShowingCountTpl: "{shown} / {total}", osSummaryNoData: "No match data for our team.",
    osNoMatchDataPre: "No match data for ", osNoMatchDataPost: "", osNoFightData: "No teamfight data to analyze",
    osLostFightsSuffix: " lost fights", osResistDescPre: "Eliminated ", osResistDescMid: " enemies in lost fights → ", osResistDescPost: "% kill rate. Higher means better trades even in losses.",
    osFirstDeathTop3: "First Death TOP 3", osFirstDeathLabel: "First Death", osLostFightCarryTop3: "Lost Fight Carry TOP 3", osNoMin10: "No players with 10+ participations",
    osKillsPerFight: "kills/fight", osTotalWord: "", osKillUnit: " kills", osMin10Note: "* Based on 10+ lost fight participations",
    osMomentumNotePre: "* No match-boundary crossing · Draw fights excluded · Matches: ", osMomentumNotePost: " games", osEliminated: "eliminated", osKill: "kill",
    // Tab restructure: Ult Analysis / First Kill·Death
    navUltAnalysis: "Ult Analysis",
    navKillDeath: "First Kill·Death",
    kdToggleFk: "First Kill", kdToggleFd: "First Death",
    flUaTitle: "Ultimate Analysis",
    flUaDesc: "Win rates by ultimate situation plus combos, sequences and responses. From the base team's view.",
    flUaTabSituation: "Situations", flUaTabComboSeq: "Combos & Sequences",
    // [Exchange Patterns]
    flPatTab: "Exchange Patterns",
    flPatUs: "A", flPatOpp: "E", flPatNone: "no ults",
    flPatChipUs: "ALLY", flPatChipOpp: "ENEMY",
    flPatChipUsTip: "Our ultimate", flPatChipOppTip: "Enemy ultimate",
    flPatSumFights: "Fights (decidable)", flPatSumKinds: "Distinct patterns", flPatSumTop: "Most common",
    flPatColPattern: "Pattern",
    flPatSecUs: "We ult first", flPatSecOpp: "They ult first",
    flPatSecSub: "subtotal: {n} fights · {w} WR",
    flPatHotTitle: "Notable",
    flPatBarToggle: "WR bars",
    flPatTableNote: "Pattern = the ORDER of the ult exchange. Click a row to see actual hero compositions and VODs.",
    flPatOppOther: "other {n}",
    flPatInsFirst: "First ult ours: {a} WR ({an} fights) vs theirs first: {b} ({bn} fights)",
    flPatInsLast: "Last ult ours: {a} WR ({an} fights) vs theirs: {b} ({bn} fights)",
    flExpPat1: "Pattern notation (per-ult): all ultimates in a fight are listed chronologically, one chip per ult — blue badge = our ult, red badge = enemy ult (same team colors as the timeline viewer); fights with no ults are 'no ults'. Patterns longer than 6 chips are truncated to the first 6 + '…' and bucketed together. This table is about the ORDER of the exchange — for time-clustered combos see the [Combos & Sequences] subtab.",
    flExpPat2: "Ordering rule: when both teams ult at exactly the same timestamp, ours is ordered first (same rule as the combo/initiation analyses). Occurrence, win rate and samples all count only fights with a decidable winner. The table splits into [We ult first] / [They ult first] sections by the first chip; each section header's subtotal WR is the weighted average over all fights in that section.",
    flExpPat3: "Δ (vs opp) = this pattern's our win rate − the opponent's win rate in the MIRROR pattern (ally↔enemy swapped), which equals 1 − our win rate there. E.g. [ALLY]→[ENEMY] compares against the opponent's win rate in [ENEMY]→[ALLY]. Self-mirror (symmetric) patterns, including 'no ults', show '—'.",
    flExpPat4: "Caution: pattern win rates are correlation, not causation — the effect of ult COUNT (investment) is mixed with the effect of ORDER, so always read them together with the sample size.",
    flPatOnlyUlt: "Ult fights only",
    flExpPat5: "'Ult fights only' (default on) excludes no-ult fights from the sample; occurrence rates, summary numbers and trends use that population. Turning it off includes the 'no ults' pattern in the table and denominators (the insight lines are unaffected — they already cover ult fights only).",
    flPatCompTitle: "Top compositions",
    flPatCompNotice: "Small samples — treat as directional only.",
    flPatCompCol: "Composition",
    // [Initiation]
    flInitTab: "Initiation",
    flInitSumRate: "Our first-ult rate ({m}/{n} fights)",
    flInitSumUsWin: "WR when we ult first ({n} fights)",
    flInitSumThemWin: "WR when they ult first ({n} fights)",
    flInitOurTitle: "Our initiating ultimates",
    flInitOurDesc: "Fights we opened, grouped by the first ult's hero — which ult wins fights when it opens. Click a row for the per-player breakdown + VODs.",
    flInitOppTitle: "Opponent initiating ultimates",
    flInitOppDesc: "Fights the opponent opened. Win rate is OURS — lower means that initiation hurts us. Click a row for our top 3 responses within 3s + VODs.",
    flInitColUlt: "Initiating ult", flInitColShare: "Initiation share", flInitColDelta: "Δ (vs all inits)",
    flInitColPlayer: "Player", flInitPlayersTitle: "Who opened (by player)",
    flInitRespTitle: "Our top 3 responses within 3s to this initiation",
    flInitRespNone: "No fights had a response from us within 3s.",
    flExpInit1: "Initiation = the chronologically first ultimate of a fight. The call reuses the exchange-pattern first-move definition as-is — when both teams ult at exactly the same timestamp, ours is ordered first (counted as our initiation). The population is decidable-winner fights WITH ults; no-ult fights are excluded everywhere (identical calculation and numbers as the exchange-pattern insight line).",
    flExpInit2: "Initiation share = within that table (our inits / opponent inits), the share of fights this hero opened — each table sums to 100%. Δ = this initiating ult's win rate − the table-wide win rate (all our inits, or all opponent inits, ours-basis).",
    flExpInit3: "The opponent table's win rate is also always OURS (lower = that initiation threatens us). The response mini table shown when expanding a row uses the same calculation as the Response (Counter) analysis (our ults within 3s AFTER the first use, simultaneous excluded, one fastest response per fight), only narrowing the population to fights where that ult was the INITIATION.",
    flExpInit4: "Caution: initiation win rates are correlation, not causation — opening with a certain ult may just signal an already-favorable comp or fight state, so read them together with sample sizes.",
    flExpPatComp: "Composition (the mini table inside an expanded pattern row): groups are keyed by OUR ult heroes only, in per-ult order — enemy ults are NOT part of the key, so samples stay intact (switching perspective turns this into the opponent's compositions). The display shows the full sequence: our slots as hero names (blue), enemy slots as the actual enemy-ult frequencies across that group's fights (red, top 2 + 'other N'), e.g. 'Kiriko → E(Ana 2/Ramattra 1) → Sigma'. Patterns with no our-ults have no composition table. Clicking a composition row narrows the VOD list to that composition's fights, and each VOD item then shows the fight's complete ult sequence (side + hero) on one line.",
    // FightLabStats (Fight Lab Beta)
    navFightLab: "Fight Lab",
    flTitle: "Fight Lab",
    flDesc: "Compares per-fight win rates by situation across periods. From the base team's view.",
    flTabFights: "Engagements", flTabUlts: "Ultimates", flTabUltSeq: "Ult Combos & Sequences",
    flPresetAll: "All Time", flPreset1w: "Last 1 Week", flPreset2w: "Last 2 Weeks", flPreset1m: "Last 1 Month", flPresetCustom: "Custom Range",
    flPresetAllBefore: "All Earlier", flPresetPrevSame: "Previous Same Length",
    flMinSample: "Min Sample",
    flSideDate: "Date filter", flSideTrend: "Trend window", flSideView: "Perspective", flSideOpp: "Opponent", flSideMap: "Map", flSideMin: "Min sample", flSideFilter: "Filter",
    flApply: "Apply",
    flScopePeriod: "Period", flScopeTrend: "Trend", flScopeView: "View", flScopeOpp: "Opp", flScopeMap: "Map", flScopeNone: "none",
    flOverlapWarn: "The recent and past periods overlap. Samples are double-counted — interpret with care.",
    flColSituation: "Situation", flColOccur: "Rate", flColDOcc: "Δ rate (vs opp)",
    flColWin: "Win rate", flColDWin: "Δ win (vs opp)", flColSampleOne: "Sample",
    flColTrend: "Trend (vs past)", flColStability: "Stability", flColStatus: "Status",
    flStabStable: "stable", flStabVolatile: "volatile", flStatusOk: "available",
    flUnitPp: " pp", flTipUs: "us", flTipOpp: "opp",
    flLowSample: "Low sample",
    flRecentShort: "Recent", flPastShort: "Past",
    flCmpPastAll: "All past", flCmpPrevPrefix: "previous ",
    flVerdictImproved: "Improved", flVerdictWorse: "Worse", flVerdictSame: "Unchanged",
    flPerspUs: "Our View", flPerspThem: "Opponent View",
    flPerspNotice: "Opponent view — all win rates, occurrence rates and the summary are from the opponents' side. Opponent data covers only scrims played against us.",
    // [Players] subtab
    flTabPlayers: "Players",
    flPbGroupPlayer: "By Player", flPbGroupPlayerHero: "By Player + Hero",
    flPbColPlayer: "Player", flPbGroupFight: "Fight Metrics", flPbGroupRound: "Round Metrics",
    flPbFights: "Fights", flPbKp: "Kill Part.", flPbFk: "FK / Fight", flPbFd: "FD / Fight",
    flPbUpf: "Ults / Fight", flPbUwin: "Ult Fight WR", flPbKd: "K/D", flPbDmg10: "Dmg /10min",
    flPbHeal10: "Heal /10min", flPbUlt10: "Ults /10min",
    flPbPoolAvg: "pool", flPbPoolShortPre: "small pool (", flPbPoolShortPost: ")",
    flPbTipSample: "Sample",
    flPbRankTpl: "#{k} of {n}",
    flPbRankShortTpl: "#{k}", flPbNoPool: "small pool",
    flPbRankRoleTpl: "{role} #{k}",
    flPbRoleTank: "Tank", flPbRoleDps: "DPS", flPbRoleSup: "Sup",
    flPbTipVsPast: "vs past",
    flPbColSignals: "Signals",
    flPbSigTopSuffix: " — top 20%", flPbSigLowSuffix: " — bottom 20%",
    flPbGroupLabel: "Group player breakdown by", flPbSortLabel: "Sort by", flPbSortName: "Player",
    flPbUnitFight: " fights", flPbUnitRound: " rounds",
    flPbPDashSample: "no rank: player's own sample is below the pool minimum (20 fights / 10 rounds)",
    flPbFootnote: "Each cell is value, trend arrow (vs past window), and (parentheses = rank within the same-role pool of ours + opponents). Hover a cell for pool size and details. (—) or (small pool) is shown where a rank is not meaningful.",
    flPbPoolTpl: "{role} pool: {us} ours + {them} opponents",
    flPbPoolWarn: "※ Ranks are based only on data collected from scrims against us. Opponent numbers are limited to games played against our team; small pools can make ranks volatile.",
    flPbExpSrc: "Two data sources — [Fight Metrics] come from kill/ult events (same data as the Engagements/Ultimates tabs); [Round Metrics] come from the round summary table (same data as the Personal Stats tab). Their baselines may differ.",
    flPbExpFights: "Fights: number of our team's fights in rounds the player appeared in.",
    flPbExpKp: "Kill Participation: average of (player kills ÷ team kills) over fights where the team scored at least one kill.",
    flPbExpFkFd: "FK/FD per fight: share of fights where the player scored / suffered the fight's first kill. FD is lower-is-better — arrows, team-average colors and ranks are all inverted.",
    flPbExpAxes: "Reading a cell: one line — 'value ↑ (#5)'. Value = current period; arrow = vs the player's OWN past window (inverted metrics like FD flip colors; → = no change); parentheses = tied rank within the same-role pool (ours + opponents; inverted metrics rank by the good direction). Hover for pool size ('#5 of 13'), change vs past, samples, pool-average diff, and pool composition. The Signals top/bottom-20% rule also uses rank ÷ pool size.",
    flExpSidebar: "Set the date filter, trend window, perspective, opponent/map and min sample in the left sidebar, then press Apply. With 'All Time' selected, no comparison (Δ/arrows) is shown.",
    flPbExpSignals: "Signals: within metrics whose pool is large enough, top 20% → green (strength), bottom 20% → red (watch). Inverted metrics use the inverted direction. Max 2 per player (watch flags first); display-only — not counted in any summary.",
    flPbExpPool: "The rank pool ignores the opponent/map filters and uses all data in the recent period (so filters cannot shrink the pool into meaninglessness). Min sample: 20 fights (fight metrics) / 10 rounds (round metrics). Pools under 8 players show 'small pool'.",
    flPbExpHeal: "Heal /10min is shown for supports only. Per-10min values are based on the sum of round durations played; rounds without a duration are excluded.",
    // Leaderboard
    flLbTitle: "Leaderboard",
    flLbMetric: "Metric", flLbRole: "Role",
    flLbColRank: "Rank", flLbColTeam: "Team", flLbColValue: "Value",
    flLbUnranked: "Unranked (low sample)",
    flLbSupportOnly: "This metric is tracked for supports only — select the Support role.",
    flLbPoolWarnTpl: "Pool has only {n} players (minimum {min}) — ranks are indicative only.",
    flPbExpLb: "Leaderboard: the same pool as the cell ranks ('Sup #3') — all data in the recent period, ours + opponents, same role, min sample met — with the same tied-rank rule, laid out as a table. It ignores the opponent/map filters (existing pool rule); inverted metrics (e.g. FD/fight) rank the good direction first. Players below the min sample appear at the bottom as 'Unranked' with their value shown.",
    flRowFirstPick: "First Pick Secured", flRowFirstDeath: "First Death Suffered",
    flRowFdTank: "Tank First Death", flRowFdDamage: "DPS First Death", flRowFdSupport: "Support First Death", flRowFdOther: "Other First Death",
    flRowFkTraded: "First Pick Traded", flRowFdTraded: "First Death Traded Back",
    flRowUltUsed: "Fights Using Ults", flRowFirstUlt: "First Ult (Us)", flRowEnemyFirstUlt: "First Ult (Enemy)",
    flRowUltAdv: "Ult Advantage", flRowUltDis: "Ult Disadvantage", flRowUltEven: "Ult Even (both ≥1)",
    flRowUlt1: "1 Ult Invested", flRowUlt2: "2 Ults Invested", flRowUlt3: "3+ Ults Invested",
    flSumAvgUlt: "Avg Ults per Fight (Us)", flSumUltConv: "Ult Conversion (Win% with Ults)",
    flUnknownNotePre: "Fights with undecidable winner (equal survivors = draw): ",
    flUnknownNotePost: " — included in occurrence denominators but excluded from win-rate samples.",
    flExplainTitle: "Metric Definitions",
    flExpWinner: "Fight winner: the team with more survivors when the fight ends. Fights with equal survivors (draws) are excluded from win rates.",
    flExpTwoCols: "Each row carries two different numbers — how often the situation happens is the 'Rate' column; how well we win once in that situation is the win-rate columns.",
    flExpOccur: "Rate / Win rate: our values for the current period. Δ columns (vs opp) compare against the opponents' symmetric situation in the SAME fights — e.g. Δ rate for First Pick = our first-pick rate − opponents' first-pick rate (= our first-death rate). 'Lower is better' situations flip colors; under ±1 pp is gray. Hover a Δ cell for both raw values.",
    flExpFirstPick: "First Pick Secured: we scored the fight's first kill. Rate (higher is better) = how often; WR = whether we actually won those fights.",
    flExpFirstDeath: "First Death Suffered: the fight's first kill was against us. Rate (lower is better) = how often; WR = how often we still turned those fights around.",
    flExpFdRole: "Tank/DPS/Support First Death: breakdown of our first deaths by the victim's hero role. Rate (lower is better) = share within our first deaths; WR = fight win rate in that situation.",
    flExpFkTraded: "First Pick Traded: after our first pick, the enemy killed one of us within 5 seconds. Rate (lower is better) = how often we give the advantage back; WR = whether we still won those fights. A rising WR is good news — it does not mean trades became more frequent.",
    flExpFdTraded: "First Death Traded Back: after suffering first death, we answered with a kill within 5 seconds. Rate (higher is better) = how often we recover; WR = whether we won those fights.",
    flExpUltUsed: "Fights Using Ults: fights where we used at least one ultimate. This row's win rate is the 'Ult Conversion'.",
    flExpFirstUlt: "First Ult (Us/Enemy): which team used the fight's first ultimate. Denominator: fights where any ult was used.",
    flExpUltCount: "Ult Advantage/Disadvantage/Even: we used more / fewer / the same number of ults as the enemy in that fight.",
    flExpUltInvest: "1·2·3+ Ults Invested: win rate by the number of ults we spent in the fight. Winning with fewer ults is more efficient.",
    flExpDryFight: "Dry fights (holding an ult without using it) are not provided — ult charge data is unavailable.",
    flExpTrend: "Trend (vs past) = recent win rate − past win rate. Green ↑ = improved, red ↓ = worse, → under ±1 pp (unchanged). The summary (improved/worse/unchanged) uses this past-based trend; the Δ (vs opp) columns are not counted. Hover the trend cell for past→recent raw values.",
    flExpSample: "Sample: fights counted toward the current-period win rate. Past samples are in the row tooltip. Rows below the min sample are dimmed and marked 'Low sample' in the Status column.",
    flExpStability: "Stability: 'stable' when both current and past samples are at least (min sample × 4), otherwise 'volatile'. Trends on volatile rows can swing wildly — treat them as indicative only.",
    // Ultimate Combo Analysis
    flCmbTitle: "Ultimate Combo Analysis",
    flCmbRoleFilter: "Role filter",
    flCmbGroupBy: "Group combo by",
    flCmbGroupPH: "Player + Hero", flCmbGroupH: "Hero only",
    flCmbSize: "Combo size", flCmbWindow: "Combo window (s)", flCmbTopK: "Top-k", flCmbMinSample: "Min combo sample",
    flCmbGenerate: "Generate ultimate combos",
    flCmbTopTitle: "Top ultimate combos", flCmbBottomTitle: "Bottom ultimate combos",
    flCmbColCombo: "Combo", flCmbColRoles: "Role(s)", flCmbColAvgInvest: "Avg ults invested",
    flCmbPrompt: "Press 'Generate ultimate combos' to aggregate with the current sidebar filters (period · perspective · opponent · map).",
    flCmbEmpty: "No combos match the criteria.",
    flCmbNote: "Win rate is over the current period; trend compares against the same combo's win rate in the trend window. Low-sample combos are dimmed and are not promoted above qualifying ones.",
    flExpCombo1: "Ultimate combo: a TIME CHAIN of our (current perspective) ultimates — an ultimate joins the chain when used within the combo window (default 3s) of our previous ultimate. An opponent ultimate between two of ours BREAKS the chain (the later ult is a response, not a combo — see the Response Analysis below), and a lone ultimate is not a combo. Win rate / Avg ults invested are per fights containing the combo; both count only fights with a decidable winner (draws excluded).",
    flExpCombo2: "Subset counting: when a chain has more ults than the combo size, every subset of size N drawn from the chain members is counted separately (the chain guarantees time proximity) — e.g. a 3-ult chain yields three size-2 combos, so one fight can appear under multiple combos.",
    flExpCombo3: "Caution: combo win rates are correlation, not causation — a combo may only appear on certain maps/opponents/game states, so always read them together with the sample size.",
    // Ultimate Sequence Analysis
    flSeqTitle: "Ultimate Sequence Analysis",
    flSeqStep1: "Step 1 — First ultimate", flSeqStep2: "Step 2 — Top followups",
    flSeqStep3: "Step 3 — Second ultimate", flSeqStep4: "Step 4 — Ultimate interaction",
    flSeqSide: "Side", flSeqSideOur: "Our", flSeqSideOpp: "Opponent",
    flSeqHero: "Hero", flSeqUltWord: "ultimate", flSeqRespWin: "Response window (s)",
    flSeqAnalyze: "Analyze first ultimate", flSeqAnalyze2: "Analyze ultimate interaction",
    flSeqNoData: "No fights with a decidable winner contain the selected ultimate.",
    flSeqSummaryTpl: "{n} fights · {win} win rate · Δ (vs opp) {d} · trend {trend}",
    flSeqTopCounters: "Top counters (opponent followups)", flSeqTopFollowups: "Top same-side followups",
    flSeqColFollow: "Followup ultimate", flSeqColSeqRate: "Sequence rate", flSeqColDWin: "Δ win", flSeqColReact: "Avg response time",
    flSeqNote: "Win rate is always our (current perspective) fight win rate; low-sample rows are flagged and never promoted.",
    flSeqPrefill: "Prefill from a followup", flSeqManualOpt: "(choose manually)",
    flSeqSecondLabel: "Second ultimate",
    flSeqPickSecond: "Pick a second ultimate and press 'Analyze ultimate interaction'.",
    flSeqSameWarn: "The second ultimate is the same as the first — pick a different one.",
    flSeqDiffWord: "difference",
    flSeqStep4Note: "Win rate is our (current perspective) fight win rate; Δ win compares against our overall fight win rate in the current scope. Win-rate differences are correlational, not causal.",
    flExpSeq1: "Ultimate sequence: in fights containing the selected ultimate, any ultimate used strictly AFTER its first use and within the response window (default 3s) is counted as a followup. Equal timestamps (simultaneous use) are NOT counted as followups — simultaneous combos belong to the Combo Analysis section above. Samples, sequence rates and response times all count only fights with a decidable winner (draws excluded).",
    flExpSeq2: "Sequence rate = fights containing the followup ÷ all fights containing the selected ultimate. Avg response time = average gap from the selected ultimate to the followup (first use within each fight). Step 2 Δ win compares against the selected ultimate's overall win rate; Step 4 Δ win compares against our overall fight win rate in scope.",
    flExpSeq3: "Counters: opponent followups after our selected ultimate where our win rate is lowest — meaning we often lose when the opponent answers with that ultimate. Win-rate differences are correlational, not causal — always read them together with the sample size.",
    // Fight VOD list
    flVodMore: "Show more", flVodReact: "response",
    flExpVod: "Click a row to open the list of its sample fights with VOD links. Videos start about 12 seconds before the fight begins.",
    // Ultimate Response (Counter) Analysis
    flCtrTitle: "Ultimate Response (Counter) Analysis",
    flCtrDesc: "When an opponent ultimate opens, which of our ultimates has the best verified win rate as a response — a defensive playbook per opponent ultimate. Click a row to expand all responses.",
    flCtrOverviewTitle: "Opponent key ultimates overview",
    flCtrColEnemyUlt: "Opponent ult", flCtrColWinWith: "Our WR then", flCtrColNoResp: "WR w/o response",
    flCtrColBest: "Best response", flCtrColBestWin: "WR with response", flCtrColBestN: "Response sample",
    flCtrColResp: "Our response ult", flCtrColRespRate: "Response rate", flCtrColDNo: "Δ vs no response",
    flCtrNote: "Win-rate differences are correlational, not causal. Treat low-sample responses as indicative only.",
    flExpCtr1: "Response: every ultimate we use strictly AFTER the opponent ultimate's first use and within the response window (default 3s), including the first followup — identical to the sequence analysis followup rule, reusing the same computation.",
    flExpCtr2: "No response = fights where we used no ultimate within the response window (default 3s) after that opponent ultimate. Δ vs no response = win rate with that response − win rate without any response, directly showing the value of responding. Best response = the highest-win-rate response among those meeting the min sample (otherwise 'Low sample').",
    flExpCtr3: "If we respond with several ultimates in one fight, the fight is counted under each response — so response rates can sum past 100% and do not simply add up with the no-response rate.",
    flExpWindows: "Unified time windows: combos use the combo window (default 3s) for ALLIED ult chains (synergy); responses/sequences use the response window (default 3s) for IMMEDIATE reactions to the opponent's (or selected) ultimate. The two windows are separate settings and can be tuned independently.",

    // ── Map Analysis tab ──
    navMapAnalysis: "Maps",
    maTitle: "Map Analysis",
    maDesc: "Which maps and map types we are strong or weak on — measured evidence for map picks and vetoes.",
    maSummaryOverall: "Overall map win rate", maSummaryBest: "Best map type", maSummaryWorst: "Worst map type",
    maSummaryNone: "No type meets min sample",
    maTypeTitle: "Map type summary",
    maTypeHint: "Click a row to expand per-map stats for that type.",
    maMapsTitle: "Maps",
    maMapsHint: "Click a row to expand that map's match list. Sorted by play rate (desc).",
    maWeeklyTitle: "Weekly trend",
    maColType: "Map type", maColMap: "Map", maColPlayRate: "Play rate", maColMapWin: "Map win rate",
    maColFightWin: "Fight win rate", maColDelta: "Δ (vs opp)", maColTrend: "Trend (vs past)",
    maColTopHeroes: "Top heroes", maColStatus: "Status",
    maCellPlayTpl: "{p} ({n} maps)", maCellWinTpl: "{p} ({w} wins)",
    maMlDate: "Date", maMlOpp: "Opponent", maMlScore: "Score", maMlResult: "Result", maMlLink: "Session",
    maMlOpen: "Open →",
    maResultWin: "W", maResultLoss: "L", maResultDraw: "D", maResultUnknown: "N/A",
    maTopHeroNone: "Low sample",
    maWeeklyRowAll: "All",
    maWeeklyMetricFight: "Fight win rate", maWeeklyMetricMap: "Map win rate", maWeeklyMetricPicks: "Pick count",
    maWeekLabelTpl: "{mon} W{n}",
    maWeekDetailTpl: "{label} detail ({range} · {n} maps)",
    maColPicks: "Picks",
    maWlDrawTpl: "{w}W {l}L {d}D",
    maPushTip: "Uncorrected Push matches are counted as draws.",
    maCorrected: "corrected",
    maWeeklyCellTipTpl: "{range} · {metric} {p} · {w} wins / sample {n}",
    maWeeklyPicksTipTpl: "{range} · {n} picks",
    maWeeklyLowTipTpl: "{range} · sample {n}",
    maTipUsOppTpl: "Us {a} vs Opp {b}",
    maTipTrendTpl: "Past {b} → Recent {a}",
    // Metric explanations
    maExpMapWin: "Map win rate = match-level wins ÷ matches with a recorded result (draws stay in the denominator; matches without a recorded result are excluded). Fight win rate = teamfight wins ÷ fights with a decidable winner. The two metrics use different units — read them together.",
    maExpPlayRate: "Play rate = matches on that map (type) ÷ all matches in scope. Matches with no recorded fights cannot appear in this data and are not counted.",
    maExpDelta: "Δ (vs opp) = our fight win rate − the opponent's fight win rate (the same fights, mirrored). Trend (vs past) = recent-period fight win rate − past-period fight win rate (per the sidebar trend window).",
    maExpTopHeroes: "Top heroes are an APPROXIMATION — full playtime data is unavailable, so we use the fight win rate of fights where we used that hero's ultimate on that map (min {n} fights per hero, sorted by win rate). Appearances without an ultimate are invisible to this metric; treat as indicative only.",
    maExpWeek: "Weeks start on Monday (Mon–Sun) with the most recent week on the right. The week label (e.g. \"Jun W4\") follows that week's Monday — the month is the Monday's month and N is which Monday of that month it is (e.g. the week of Mon Jun 23 = Jun W4). Click a week header to open that week's per-map detail. In win-rate modes, cells with no sample that week show a gray \"—\"; pick-count mode shows match counts without coloring.",
    maExpPushFix: "Push-map caveat: Push logs carry no score, so the automatic result is stored as a draw (0:0). Matches manually corrected in the Sessions screen count with their corrected result; only uncorrected matches remain draws. Corrections are stored separately from the original record and can be reverted anytime.",
    maExpStatus: "No minimum sample — every map/type with at least one match is included. Map win rate cells are colored green/red around the 50% line; read small-sample rows carefully alongside the sample counts in parentheses. The opponent filter is shown only in the opponent perspective (auto-reset when switching back to our perspective).",
    maExpCausal: "Win-rate differences are correlational, not causal — interpret alongside opponent strength, compositions, and patches.",
    // Result correction (Push maps) — scrim creation modal only
    woLabel: "Result correction",
    woNone: "Not corrected",
    woWinSuffix: "win",
    woHint: "Push maps carry no score in the log, so the automatic result is stored as a draw. Pick the actual winner to reflect it in Map Analysis and stats (the original record is preserved).",
    // Post-hoc result correction badge & inline edit (match detail · session match list)
    woBadgeDraw: "Draw · set winner",
    woBadgeOverridden: "Overridden",
    woPick: "Set",
    woSaving: "Saving…",
    woSaveFail: "Failed to save override"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ko');
  const toggleLanguage = () => setLanguage(prev => prev === 'ko' ? 'en' : 'ko');
  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);